import type { SeedArticle } from "./types";

export const CRYPTO_FORENSICS_ARTICLES: SeedArticle[] = [
  // ── crypto L0-L5 ────────────────────────────────────────────────────────
  {
    competencyId: "crypto", depthTier: 0, title: "Cryptography Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is cryptography", content: `Cryptography is the science of securing information through mathematical techniques. It provides four fundamental properties: confidentiality (only intended recipients can read data), integrity (data hasn't been tampered with), authentication (verifying identity), and non-repudiation (sender can't deny sending).\n\nFor security professionals, understanding cryptography is essential — both to evaluate whether systems are properly secured and to identify weaknesses that can be exploited.`, sortOrder: 0 },
      { heading: "Symmetric vs asymmetric encryption", content: `**Symmetric**: Same key for encryption and decryption (AES, ChaCha20). Fast, used for bulk data.\n\n**Asymmetric**: Public key encrypts, private key decrypts (RSA, ECC). Slower, used for key exchange and signatures.\n\nIn practice, systems use both: asymmetric crypto establishes a shared key (key exchange), then symmetric crypto encrypts the data (TLS does exactly this).`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Plaintext/Ciphertext**: Unencrypted/encrypted data\n- **Hash function**: One-way function producing a fixed-size digest (SHA-256, bcrypt)\n- **Digital signature**: Hash signed with a private key, verifiable with the public key\n- **Key exchange**: Establishing a shared secret over an insecure channel (Diffie-Hellman)\n- **Cipher mode**: How a block cipher processes multiple blocks (ECB, CBC, GCM)\n- **IV/Nonce**: Random value ensuring identical plaintexts produce different ciphertexts\n- **HMAC**: Hash-based Message Authentication Code — integrity + authentication`, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-175B (Guideline for Using Cryptographic Standards)\n- Christof Paar & Jan Pelzl, "Understanding Cryptography" (Springer)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 1, title: "Cryptography Basics", recommendedLevel: 1,
    sections: [
      { heading: "Hash functions and password cracking", content: `\`\`\`bash\n# Common hash types\necho -n "password" | md5sum      # 5f4dcc3b5aa765d61d8327deb882cf99\necho -n "password" | sha256sum   # 5e884898da2803...\n\n# Identify hash type\nhashid '5f4dcc3b5aa765d61d8327deb882cf99'\n# [+] MD5\n\n# Crack with hashcat\nhashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt    # MD5\nhashcat -m 1000 hash.txt /usr/share/wordlists/rockyou.txt # NTLM\nhashcat -m 1800 hash.txt /usr/share/wordlists/rockyou.txt # sha512crypt\nhashcat -m 3200 hash.txt /usr/share/wordlists/rockyou.txt # bcrypt\n\n# John the Ripper\njohn --wordlist=/usr/share/wordlists/rockyou.txt hash.txt\njohn --show hash.txt\n\`\`\`\n\nKey insight: fast hashes (MD5, SHA-1, SHA-256) are unsuitable for passwords — they can be brute-forced at billions per second on GPUs. Password hashes should use bcrypt, scrypt, or Argon2.`, sortOrder: 0 },
      { heading: "Encoding vs encryption vs hashing", content: `These are fundamentally different operations:\n\n| Operation | Reversible? | Key needed? | Purpose |\n|-----------|-------------|-------------|----------|\n| Encoding | Yes | No | Data representation (Base64, URL encoding) |\n| Encryption | Yes | Yes | Confidentiality |\n| Hashing | No | No | Integrity, fingerprinting |\n\n\`\`\`bash\n# Base64 encoding (NOT encryption)\necho -n "secret" | base64        # c2VjcmV0\necho "c2VjcmV0" | base64 -d     # secret\n\n# AES encryption with OpenSSL\nopenssl enc -aes-256-cbc -salt -in file.txt -out file.enc -k password\nopenssl enc -aes-256-cbc -d -in file.enc -out file.txt -k password\n\`\`\``, sortOrder: 1 },
      { heading: "Classical ciphers", content: `Understanding classical ciphers builds intuition for cryptanalysis:\n\n- **Caesar cipher**: Shift each letter by a fixed amount. Break with frequency analysis.\n- **Vigenere cipher**: Polyalphabetic substitution with a keyword. Break with Kasiski examination.\n- **XOR cipher**: XOR plaintext with a key. If key is reused, XOR two ciphertexts to eliminate the key.\n\n\`\`\`python\n# Caesar cipher brute force\ndef caesar_bruteforce(ciphertext):\n    for shift in range(26):\n        plain = ''.join(\n            chr((ord(c) - ord('a') - shift) % 26 + ord('a'))\n            if c.isalpha() else c\n            for c in ciphertext.lower()\n        )\n        print(f"Shift {shift:2d}: {plain}")\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-132 (Recommendation for Password-Based Key Derivation)\n- hashcat documentation: hashcat.net/wiki\n- CyberChef: gchq.github.io/CyberChef (online crypto tool)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 2, title: "Applied Cryptography", recommendedLevel: 2,
    sections: [
      { heading: "Block cipher modes", content: `How a block cipher (e.g., AES-128 = 16-byte blocks) handles messages longer than one block:\n\n| Mode | Properties | Vulnerabilities |\n|------|------------|----------------|\n| ECB | Each block encrypted independently | Identical blocks produce identical ciphertext (penguin problem) |\n| CBC | Each block XORed with previous ciphertext | Padding oracle attacks (e.g., POODLE) |\n| CTR | Counter encrypted, XORed with plaintext | Nonce reuse completely breaks security |\n| GCM | CTR + authentication tag | Nonce reuse breaks authentication |\n\nGCM (Galois/Counter Mode) is the standard recommendation — it provides both encryption and authentication (AEAD). Never use ECB for anything beyond single-block encryption.`, sortOrder: 0 },
      { heading: "RSA and asymmetric crypto", content: `RSA is the classic public-key cipher. Its security rests on a one-way asymmetry: multiplying two large primes is cheap, but factoring the product back apart is computationally infeasible.\n\n**How RSA actually works:**\n1. Pick two large primes \`p\` and \`q\`; the modulus is \`n = p·q\`.\n2. Compute Euler's totient \`φ(n) = (p-1)(q-1)\`.\n3. Choose a public exponent \`e\` (commonly 65537), coprime to φ(n).\n4. Compute the private exponent \`d = e⁻¹ mod φ(n)\` (the modular inverse of e).\n5. Public key = \`(n, e)\`; private key = \`(n, d)\`.\n\nEncryption is \`c = mᵉ mod n\`; decryption is \`m = cᵈ mod n\`. It round-trips because \`(mᵉ)ᵈ ≡ m (mod n)\` by Euler's theorem. Recovering \`d\` from the public \`(n, e)\` requires φ(n) — which requires factoring \`n\` back into \`p\` and \`q\`. That factoring step is the hard problem the whole scheme leans on. Raw ("textbook") RSA is deterministic and malleable, so real systems add randomised padding (**OAEP**) — which is exactly why the code below uses \`PKCS1_OAEP\`.\n\n\`\`\`python\nfrom Crypto.PublicKey import RSA\nkey = RSA.generate(2048)\npublic_key = key.publickey()\n\nfrom Crypto.Cipher import PKCS1_OAEP\ncipher = PKCS1_OAEP.new(public_key)   # OAEP padding — never textbook RSA\nciphertext = cipher.encrypt(b"secret message")\n\`\`\`\n\n**Why the classic attacks work** — each breaks a specific *assumption*, not RSA's core:\n- **Small-e cube root** (e=3, no padding): if \`m³ < n\`, then \`c = m³\` never wraps modulo \`n\`, so the plaintext is just the ordinary integer cube root of \`c\` — no factoring required.\n- **Common modulus**: the same \`m\` encrypted under one \`n\` with two coprime exponents \`e₁, e₂\` can be recombined via Bézout coefficients to recover \`m\` with no private key at all.\n- **Fermat factorization**: if \`p\` and \`q\` are close together, \`n\` sits just below a perfect square, so searching \`n = a² - b²\` near \`√n\` factors it in a handful of steps.\n- **Wiener's attack**: if \`d\` is too small (< n^0.25), the continued-fraction expansion of \`e/n\` reveals \`d\` directly.\n\nThe defenses fall straight out of the mechanisms: use \`e = 65537\`, OAEP padding, well-separated random primes, and a full-size \`d\`. NIST recommends ≥ 2048-bit keys (SP 800-57); ECC reaches equivalent strength with far smaller keys (256-bit ECC ≈ 3072-bit RSA).\n\nSource: RFC 8017 (PKCS#1 v2.2); Dan Boneh, "Twenty Years of Attacks on the RSA Cryptosystem" (1999); NIST SP 800-57.`, sortOrder: 1 },
      { heading: "TLS handshake and certificate validation", content: `The TLS handshake is how a client and server agree on encryption keys before any application data flows. Understanding it is the difference between running \`openssl\` and knowing what its output means.\n\n**The handshake, step by step (TLS 1.2):**\n\n\`\`\`mermaid\nsequenceDiagram\n    participant C as Client\n    participant S as Server\n    C->>S: ClientHello (TLS versions, cipher suites, random)\n    S->>C: ServerHello (chosen version + cipher, random)\n    S->>C: Certificate (public key, signed by a CA)\n    Note over C: Validate chain to a trusted root, check hostname, expiry, revocation\n    S->>C: ServerHelloDone\n    C->>S: ClientKeyExchange (ECDHE key material)\n    Note over C,S: Both derive the same session keys\n    C->>S: Finished (encrypted — proves keys match)\n    S->>C: Finished (encrypted)\n    Note over C,S: Application data now encrypted\n\`\`\`\n\n**What each phase does.** The *Hellos* negotiate the highest common TLS version and a cipher suite. The *Certificate* lets the client authenticate the server — it walks the chain up to a trusted root CA and checks the hostname, validity dates, and revocation status. The *key exchange* (ECDHE today) lets both sides derive a shared secret without ever transmitting it; because the ephemeral keys are thrown away afterward, recorded traffic stays safe even if the server's long-term private key later leaks (**forward secrecy**). The *Finished* messages are encrypted with the freshly derived keys, proving both ends computed them identically. TLS 1.3 compresses all of this to a single round-trip and encrypts the certificate itself.\n\nNow the tooling maps directly onto those phases:\n\n\`\`\`bash\n# See the full handshake: negotiated version, cipher, and cert chain\nopenssl s_client -connect target.com:443 -servername target.com\n\n# Force a version — does the server still allow weak TLS 1.0/1.1?\nopenssl s_client -connect target.com:443 -tls1_2\nopenssl s_client -connect target.com:443 -tls1_3\n\n# Enumerate offered cipher suites (the ServerHello choice space)\nnmap --script ssl-enum-ciphers -p 443 target.com\ntestssl.sh target.com\n\n# Validate the certificate chain manually\nopenssl verify -CAfile ca-bundle.crt server.crt\n\`\`\`\n\nCommon issues, and the phase each one breaks: expired/self-signed certs and hostname mismatches fail *certificate validation*; weak cipher suites and TLS 1.0/1.1 weaken the *negotiation*; a missing HSTS header lets an attacker strip TLS before the handshake even begins.\n\nSource: RFC 8446 (TLS 1.3), RFC 5246 (TLS 1.2); Cloudflare "Illustrated TLS Connection"; the net-fundamentals L3 article covers the same handshake in the networking track.`, sortOrder: 2 },
      { heading: "Random number generation", content: `Weak randomness is a recurring source of crypto vulnerabilities:\n\n\`\`\`python\n# BAD: predictable random\nimport random\ntoken = random.randint(0, 999999)  # Mersenne Twister — not cryptographic\n\n# GOOD: cryptographically secure\nimport secrets\ntoken = secrets.token_hex(32)  # Uses os.urandom (kernel CSPRNG)\n\`\`\`\n\n\`\`\`bash\n# Linux CSPRNG\nhead -c 32 /dev/urandom | xxd\n\n# Check entropy pool\ncat /proc/sys/kernel/random/entropy_avail\n\`\`\`\n\nIf you can predict the random number generator's output, you can forge tokens, session IDs, and CSRF tokens.`, sortOrder: 3 },
      { heading: "Sources", content: `- NIST SP 800-57 (Recommendation for Key Management)\n- NIST SP 800-38D (GCM specification)\n- PyCryptodome documentation\n- testssl.sh: github.com/drwetter/testssl.sh`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 3, title: "Advanced Cryptanalysis", recommendedLevel: 3,
    sections: [
      { heading: "Padding oracle attacks", content: `CBC mode with PKCS#7 padding leaks the plaintext when the server reveals whether padding is valid after decryption — turning one boolean ("padding OK?") into a full decryption oracle.\n\n**The mechanism.** In CBC, each plaintext block is \`P[i] = D(C[i]) ⊕ C[i-1]\`, where \`D\` is the raw block decryption and \`C[i-1]\` is the *previous ciphertext block* — which the attacker can freely alter. Send \`C[i]\` preceded by an attacker-chosen block \`C'\`. The server computes \`D(C[i]) ⊕ C'\` and checks its padding. Tweak the last byte of \`C'\` until padding is accepted (\`0x01\`): now you know \`D(C[i])_last ⊕ C'_last = 0x01\`, so \`D(C[i])_last = C'_last ⊕ 0x01\`. XOR that with the *real* previous byte to recover that plaintext byte. Move to the next byte (forcing padding \`0x02 0x02\`) and repeat — one byte at a time, ~128 tries per byte, no key required.\n\n\`\`\`python\n# The oracle: any distinguishable response works\n# - "Invalid padding"        -> padding was wrong\n# - any other error/success  -> padding was correct\n# PKCS#7: the last byte is the padding length, e.g. "HELLO\\x03\\x03\\x03"\n\n# Tool: PadBuster automates the byte-by-byte recovery\npadbuster http://target.com/api?data=ENCRYPTED_B64 ENCRYPTED_B64 16\n\`\`\`\n\nHistorical impact: POODLE (SSLv3), Lucky13 (TLS CBC), the ASP.NET padding oracle. This is why AEAD modes (GCM) — which authenticate the ciphertext *before* decrypting it — are strongly preferred.\n\nSource: Vaudenay, "Security Flaws Induced by CBC Padding Applications" (2002); RFC 5246 §6.2.3.2.`, sortOrder: 0 },
      { heading: "Hash length extension attacks", content: `MD5, SHA-1, and SHA-256 use the **Merkle-Damgård** construction — and that structure is exactly what makes them extensible.\n\n**Why it works.** These hashes absorb the message in fixed-size blocks, carrying a running *internal state* from block to block; the final state, emitted verbatim, *is* the digest. So if you know \`H = SHA256(secret || message)\`, you know the exact internal state the algorithm finished in. Load that state back into a SHA-256 engine and you can keep hashing *more* data — as though you had continued the original computation — without ever learning \`secret\`. The one subtlety is the length padding the algorithm appends internally; you must reproduce it, but it depends only on the total length, so you just guess the secret's length (or sweep a small range).\n\n\`\`\`bash\n# Server computes MAC = SHA256(secret || message); you know MAC + message, not secret.\n# You can forge SHA256(secret || message || glue-padding || "&admin=true"):\nhash_extender --data "original_data" --secret-min 8 --secret-max 32 \\\\\n  --append "admin=true" --signature ORIGINAL_MAC --format sha256\n\`\`\`\n\nDefense: use **HMAC**, which nests the key — \`H(key ⊕ opad || H(key ⊕ ipad || msg))\` — so the output is not a resumable state; or **SHA-3**, a sponge construction that never exposes its full internal state. Never authenticate with a bare \`H(secret || message)\`.\n\nSource: RFC 2104 (HMAC); Ferguson, Schneier & Kohno, *Cryptography Engineering*, §5.4.`, sortOrder: 1 },
      { heading: "Timing attacks on crypto", content: `String comparison timing leaks:\n\n\`\`\`python\n# VULNERABLE: early exit reveals how many bytes match\ndef verify_mac(expected, received):\n    for i in range(len(expected)):\n        if expected[i] != received[i]:\n            return False\n    return True\n\n# SECURE: constant-time comparison\nimport hmac\ndef verify_mac(expected, received):\n    return hmac.compare_digest(expected, received)\n\`\`\`\n\nTiming attacks apply to: MAC verification, password comparison, RSA decryption (via differences in modular exponentiation time). Always use constant-time operations for secret-dependent comparisons.`, sortOrder: 2 },
      { heading: "Elliptic curve cryptography attacks", content: `**First, the ground you need.** ECC works with points \`(x, y)\` on a curve \`y² = x³ + ax + b\` over a finite field \`GF(p)\`. There is a defined "addition" of two points; repeating it gives **scalar multiplication**: \`Q = k·G\` means adding the base point \`G\` to itself \`k\` times. The private key is the scalar \`k\`, the public key is the point \`Q\`. Security rests on the **ECDLP** (Elliptic-Curve Discrete Logarithm Problem): given \`G\` and \`Q\`, recovering \`k\` is infeasible on a well-chosen curve. ECC's appeal is efficiency — a 256-bit curve matches ~3072-bit RSA because no sub-exponential attack (the factoring analogue) is known against it.\n\n**Why the attacks work** — every one sidesteps the ECDLP by pushing the math onto a *weaker structure*:\n- **Invalid curve attack**: if the code never checks the received point actually lies on the agreed curve, the attacker sends a point from a different, weaker curve; the victim's scalar multiplication then runs in an easy group and leaks key bits.\n- **Small subgroup attack**: send a point of small order \`r\`; then \`k·P\` can only take \`r\` distinct values, which reveals \`k mod r\`. Repeat with several small \`r\` and reassemble \`k\` via the Chinese Remainder Theorem.\n- **Twist attack**: the same idea aimed at the curve's *quadratic twist* — if the twist has small factors and x-only code doesn't reject off-curve x-coordinates, the discrete log is solved there instead.\n- **Pohlig-Hellman**: the umbrella technique behind the others — if the group order factors into small primes, solve the discrete log in each small subgroup and recombine via CRT. This is *why* secure curves are chosen to have prime (or near-prime) order.\n\n\`\`\`python\n# SageMath: is this curve safe? Check the order's factorization\nE = EllipticCurve(GF(p), [a, b])\nprint(f"Order: {E.order()}")\nprint(f"Factored: {factor(E.order())}")\n# Small factors => Pohlig-Hellman applies => the curve is weak\n\`\`\`\n\nSource: RFC 6090 (fundamental ECC), NIST SP 800-186; Pohlig & Hellman (1978); the CryptoHack ECC track for hands-on practice.`, sortOrder: 3 },
      { heading: "Sources", content: `- Serge Vaudenay, "Security Flaws Induced by CBC Padding" (2002)\n- Thai Duong & Juliano Rizzo, "Practical Padding Oracle Attacks" (2010)\n- NIST SP 800-186 (Recommendations for Discrete Logarithm-Based Cryptography: Elliptic Curve Cryptography)\n- CryptoPals challenges: cryptopals.com`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 4, title: "Expert Cryptographic Techniques", recommendedLevel: 4,
    sections: [
      { heading: "Side-channel attacks on cryptographic implementations", content: `Implementation flaws leak secrets through physical or timing side channels:\n\n**Power analysis**: Measure power consumption during RSA operations — different operations for 0/1 bits consume different power.\n\n**Electromagnetic emanations**: Similar to power analysis but measured remotely via EM radiation.\n\n**Cache timing (Flush+Reload, Prime+Probe)**: Measure cache access times to infer which memory lines were accessed by AES table lookups.\n\n\`\`\`python\n# Timing attack on modular exponentiation (simplified)\n# Square-and-multiply: for each bit of the exponent\n# bit=1: square, then multiply (takes longer)\n# bit=0: square only (takes less time)\n# Measure execution time per bit to recover the private key\n\`\`\`\n\nMitigation: constant-time implementations, blinding (randomize inputs), hardware AES instructions (AES-NI avoids table lookups).`, sortOrder: 0 },
      { heading: "Advanced hash cracking techniques", content: `\`\`\`bash\n# Rule-based attacks (much more effective than pure brute force)\nhashcat -m 1000 hashes.txt rockyou.txt -r /usr/share/hashcat/rules/best64.rule\n\n# Mask attacks (known pattern)\nhashcat -m 1000 hashes.txt -a 3 '?u?l?l?l?l?l?d?d?d?d'\n# Matches: Password1234, Sunshine5678, etc.\n\n# Combinator attack\nhashcat -m 1000 hashes.txt -a 1 words1.txt words2.txt\n\n# PRINCE attack (pipe dictionary through princeprocessor)\n# princeprocessor generates word combinations; hashcat cracks them\n# (see hashcat.net/wiki/doku.php?id=princeprocessor)\nprinceprocessor --pw-min=8 < rockyou.txt | hashcat -m 1000 hashes.txt\n\n# Performance reference (RTX 4090):\n# MD5:     ~165 GH/s\n# NTLM:    ~300 GH/s\n# SHA-256: ~22 GH/s\n# bcrypt:  ~180 kH/s (intentionally slow)\n\`\`\``, sortOrder: 1 },
      { heading: "Protocol-level crypto attacks", content: `Attacks on cryptographic protocols rather than primitives:\n\n- **Bleichenbacher's attack** (ROBOT): Adaptive chosen-ciphertext attack on PKCS#1 v1.5 RSA encryption. Send crafted ciphertexts, observe padding errors to decrypt.\n- **DROWN**: Cross-protocol attack — use SSLv2 support to decrypt TLS sessions.\n- **Logjam**: Downgrade to export-grade 512-bit Diffie-Hellman; precompute discrete log for common primes.\n- **CRIME/BREACH**: Compression oracles — if TLS compresses data, response size reveals whether a guessed string matches a secret in the response.\n\nMitigation: disable legacy protocols, use ECDHE for key exchange, disable compression, use TLS 1.3 (removes vulnerable options).`, sortOrder: 2 },
      { heading: "Sources", content: `- CryptoPals challenges: cryptopals.com (sets 4-6 cover these attacks)\n- Daniel Bleichenbacher, "Chosen Ciphertext Attacks Against Protocols Based on the RSA Encryption Standard PKCS#1" (1998)\n- hashcat wiki: hashcat.net/wiki\n- NIST SP 800-131A (Transitioning the Use of Cryptographic Algorithms)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 5, title: "Cryptography Internals", recommendedLevel: 5,
    sections: [
      { heading: "AES internals", content: `AES operates on a 4x4 byte matrix (state) through rounds:\n\n1. **SubBytes**: Non-linear substitution using the S-box (derived from GF(2^8) inversion)\n2. **ShiftRows**: Cyclically shift rows by 0, 1, 2, 3 positions\n3. **MixColumns**: Matrix multiplication in GF(2^8) — provides diffusion\n4. **AddRoundKey**: XOR state with round key\n\nAES-128: 10 rounds. AES-256: 14 rounds.\n\nAttacks on reduced-round AES exist (Square attack on 4-round, biclique on full AES — reduces security from 128 to 126.1 bits, practically irrelevant). Full AES remains unbroken.\n\n\`\`\`c\n// AES-NI hardware instruction (x86)\n// Single instruction performs one round of AES\n__m128i aesenc(__m128i data, __m128i key);\n// Eliminates cache-timing side channels entirely\n\`\`\``, sortOrder: 0 },
      { heading: "Post-quantum cryptography", content: `Quantum computers threaten current asymmetric cryptography:\n\n| Algorithm | Quantum threat | Status |\n|-----------|---------------|--------|\n| RSA | Shor's algorithm breaks it | Replace with ML-KEM |\n| ECC/ECDSA | Shor's algorithm breaks it | Replace with ML-DSA |\n| AES-128 | Grover's reduces to 64-bit | Use AES-256 |\n| SHA-256 | Grover's reduces to 128-bit | Adequate |\n\nNIST PQC standards (2024):\n- **ML-KEM** (Kyber): Key encapsulation (key exchange)\n- **ML-DSA** (Dilithium): Digital signatures\n- **SLH-DSA** (SPHINCS+): Hash-based signatures (conservative fallback)\n\nHybrid approaches (e.g., X25519 + ML-KEM) are recommended during the transition — protect against both classical and quantum adversaries.`, sortOrder: 1 },
      { heading: "Zero-knowledge proofs and advanced protocols", content: `ZKPs allow proving a statement is true without revealing why:\n\n- **zk-SNARKs**: Succinct proofs, trusted setup required. Used in Zcash.\n- **zk-STARKs**: No trusted setup, larger proofs. Used in StarkNet.\n- **Bulletproofs**: Range proofs without trusted setup. Used in Monero.\n\nPractical applications beyond cryptocurrency:\n- Authentication without revealing the password\n- Proving age > 18 without revealing date of birth\n- Verifiable computation: prove a computation was done correctly\n\nFor security professionals: understanding ZKPs helps evaluate privacy-preserving protocols and identify implementation weaknesses.`, sortOrder: 2 },
      { heading: "Sources", content: `- NIST FIPS 197 (AES specification)\n- NIST FIPS 203, 204, 205 (ML-KEM, ML-DSA, SLH-DSA)\n- Joan Daemen & Vincent Rijmen, "The Design of Rijndael" (Springer)\n- NIST Post-Quantum Cryptography project: nist.gov/pqcrypto`, sortOrder: 3 },
    ],
  },

  // ── forensics L0-L5 ─────────────────────────────────────────────────────
  {
    competencyId: "forensics", depthTier: 0, title: "Digital Forensics Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is digital forensics", content: `Digital forensics is the process of collecting, preserving, analyzing, and presenting digital evidence. It's used in incident response (what happened? how?), legal proceedings, and security research.\n\nForensics applies to: disk images, memory dumps, network captures, mobile devices, cloud environments, and IoT devices. The key principle is maintaining the chain of custody — evidence must be handled so its integrity can be proven.`, sortOrder: 0 },
      { heading: "Why forensics matters for security", content: `- **Incident response**: Determine the scope and impact of a breach\n- **Malware analysis**: Understand what malicious software does\n- **CTF challenges**: Forensics is a major category in competitions\n- **Threat intelligence**: Understand attacker techniques and infrastructure\n- **Legal proceedings**: Produce evidence that holds up in court`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Disk image**: Bit-for-bit copy of a storage device\n- **Memory dump**: Snapshot of RAM contents at a point in time\n- **Artifact**: A trace left by activity (log entry, registry key, file metadata)\n- **Timeline**: Chronological reconstruction of events from multiple artifact sources\n- **Volatility order**: Most volatile evidence first (RAM > running processes > disk > logs)\n- **Chain of custody**: Documentation of evidence handling\n- **Steganography**: Hiding data within other data (images, audio)`, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-86 (Guide to Integrating Forensic Techniques)\n- SANS DFIR resources: sans.org/digital-forensics-incident-response\n- RFC 3227 (Guidelines for Evidence Collection and Archiving)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 1, title: "Forensics Basics", recommendedLevel: 1,
    sections: [
      { heading: "File analysis fundamentals", content: `\`\`\`bash\n# Identify file type (regardless of extension)\nfile mystery_file\n# mystery_file: PNG image data, 800 x 600\n\n# View hex dump\nxxd mystery_file | head -20\nhexdump -C mystery_file | head -20\n\n# Common file signatures (magic bytes)\n# PDF:  25 50 44 46 (%PDF)\n# PNG:  89 50 4E 47 (.PNG)\n# JPEG: FF D8 FF\n# ZIP:  50 4B 03 04 (PK..)\n# ELF:  7F 45 4C 46 (.ELF)\n\n# Extract metadata\nexiftool image.jpg\n# Shows: camera model, GPS coordinates, timestamps, software\n\n# Search for strings in binary files\nstrings binary_file | grep -i password\nstrings -e l binary_file  # little-endian Unicode\n\`\`\``, sortOrder: 0 },
      { heading: "Steganography basics", content: `Steganography hides the *existence* of a message, not just its meaning (that is cryptography). The goal is a carrier — an image, audio file, or document — that looks perfectly normal while secretly holding data. Three mechanisms cover most CTF and real-world cases:\n\n**1. LSB (Least Significant Bit) embedding.** Each pixel channel is a byte (0–255). Flipping its lowest bit changes the color by at most 1/256 — invisible to the eye. Store one secret bit per channel and a 1000×1000 RGB image quietly carries ~370 KB.\n\n\`\`\`\nCover byte:   1 0 0 1 0 1 1 |0|   (blue channel = 150)\nSecret bit:                 |1|\nStego byte:   1 0 0 1 0 1 1 |1|   (blue channel = 151, indistinguishable)\n\`\`\`\n\n\`zsteg\` attacks this by reading out those low-bit planes and looking for structure (text, file headers).\n\n**2. Appended data.** Formats like PNG and JPEG have an explicit *end-of-file marker*; viewers stop reading there, so any bytes tacked on afterward are ignored on screen but sit plainly on disk. That is why a ZIP glued after a PNG still opens as an image — and why \`binwalk\`, which scans for known file signatures *anywhere* in the byte stream, spots both files.\n\n**3. Frequency-domain hiding (audio).** Data encoded at specific frequencies is inaudible but shows up as shapes in a **spectrogram** (Audacity → Spectrogram view).\n\n\`\`\`bash\n# Password-protected embedding (JPEG/BMP/WAV)\nsteghide info image.jpg\nsteghide extract -sf image.jpg\n\n# LSB analysis on PNG/BMP\nzsteg image.png\nzsteg -a image.png            # try every bit-order / channel combination\n\n# Appended / embedded files\nbinwalk image.png             # list detected signatures\nbinwalk -e image.png          # carve them out\n\`\`\`\n\nSource: Fridrich, *Steganography in Digital Media* (Cambridge, 2010); zsteg and binwalk documentation.`, sortOrder: 1 },
      { heading: "Log analysis", content: `\`\`\`bash\n# Linux auth logs\ngrep "Failed password" /var/log/auth.log | \\n  awk '{print $11}' | sort | uniq -c | sort -rn | head\n# Shows top IPs with failed login attempts\n\n# Apache/nginx access logs\ncat access.log | awk '{print $1}' | sort | uniq -c | sort -rn | head\n# Top requesting IPs\n\n# Look for suspicious patterns\ngrep -E "(\\.\\./|select|union|<script)" access.log\n# Directory traversal, SQL injection, XSS attempts\n\n# Windows Event Logs (with evtx_dump)\nevtx_dump Security.evtx | grep -A5 "EventID.*4625"  # Failed logins\nevtx_dump Security.evtx | grep -A5 "EventID.*4624"  # Successful logins\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-86 (Guide to Integrating Forensic Techniques)\n- steghide documentation\n- binwalk: github.com/ReFirmLabs/binwalk\n- man pages: file(1), strings(1), xxd(1)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 2, title: "Digital Forensics in Depth", recommendedLevel: 2,
    sections: [
      { heading: "Disk forensics with Autopsy and Sleuth Kit", content: `**The core principle: never analyze the original.** You work on a *bit-for-bit copy*, and a hash proves the copy is identical to the source and stayed unchanged throughout — that is what makes the evidence defensible in the first place. From there you descend a layered model: raw disk → partitions → filesystem → inodes (metadata) → file content. Each Sleuth Kit tool operates at one layer, which is why you pass a partition *offset* (\`-o 2048\`): it tells the tool where the filesystem begins inside the whole-disk image.\n\n\`\`\`bash\n# 1. Image the disk (dcfldd hashes while it copies — proves integrity)\ndd if=/dev/sda of=disk.raw bs=4M status=progress\ndcfldd if=/dev/sda of=disk.raw hash=sha256 hashlog=disk.hash\nsha256sum disk.raw            # re-verify the copy is unchanged\n\n# 2. Walk the layers with The Sleuth Kit\nmmls disk.raw                # partition layer: find the offset\nfls -r disk.raw -o 2048      # filesystem layer: list files (incl. deleted)\nicat disk.raw -o 2048 42     # content layer: extract a file by inode number\n\n# 3. Build a MAC-times timeline (Modified / Accessed / Changed)\nfls -r -m "/" disk.raw -o 2048 > bodyfile.txt\nmactime -b bodyfile.txt -d > timeline.csv\n\`\`\`\n\nAutopsy (the GUI frontend for Sleuth Kit) wraps all of this with keyword search, hash filtering, timeline visualization, and carved-file recovery.\n\nSource: Brian Carrier, *File System Forensic Analysis* (Addison-Wesley); The Sleuth Kit documentation.`, sortOrder: 0 },
      { heading: "Memory forensics with Volatility", content: `**Why memory forensics exists.** RAM holds live state that may never touch disk: decrypted data, encryption keys, injected malware, running processes, and open network connections. Pull the plug and it is gone — so responders capture a **memory dump** (a raw snapshot of physical RAM) while the machine is live. Volatility's job is to *reconstruct operating-system structures from those raw bytes* — it knows the layout of kernel objects and walks them the way the OS itself does.\n\n**How process listing works — and why there are two of them.** The kernel tracks running processes as \`EPROCESS\` objects in a doubly-linked list. \`pslist\` walks that list, exactly like Task Manager. But a rootkit can *unlink* its process from the list to hide it (DKOM — Direct Kernel Object Manipulation) while the process keeps running. \`psscan\` ignores the list and instead scans all of memory for the byte *signature* of an \`EPROCESS\` object, so it catches processes that were unlinked or have already exited. Diffing the two lists is a classic way to surface hidden malware.\n\n\`\`\`mermaid\nflowchart LR\n    subgraph P1["windows.pslist"]\n        L["walk EPROCESS linked list"] --> V1["sees only linked processes"]\n    end\n    subgraph P2["windows.psscan"]\n        S["scan raw memory for EPROCESS signature"] --> V2["also finds unlinked / exited"]\n    end\n    V1 -. difference reveals hidden process .-> V2\n\`\`\`\n\n\`\`\`bash\n# Identify the image (Volatility 2 needs a profile; Vol 3 auto-detects)\nvol.py -f memory.dmp imageinfo\nvol3 -f memory.dmp windows.info\n\n# Processes: linked list vs raw scan (diff them to reveal hidden ones)\nvol3 -f memory.dmp windows.pslist\nvol3 -f memory.dmp windows.pstree\nvol3 -f memory.dmp windows.psscan\n\n# Live network state, command lines, files, registry — all rebuilt from RAM\nvol3 -f memory.dmp windows.netscan\nvol3 -f memory.dmp windows.cmdline\nvol3 -f memory.dmp windows.dumpfiles --pid 1234\nvol3 -f memory.dmp windows.registry.hivelist\nvol3 -f memory.dmp windows.registry.printkey --key "Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run"\n\`\`\`\n\nSource: Ligh et al., *The Art of Memory Forensics* (Wiley); Volatility 3 documentation. The kernel structures themselves are detailed in the forensics L5 article.`, sortOrder: 1 },
      { heading: "Network forensics", content: `A **pcap** is a recorded stream of raw packets. Network forensics reassembles those packets back into meaningful units — TCP sessions, transferred files, DNS lookups — to answer "who talked to whom, and what crossed the wire?" It works because cleartext protocols (HTTP, FTP, DNS) carry their payload in plain view, and even encrypted traffic leaks metadata: endpoints, timing, sizes, and the DNS names looked up beforehand.\n\nEach query below targets a specific investigative question:\n\n\`\`\`bash\n# Overview: traffic volume over time (spot spikes / periodic beaconing)\ntshark -r capture.pcap -q -z io,stat,1\n\n# Reconstruct transferred files from the reassembled byte stream\ntshark -r capture.pcap --export-objects http,exported_files/\n\n# What names were resolved? (C2 domains, staging hosts)\ntshark -r capture.pcap -Y "dns.flags.response == 0" -T fields -e dns.qry.name | sort | uniq -c | sort -rn\n\n# Credentials sent in the clear (why cleartext protocols are dangerous)\ntshark -r capture.pcap -Y "http.authorization" -T fields -e http.authorization\ntshark -r capture.pcap -Y "ftp.request.command == USER || ftp.request.command == PASS"\n\n# Exfiltration signal: abnormally long DNS labels = data tunneled inside queries\ntshark -r capture.pcap -Y "dns.qry.name.len > 50" -T fields -e dns.qry.name\n\`\`\`\n\nSource: Davidoff & Ham, *Network Forensics: Tracking Hackers through Cyberspace* (Prentice Hall); Wireshark User's Guide.`, sortOrder: 2 },
      { heading: "File carving and recovery", content: `\`\`\`bash\n# Recover deleted files from disk image\nforemost -i disk.raw -o recovered/\nphotorec disk.raw\n\n# Scalpel (configurable carving)\nscalpel -c /etc/scalpel/scalpel.conf -o output/ disk.raw\n\n# From memory\nvol3 -f memory.dmp windows.filescan | grep ".doc\\|.pdf\\|.txt"\nvol3 -f memory.dmp windows.dumpfiles --virtaddr 0xfa8001234567\n\`\`\`\n\nFile carving recovers files based on header/footer signatures, even when filesystem metadata is destroyed. It works on unallocated space, formatted drives, and damaged images.`, sortOrder: 3 },
      { heading: "Sources", content: `- Volatility 3 documentation: volatility3.readthedocs.io\n- The Sleuth Kit: sleuthkit.org\n- Autopsy: autopsy.com/documentation\n- SANS DFIR cheat sheets`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 3, title: "Advanced Forensic Techniques", recommendedLevel: 3,
    sections: [
      { heading: "Windows forensic artifacts", content: `Key Windows artifacts for investigation:\n\n**Registry**:\n- \`NTUSER.DAT\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RecentDocs\` — recently opened files\n- \`SYSTEM\\CurrentControlSet\\Services\` — installed services\n- \`SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\` — persistence\n- \`SAM\` — local user accounts and password hashes\n\n**Prefetch** (\`C:\\Windows\\Prefetch\\*.pf\`): Records of program execution — name, run count, timestamps, files loaded.\n\n**Amcache** (\`C:\\Windows\\AppCompat\\Programs\\Amcache.hve\`): SHA1 hashes of executed programs.\n\n**ShimCache**: Application compatibility cache — tracks executable paths and timestamps.\n\n**Event Logs**: Security (logon/logoff), System (services), PowerShell (script execution).\n\n\`\`\`bash\n# Parse prefetch files\npython3 PECmd.py -d C:\\Windows\\Prefetch --csv output/\n\n# Parse Amcache\npython3 AmcacheParser.py -f Amcache.hve --csv output/\n\`\`\``, sortOrder: 0 },
      { heading: "Linux forensic artifacts", content: `\`\`\`bash\n# User activity\ncat /home/user/.bash_history\ncat /home/user/.zsh_history\ncat /home/user/.local/share/recently-used.xbel\n\n# Authentication\n/var/log/auth.log\n/var/log/secure\nlast -f /var/log/wtmp     # login history\nlastb -f /var/log/btmp    # failed logins\n\n# System activity\n/var/log/syslog\njournalctl --since "2024-01-01" --until "2024-01-02"\n\n# Cron execution\ngrep CRON /var/log/syslog\ncrontab -l -u root\nls -la /etc/cron.d/\n\n# Filesystem timestamps\nstat suspicious_file\n# Access, Modify, Change, Birth times\n\n# Find recently modified files\nfind / -mtime -1 -type f 2>/dev/null\nfind / -newer /tmp/reference_file -type f 2>/dev/null\n\`\`\``, sortOrder: 1 },
      { heading: "Malware triage", content: `Initial analysis of a suspicious file:\n\n\`\`\`bash\n# Static analysis\nfile malware.exe\nstrings malware.exe | less\nstrings -e l malware.exe  # Unicode strings\n\n# PE analysis\npython3 -c "import pefile; pe = pefile.PE('malware.exe'); print(pe.dump_info())"\n\n# Check imports for suspicious APIs\n# VirtualAlloc, WriteProcessMemory → injection\n# CreateRemoteThread → thread injection\n# WinExec, ShellExecute → execution\n# InternetOpen, URLDownloadToFile → C2 communication\n\n# Hash lookup\nsha256sum malware.exe\n# Check against VirusTotal, MalwareBazaar\n\n# Sandbox execution\n# Upload to Any.Run, Hybrid Analysis, or Joe Sandbox\n\`\`\``, sortOrder: 2 },
      { heading: "Timeline analysis", content: `Correlate events across multiple artifact sources:\n\n\`\`\`bash\n# Build a super-timeline with Plaso\nlog2timeline.py timeline.plaso disk.raw\npsort.py -o l2tcsv timeline.plaso -w timeline.csv\n\n# Filter the timeline\npsort.py -o l2tcsv timeline.plaso "date > '2024-06-01' AND date < '2024-06-02'" -w filtered.csv\n\n# Key artifacts to correlate:\n# 1. File creation/modification times\n# 2. Registry modification times\n# 3. Event log entries\n# 4. Prefetch execution times\n# 5. Browser history timestamps\n# 6. Network connection logs\n\`\`\`\n\nThe timeline reveals the sequence: initial access → execution → persistence → lateral movement → data exfiltration. Each phase leaves different artifacts.`, sortOrder: 3 },
      { heading: "Sources", content: `- SANS DFIR Poster: digital forensic artifact reference\n- Eric Zimmerman's tools: ericzimmerman.github.io\n- Plaso documentation: plaso.readthedocs.io\n- MITRE ATT&CK mapped to forensic artifacts`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 4, title: "Expert Forensics Techniques", recommendedLevel: 4,
    sections: [
      { heading: "Advanced memory forensics", content: `Beyond basic process listing:\n\n\`\`\`bash\n# Detect process injection\nvol3 -f memory.dmp windows.malfind\n# Finds: executable pages in process memory not backed by files\n# Common indicator: MZ header in non-image memory regions\n\n# SSDT hooks (System Service Descriptor Table)\nvol3 -f memory.dmp windows.ssdt\n# Hooks redirect system calls — rootkit indicator\n\n# Kernel module analysis\nvol3 -f memory.dmp windows.modules\nvol3 -f memory.dmp windows.modscan  # find hidden modules\n\n# Extract process memory for analysis\nvol3 -f memory.dmp windows.memmap --pid 1234 --dump\n\n# Yara scanning in memory\nvol3 -f memory.dmp yarascan.YaraScan --yara-rules malware_rules.yar\n\`\`\``, sortOrder: 0 },
      { heading: "Anti-forensics detection", content: `Attackers try to cover their tracks:\n\n- **Timestomping**: Modify file timestamps with tools like Timestomp. Detection: compare $STANDARD_INFORMATION vs $FILE_NAME timestamps in NTFS (MFT analysis). $FILE_NAME times are harder to modify.\n- **Log clearing**: Detect via Event ID 1102 (audit log cleared), or gaps in sequential event IDs.\n- **Secure deletion**: Tools like sdelete overwrite file data. Detection: look for MFT entries without corresponding data, or SDelete artifacts in prefetch.\n- **Process hollowing**: Legitimate process with injected code. Detection: compare in-memory image to on-disk binary.\n\n\`\`\`bash\n# Detect timestomping with MFT analysis\nanalyzeMFT.py -f $MFT -o mft_output.csv\n# Compare SI_Created vs FN_Created timestamps\n# Large discrepancies indicate timestomping\n\`\`\``, sortOrder: 1 },
      { heading: "Cloud forensics", content: `Cloud environments require different approaches:\n\n\`\`\`bash\n# AWS CloudTrail analysis\naws cloudtrail lookup-events \\\\\n  --lookup-attributes AttributeKey=EventName,AttributeValue=ConsoleLogin\n\n# Key events to investigate:\n# - ConsoleLogin (especially from unusual locations)\n# - CreateUser, AttachUserPolicy (persistence)\n# - GetSecretValue (credential access)\n# - StopLogging, DeleteTrail (anti-forensics)\n# - RunInstances (cryptomining)\n\n# Azure Activity Log\naz monitor activity-log list --start-time 2024-01-01 --end-time 2024-01-02\n\n# GCP Cloud Audit Logs\ngcloud logging read 'resource.type="gce_instance"' --limit 100\n\`\`\`\n\nChallenge: cloud providers control the infrastructure — you can't image a cloud VM's hypervisor layer. Focus on API logs, flow logs, and application-level artifacts.`, sortOrder: 2 },
      { heading: "Sources", content: `- Volatility 3 plugin reference\n- SANS FOR508: Advanced Incident Response\n- AWS CloudTrail documentation\n- Harlan Carvey, "Windows Forensic Analysis Toolkit" (Syngress)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 5, title: "Forensics Internals", recommendedLevel: 5,
    sections: [
      { heading: "NTFS internals for forensics", content: `NTFS stores metadata in the Master File Table (MFT). Each file has an MFT entry with attributes:\n\n- **$STANDARD_INFORMATION**: Timestamps (created, modified, accessed, MFT modified), permissions\n- **$FILE_NAME**: Alternative timestamps (set by the kernel, harder to forge), short/long filenames\n- **$DATA**: File content (resident if < ~700 bytes, non-resident otherwise)\n- **$ATTRIBUTE_LIST**: Points to additional MFT entries for files with many attributes\n\n\`\`\`\nMFT Entry structure:\n  Header (fixup, sequence number, link count)\n  $STANDARD_INFORMATION\n  $FILE_NAME\n  $DATA (or pointer to clusters)\n  $INDEX_ROOT / $INDEX_ALLOCATION (for directories)\n\`\`\`\n\nDeleted files: the MFT entry is marked as unused but not overwritten. Data clusters are marked as free but remain until overwritten — this is why carving works.`, sortOrder: 0 },
      { heading: "Windows memory structures", content: `Understanding kernel structures for memory forensics:\n\n- **EPROCESS**: Kernel object representing a process. Contains PID, parent PID, image filename, handle table, token, VAD tree.\n- **PEB** (Process Environment Block): Usermode structure with loaded DLLs, command line, environment variables.\n- **VAD** (Virtual Address Descriptor): Tree describing the process's virtual memory layout — what's mapped where.\n- **Pool tags**: Kernel allocations are tagged (e.g., 'Proc' for process objects). Pool scanning finds objects even when unlinked from active lists.\n\n\`\`\`bash\n# Volatility uses these structures:\n# pslist: walks the ActiveProcessLinks doubly-linked list in EPROCESS\n# psscan: scans for EPROCESS pool tags (finds hidden/terminated processes)\n# vadinfo: dumps the VAD tree (shows memory regions and their protections)\n\`\`\`\n\nRootkits hide by unlinking EPROCESS from the ActiveProcessLinks list — psscan bypasses this by scanning raw memory.`, sortOrder: 1 },
      { heading: "Firmware and UEFI forensics", content: `Below the OS, firmware can harbor persistent threats:\n\n- **UEFI implants**: Survive OS reinstallation. Modify the SPI flash chip containing the firmware.\n- **Bootkits**: Compromise the boot process before the OS loads.\n- **Analysis tools**: CHIPSEC (Intel firmware security assessment), UEFITool (firmware image parser)\n\n\`\`\`bash\n# Dump UEFI firmware\nchipsec_util spi dump firmware.bin\n\n# Analyze with UEFITool\n# Look for: unexpected DXE drivers, modified boot manager,\n# unsigned modules in the firmware volume\n\n# Check Secure Boot state\nchipsec_main -m common.secureboot.variables\n\`\`\`\n\nReal-world examples: Hacking Team's UEFI rootkit (2015), LoJax (2018, first UEFI rootkit found in the wild by ESET), CosmicStrand (2022, Kaspersky).`, sortOrder: 2 },
      { heading: "Sources", content: `- Brian Carrier, "File System Forensic Analysis" (Addison-Wesley)\n- NTFS specification: flatcap.github.io/linux-ntfs/ntfs/index.html\n- CHIPSEC: github.com/chipsec/chipsec\n- ESET research: "LoJax: First UEFI rootkit found in the wild"`, sortOrder: 3 },
    ],
  },
];
