import type { SeedArticle } from "./types";

export const CRYPTO_FORENSICS_ARTICLES: SeedArticle[] = [
  // ── crypto L0-L5 ────────────────────────────────────────────────────────
  {
    competencyId: "crypto", depthTier: 0, title: "Cryptography Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is cryptography", content: `Cryptography is the science of securing information through mathematical techniques. It provides four fundamental properties: confidentiality (only intended recipients can read data), integrity (data hasn't been tampered with), authentication (verifying identity), and non-repudiation (sender can't deny sending).\n\nFor security professionals, understanding cryptography is essential — both to evaluate whether systems are properly secured and to identify weaknesses that can be exploited.`, sortOrder: 0 },
      { heading: "Symmetric vs asymmetric encryption", content: `**Symmetric**: Same key for encryption and decryption (AES, ChaCha20). Fast, used for bulk data.\n\n**Asymmetric**: Public key encrypts, private key decrypts (RSA, ECC). Slower, used for key exchange and signatures.\n\nIn practice, systems use both: asymmetric crypto establishes a shared key (key exchange), then symmetric crypto encrypts the data (TLS does exactly this).`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Plaintext/Ciphertext**: Unencrypted/encrypted data\n- **Hash function**: One-way function producing a fixed-size digest (SHA-256, bcrypt)\n- **Digital signature**: Hash signed with a private key, verifiable with the public key\n- **Key exchange**: Establishing a shared secret over an insecure channel (Diffie-Hellman)\n- **Cipher mode**: How a block cipher processes multiple blocks (ECB, CBC, GCM)\n- **IV/Nonce**: Random value ensuring identical plaintexts produce different ciphertexts\n- **HMAC**: Hash-based Message Authentication Code — integrity + authentication`, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-175B (Guideline for Using Cryptographic Standards)\n- Christof Paar & Jan Pelzl, "Understanding Cryptography" (Springer)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 1, title: "Cryptography Basics", recommendedLevel: 1,
    sections: [
      { heading: "Hash functions and password cracking", content: `\`\`\`bash\n# Common hash types\necho -n "password" | md5sum      # 5f4dcc3b5aa765d61d8327deb882cf99\necho -n "password" | sha256sum   # 5e884898da2803...\n\n# Identify hash type\nhashid '5f4dcc3b5aa765d61d8327deb882cf99'\n# [+] MD5\n\n# Crack with hashcat\nhashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt    # MD5\nhashcat -m 1000 hash.txt /usr/share/wordlists/rockyou.txt # NTLM\nhashcat -m 1800 hash.txt /usr/share/wordlists/rockyou.txt # sha512crypt\nhashcat -m 3200 hash.txt /usr/share/wordlists/rockyou.txt # bcrypt\n\n# John the Ripper\njohn --wordlist=/usr/share/wordlists/rockyou.txt hash.txt\njohn --show hash.txt\n\`\`\`\n\nKey insight: fast hashes (MD5, SHA-1, SHA-256) are unsuitable for passwords — they can be brute-forced at billions per second on GPUs. Password hashes should use bcrypt, scrypt, or Argon2.`, sortOrder: 0 },
      { heading: "Encoding vs encryption vs hashing", content: `These are fundamentally different operations:\n\n| Operation | Reversible? | Key needed? | Purpose |\n|-----------|-------------|-------------|----------|\n| Encoding | Yes | No | Data representation (Base64, URL encoding) |\n| Encryption | Yes | Yes | Confidentiality |\n| Hashing | No | No | Integrity, fingerprinting |\n\n\`\`\`bash\n# Base64 encoding (NOT encryption)\necho -n "secret" | base64        # c2VjcmV0\necho "c2VjcmV0" | base64 -d     # secret\n\n# AES encryption with OpenSSL\nopenssl enc -aes-256-cbc -salt -in file.txt -out file.enc -k password\nopenssl enc -aes-256-cbc -d -in file.enc -out file.txt -k password\n\`\`\``, sortOrder: 1 },
      { heading: "Classical ciphers", content: `Understanding classical ciphers builds intuition for cryptanalysis:\n\n- **Caesar cipher**: Shift each letter by a fixed amount. Break with frequency analysis.\n- **Vigenere cipher**: Polyalphabetic substitution with a keyword. Break with Kasiski examination.\n- **XOR cipher**: XOR plaintext with a key. If key is reused, XOR two ciphertexts to eliminate the key.\n\n\`\`\`python\n# Caesar cipher brute force\ndef caesar_bruteforce(ciphertext):\n    for shift in range(26):\n        plain = ''.join(\n            chr((ord(c) - ord('a') - shift) % 26 + ord('a'))\n            if c.isalpha() else c\n            for c in ciphertext.lower()\n        )\n        print(f"Shift {shift:2d}: {plain}")\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-132 (Recommendation for Password-Based Key Derivation)\n- hashcat documentation: hashcat.net/wiki\n- CyberChef: gchq.github.io/CyberChef (online crypto tool)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 2, title: "Applied Cryptography", recommendedLevel: 2,
    sections: [
      { heading: "Block cipher modes", content: `How a block cipher (e.g., AES-128 = 16-byte blocks) handles messages longer than one block:\n\n| Mode | Properties | Vulnerabilities |\n|------|------------|----------------|\n| ECB | Each block encrypted independently | Identical blocks produce identical ciphertext (penguin problem) |\n| CBC | Each block XORed with previous ciphertext | Padding oracle attacks (e.g., POODLE) |\n| CTR | Counter encrypted, XORed with plaintext | Nonce reuse completely breaks security |\n| GCM | CTR + authentication tag | Nonce reuse breaks authentication |\n\nGCM (Galois/Counter Mode) is the standard recommendation — it provides both encryption and authentication (AEAD). Never use ECB for anything beyond single-block encryption.`, sortOrder: 0 },
      { heading: "RSA and asymmetric crypto", content: `RSA security relies on the difficulty of factoring large numbers:\n\n\`\`\`python\n# RSA key generation (simplified)\nfrom Crypto.PublicKey import RSA\nkey = RSA.generate(2048)\npublic_key = key.publickey()\n\n# Encryption\nfrom Crypto.Cipher import PKCS1_OAEP\ncipher = PKCS1_OAEP.new(public_key)\nciphertext = cipher.encrypt(b"secret message")\n\n# Common RSA attacks:\n# - Small public exponent (e=3) with small message: cube root attack\n# - Common modulus: if same message encrypted with different e, recover plaintext\n# - Fermat factorization: if p and q are close together\n# - Wiener's attack: if private exponent d is small\n\`\`\`\n\nNIST recommends minimum 2048-bit RSA keys (SP 800-57). ECC provides equivalent security with smaller keys (256-bit ECC ~ 3072-bit RSA).`, sortOrder: 1 },
      { heading: "TLS handshake and certificate validation", content: `\`\`\`bash\n# Inspect TLS configuration\nopenssl s_client -connect target.com:443 -servername target.com\n\n# Test specific TLS versions\nopenssl s_client -connect target.com:443 -tls1_2\nopenssl s_client -connect target.com:443 -tls1_3\n\n# Check for weak ciphers\nnmap --script ssl-enum-ciphers -p 443 target.com\ntestssl.sh target.com\n\n# Verify certificate chain\nopenssl verify -CAfile ca-bundle.crt server.crt\n\`\`\`\n\nCommon issues: expired certificates, self-signed certificates, weak cipher suites, TLS 1.0/1.1 still enabled, missing HSTS header.`, sortOrder: 2 },
      { heading: "Random number generation", content: `Weak randomness is a recurring source of crypto vulnerabilities:\n\n\`\`\`python\n# BAD: predictable random\nimport random\ntoken = random.randint(0, 999999)  # Mersenne Twister — not cryptographic\n\n# GOOD: cryptographically secure\nimport secrets\ntoken = secrets.token_hex(32)  # Uses os.urandom (kernel CSPRNG)\n\`\`\`\n\n\`\`\`bash\n# Linux CSPRNG\nhead -c 32 /dev/urandom | xxd\n\n# Check entropy pool\ncat /proc/sys/kernel/random/entropy_avail\n\`\`\`\n\nIf you can predict the random number generator's output, you can forge tokens, session IDs, and CSRF tokens.`, sortOrder: 3 },
      { heading: "Sources", content: `- NIST SP 800-57 (Recommendation for Key Management)\n- NIST SP 800-38D (GCM specification)\n- PyCryptodome documentation\n- testssl.sh: github.com/drwetter/testssl.sh`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 3, title: "Advanced Cryptanalysis", recommendedLevel: 3,
    sections: [
      { heading: "Padding oracle attacks", content: `CBC mode with PKCS#7 padding is vulnerable when the server reveals whether padding is valid:\n\n\`\`\`python\n# Padding oracle attack concept\n# The attacker modifies ciphertext bytes and observes:\n# - "Invalid padding" → padding was wrong\n# - "Decryption successful" or different error → padding was correct\n# By iterating through byte values, the attacker decrypts one byte at a time\n\n# PKCS#7 padding: last byte indicates padding length\n# "HELLO\\x03\\x03\\x03" (3 bytes of padding, each = 0x03)\n\n# Tool: PadBuster\npadbuster http://target.com/api?data=ENCRYPTED_B64 ENCRYPTED_B64 16\n\`\`\`\n\nHistorical impact: POODLE (SSLv3), Lucky13 (TLS CBC), Padding oracle in ASP.NET. This is why AEAD modes (GCM) are strongly preferred.`, sortOrder: 0 },
      { heading: "Hash length extension attacks", content: `MD5, SHA-1, and SHA-256 (Merkle-Damgard construction) are vulnerable to length extension:\n\n\`\`\`bash\n# If a server computes: MAC = SHA256(secret || message)\n# And you know MAC and message (but not secret):\n# You can compute: SHA256(secret || message || padding || extension)\n# Without knowing the secret\n\n# Tool: hash_extender\nhash_extender --data "original_data" --secret-min 8 --secret-max 32 \\\\\n  --append "admin=true" --signature ORIGINAL_MAC --format sha256\n\`\`\`\n\nDefense: use HMAC (which processes the key differently) or SHA-3 (sponge construction, not vulnerable to length extension).`, sortOrder: 1 },
      { heading: "Timing attacks on crypto", content: `String comparison timing leaks:\n\n\`\`\`python\n# VULNERABLE: early exit reveals how many bytes match\ndef verify_mac(expected, received):\n    for i in range(len(expected)):\n        if expected[i] != received[i]:\n            return False\n    return True\n\n# SECURE: constant-time comparison\nimport hmac\ndef verify_mac(expected, received):\n    return hmac.compare_digest(expected, received)\n\`\`\`\n\nTiming attacks apply to: MAC verification, password comparison, RSA decryption (via differences in modular exponentiation time). Always use constant-time operations for secret-dependent comparisons.`, sortOrder: 2 },
      { heading: "Elliptic curve cryptography attacks", content: `ECC attacks for CTF and assessment contexts:\n\n- **Invalid curve attacks**: If the implementation doesn't validate that the received point is on the curve, send a point on a weaker curve\n- **Small subgroup attacks**: Send a point with small order, recover bits of the private key\n- **Twist attacks**: Points on the curve's twist have different security properties\n- **Pohlig-Hellman**: If the curve order has small factors, compute discrete log in each subgroup\n\n\`\`\`python\n# SageMath: check curve parameters\nE = EllipticCurve(GF(p), [a, b])\nprint(f"Order: {E.order()}\")\nprint(f"Factored: {factor(E.order())}\")\n# If order has small factors, Pohlig-Hellman applies\n\`\`\``, sortOrder: 3 },
      { heading: "Sources", content: `- Serge Vaudenay, "Security Flaws Induced by CBC Padding" (2002)\n- Thai Duong & Juliano Rizzo, "Practical Padding Oracle Attacks" (2010)\n- NIST SP 800-186 (Recommendations for Discrete Logarithm-Based Cryptography: Elliptic Curve Cryptography)\n- CryptoPals challenges: cryptopals.com`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 4, title: "Expert Cryptographic Techniques", recommendedLevel: 4,
    sections: [
      { heading: "Side-channel attacks on cryptographic implementations", content: `Implementation flaws leak secrets through physical or timing side channels:\n\n**Power analysis**: Measure power consumption during RSA operations — different operations for 0/1 bits consume different power.\n\n**Electromagnetic emanations**: Similar to power analysis but measured remotely via EM radiation.\n\n**Cache timing (Flush+Reload, Prime+Probe)**: Measure cache access times to infer which memory lines were accessed by AES table lookups.\n\n\`\`\`python\n# Timing attack on modular exponentiation (simplified)\n# Square-and-multiply: for each bit of the exponent\n# bit=1: square, then multiply (takes longer)\n# bit=0: square only (takes less time)\n# Measure execution time per bit to recover the private key\n\`\`\`\n\nMitigation: constant-time implementations, blinding (randomize inputs), hardware AES instructions (AES-NI avoids table lookups).`, sortOrder: 0 },
      { heading: "Advanced hash cracking techniques", content: `\`\`\`bash\n# Rule-based attacks (much more effective than pure brute force)\nhashcat -m 1000 hashes.txt rockyou.txt -r /usr/share/hashcat/rules/best64.rule\n\n# Mask attacks (known pattern)\nhashcat -m 1000 hashes.txt -a 3 '?u?l?l?l?l?l?d?d?d?d'\n# Matches: Password1234, Sunshine5678, etc.\n\n# Combinator attack\nhashcat -m 1000 hashes.txt -a 1 words1.txt words2.txt\n\n# PRINCE attack (pipe dictionary through princeprocessor)\n# princeprocessor generates word combinations; hashcat cracks them\n# (see hashcat.net/wiki/doku.php?id=princeprocessor)\nprinceprocessor --pw-min=8 < rockyou.txt | hashcat -m 1000 hashes.txt\n\n# Performance reference (RTX 4090):\n# MD5:     ~165 GH/s\n# NTLM:    ~300 GH/s\n# SHA-256: ~22 GH/s\n# bcrypt:  ~180 kH/s (intentionally slow)\n\`\`\``, sortOrder: 1 },
      { heading: "Protocol-level crypto attacks", content: `Attacks on cryptographic protocols rather than primitives:\n\n- **Bleichenbacher's attack** (ROBOT): Adaptive chosen-ciphertext attack on PKCS#1 v1.5 RSA encryption. Send crafted ciphertexts, observe padding errors to decrypt.\n- **DROWN**: Cross-protocol attack — use SSLv2 support to decrypt TLS sessions.\n- **Logjam**: Downgrade to export-grade 512-bit Diffie-Hellman; precompute discrete log for common primes.\n- **CRIME/BREACH**: Compression oracles — if TLS compresses data, response size reveals whether a guessed string matches a secret in the response.\n\nMitigation: disable legacy protocols, use ECDHE for key exchange, disable compression, use TLS 1.3 (removes vulnerable options).`, sortOrder: 2 },
      { heading: "Sources", content: `- CryptoPals challenges: cryptopals.com (sets 4-6 cover these attacks)\n- Daniel Bleichenbacher, "Chosen Ciphertext Attacks Against Protocols Based on the RSA Encryption Standard PKCS#1" (1998)\n- hashcat wiki: hashcat.net/wiki\n- NIST SP 800-131A (Transitioning the Use of Cryptographic Algorithms)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "crypto", depthTier: 5, title: "Cryptography Internals", recommendedLevel: 5,
    sections: [
      { heading: "AES internals", content: `AES operates on a 4x4 byte matrix (state) through rounds:\n\n1. **SubBytes**: Non-linear substitution using the S-box (derived from GF(2^8) inversion)\n2. **ShiftRows**: Cyclically shift rows by 0, 1, 2, 3 positions\n3. **MixColumns**: Matrix multiplication in GF(2^8) — provides diffusion\n4. **AddRoundKey**: XOR state with round key\n\nAES-128: 10 rounds. AES-256: 14 rounds.\n\nAttacks on reduced-round AES exist (Square attack on 4-round, biclique on full AES — reduces security from 128 to 126.1 bits, practically irrelevant). Full AES remains unbroken.\n\n\`\`\`c\n// AES-NI hardware instruction (x86)\n// Single instruction performs one round of AES\n__m128i aesenc(__m128i data, __m128i key);\n// Eliminates cache-timing side channels entirely\n\`\`\``, sortOrder: 0 },
      { heading: "Post-quantum cryptography", content: `Quantum computers threaten current asymmetric cryptography:\n\n| Algorithm | Quantum threat | Status |\n|-----------|---------------|--------|\n| RSA | Shor's algorithm breaks it | Replace with ML-KEM |\n| ECC/ECDSA | Shor's algorithm breaks it | Replace with ML-DSA |\n| AES-128 | Grover's reduces to 64-bit | Use AES-256 |\n| SHA-256 | Grover's reduces to 128-bit | Adequate |\n\nNIST PQC standards (2024):\n- **ML-KEM** (Kyber): Key encapsulation (key exchange)\n- **ML-DSA** (Dilithium): Digital signatures\n- **SLH-DSA** (SPHINCS+): Hash-based signatures (conservative fallback)\n\nHybrid approaches (e.g., X25519 + ML-KEM) are recommended during the transition — protect against both classical and quantum adversaries.`, sortOrder: 1 },
      { heading: "Zero-knowledge proofs and advanced protocols", content: `ZKPs allow proving a statement is true without revealing why:\n\n- **zk-SNARKs**: Succinct proofs, trusted setup required. Used in Zcash.\n- **zk-STARKs**: No trusted setup, larger proofs. Used in StarkNet.\n- **Bulletproofs**: Range proofs without trusted setup. Used in Monero.\n\nPractical applications beyond cryptocurrency:\n- Authentication without revealing the password\n- Proving age > 18 without revealing date of birth\n- Verifiable computation: prove a computation was done correctly\n\nFor security professionals: understanding ZKPs helps evaluate privacy-preserving protocols and identify implementation weaknesses.`, sortOrder: 2 },
      { heading: "Sources", content: `- NIST FIPS 197 (AES specification)\n- NIST FIPS 203, 204, 205 (ML-KEM, ML-DSA, SLH-DSA)\n- Joan Daemen & Vincent Rijmen, "The Design of Rijndael" (Springer)\n- NIST Post-Quantum Cryptography project: nist.gov/pqcrypto`, sortOrder: 3 },
    ],
  },

  // ── forensics L0-L5 ─────────────────────────────────────────────────────
  {
    competencyId: "forensics", depthTier: 0, title: "Digital Forensics Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is digital forensics", content: `Digital forensics is the process of collecting, preserving, analyzing, and presenting digital evidence. It's used in incident response (what happened? how?), legal proceedings, and security research.\n\nForensics applies to: disk images, memory dumps, network captures, mobile devices, cloud environments, and IoT devices. The key principle is maintaining the chain of custody — evidence must be handled so its integrity can be proven.`, sortOrder: 0 },
      { heading: "Why forensics matters for security", content: `- **Incident response**: Determine the scope and impact of a breach\n- **Malware analysis**: Understand what malicious software does\n- **CTF challenges**: Forensics is a major category in competitions\n- **Threat intelligence**: Understand attacker techniques and infrastructure\n- **Legal proceedings**: Produce evidence that holds up in court`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Disk image**: Bit-for-bit copy of a storage device\n- **Memory dump**: Snapshot of RAM contents at a point in time\n- **Artifact**: A trace left by activity (log entry, registry key, file metadata)\n- **Timeline**: Chronological reconstruction of events from multiple artifact sources\n- **Volatility order**: Most volatile evidence first (RAM > running processes > disk > logs)\n- **Chain of custody**: Documentation of evidence handling\n- **Steganography**: Hiding data within other data (images, audio)`, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-86 (Guide to Integrating Forensic Techniques)\n- SANS DFIR resources: sans.org/digital-forensics-incident-response\n- RFC 3227 (Guidelines for Evidence Collection and Archiving)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 1, title: "Forensics Basics", recommendedLevel: 1,
    sections: [
      { heading: "File analysis fundamentals", content: `\`\`\`bash\n# Identify file type (regardless of extension)\nfile mystery_file\n# mystery_file: PNG image data, 800 x 600\n\n# View hex dump\nxxd mystery_file | head -20\nhexdump -C mystery_file | head -20\n\n# Common file signatures (magic bytes)\n# PDF:  25 50 44 46 (%PDF)\n# PNG:  89 50 4E 47 (.PNG)\n# JPEG: FF D8 FF\n# ZIP:  50 4B 03 04 (PK..)\n# ELF:  7F 45 4C 46 (.ELF)\n\n# Extract metadata\nexiftool image.jpg\n# Shows: camera model, GPS coordinates, timestamps, software\n\n# Search for strings in binary files\nstrings binary_file | grep -i password\nstrings -e l binary_file  # little-endian Unicode\n\`\`\``, sortOrder: 0 },
      { heading: "Steganography basics", content: `\`\`\`bash\n# Check for hidden data in images\nsteghide info image.jpg\nsteghide extract -sf image.jpg\n\n# LSB steganography detection\nzsteg image.png\nzsteg -a image.png  # try all methods\n\n# Check for appended data\nbinwalk image.png\n# If a ZIP is appended after the PNG end marker:\n# binwalk shows both the PNG and the ZIP\nbinwalk -e image.png  # extract embedded files\n\n# Audio steganography\n# Spectogram analysis in Audacity: View → Spectrogram\n# Hidden images appear as visual patterns in the frequency domain\n\`\`\``, sortOrder: 1 },
      { heading: "Log analysis", content: `\`\`\`bash\n# Linux auth logs\ngrep "Failed password" /var/log/auth.log | \\n  awk '{print $11}' | sort | uniq -c | sort -rn | head\n# Shows top IPs with failed login attempts\n\n# Apache/nginx access logs\ncat access.log | awk '{print $1}' | sort | uniq -c | sort -rn | head\n# Top requesting IPs\n\n# Look for suspicious patterns\ngrep -E "(\\.\\./|select|union|<script)" access.log\n# Directory traversal, SQL injection, XSS attempts\n\n# Windows Event Logs (with evtx_dump)\nevtx_dump Security.evtx | grep -A5 "EventID.*4625"  # Failed logins\nevtx_dump Security.evtx | grep -A5 "EventID.*4624"  # Successful logins\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- NIST SP 800-86 (Guide to Integrating Forensic Techniques)\n- steghide documentation\n- binwalk: github.com/ReFirmLabs/binwalk\n- man pages: file(1), strings(1), xxd(1)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 2, title: "Digital Forensics in Depth", recommendedLevel: 2,
    sections: [
      { heading: "Disk forensics with Autopsy and Sleuth Kit", content: `\`\`\`bash\n# Create a forensic image\ndd if=/dev/sda of=disk.raw bs=4M status=progress\n# Or with dcfldd for hashing\ndcfldd if=/dev/sda of=disk.raw hash=sha256 hashlog=disk.hash\n\n# Verify integrity\nsha256sum disk.raw\n\n# Analyze with The Sleuth Kit\nmmls disk.raw          # list partitions\nfls -r disk.raw -o 2048  # list files (offset in sectors)\nicat disk.raw -o 2048 42  # extract file by inode number\n\n# Timeline generation\nfls -r -m "/" disk.raw -o 2048 > bodyfile.txt\nmactime -b bodyfile.txt -d > timeline.csv\n\`\`\`\n\nAutopsy (GUI frontend for Sleuth Kit) provides keyword search, hash filtering, timeline visualization, and carved file recovery.`, sortOrder: 0 },
      { heading: "Memory forensics with Volatility", content: `\`\`\`bash\n# Identify the OS profile\nvol.py -f memory.dmp imageinfo\n\n# Volatility 3 (no profile needed)\nvol3 -f memory.dmp windows.info\n\n# List processes\nvol3 -f memory.dmp windows.pslist\nvol3 -f memory.dmp windows.pstree  # tree view\n\n# Find hidden processes\nvol3 -f memory.dmp windows.psscan  # scans for EPROCESS structures\n\n# Network connections\nvol3 -f memory.dmp windows.netscan\n\n# Command history\nvol3 -f memory.dmp windows.cmdline\n\n# Extract files from memory\nvol3 -f memory.dmp windows.dumpfiles --pid 1234\n\n# Registry hives\nvol3 -f memory.dmp windows.registry.hivelist\nvol3 -f memory.dmp windows.registry.printkey --key "Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run"\n\`\`\``, sortOrder: 1 },
      { heading: "Network forensics", content: `\`\`\`bash\n# Analyze pcap files\ntshark -r capture.pcap -q -z io,stat,1\n# Traffic statistics per second\n\n# Extract HTTP objects\ntshark -r capture.pcap --export-objects http,exported_files/\n\n# DNS queries\ntshark -r capture.pcap -Y "dns.flags.response == 0" -T fields -e dns.qry.name | sort | uniq -c | sort -rn\n\n# Find credentials in cleartext\ntshark -r capture.pcap -Y "http.authorization" -T fields -e http.authorization\ntshark -r capture.pcap -Y "ftp.request.command == USER || ftp.request.command == PASS"\n\n# Detect data exfiltration\n# Large DNS queries (tunneling)\ntshark -r capture.pcap -Y "dns.qry.name.len > 50" -T fields -e dns.qry.name\n\`\`\``, sortOrder: 2 },
      { heading: "File carving and recovery", content: `\`\`\`bash\n# Recover deleted files from disk image\nforemost -i disk.raw -o recovered/\nphotorec disk.raw\n\n# Scalpel (configurable carving)\nscalpel -c /etc/scalpel/scalpel.conf -o output/ disk.raw\n\n# From memory\nvol3 -f memory.dmp windows.filescan | grep ".doc\\|.pdf\\|.txt"\nvol3 -f memory.dmp windows.dumpfiles --virtaddr 0xfa8001234567\n\`\`\`\n\nFile carving recovers files based on header/footer signatures, even when filesystem metadata is destroyed. It works on unallocated space, formatted drives, and damaged images.`, sortOrder: 3 },
      { heading: "Sources", content: `- Volatility 3 documentation: volatility3.readthedocs.io\n- The Sleuth Kit: sleuthkit.org\n- Autopsy: autopsy.com/documentation\n- SANS DFIR cheat sheets`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 3, title: "Advanced Forensic Techniques", recommendedLevel: 3,
    sections: [
      { heading: "Windows forensic artifacts", content: `Key Windows artifacts for investigation:\n\n**Registry**:\n- \`NTUSER.DAT\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RecentDocs\` — recently opened files\n- \`SYSTEM\\CurrentControlSet\\Services\` — installed services\n- \`SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\` — persistence\n- \`SAM\` — local user accounts and password hashes\n\n**Prefetch** (\`C:\\Windows\\Prefetch\\*.pf\`): Records of program execution — name, run count, timestamps, files loaded.\n\n**Amcache** (\`C:\\Windows\\AppCompat\\Programs\\Amcache.hve\`): SHA1 hashes of executed programs.\n\n**ShimCache**: Application compatibility cache — tracks executable paths and timestamps.\n\n**Event Logs**: Security (logon/logoff), System (services), PowerShell (script execution).\n\n\`\`\`bash\n# Parse prefetch files\npython3 PECmd.py -d C:\\Windows\\Prefetch --csv output/\n\n# Parse Amcache\npython3 AmcacheParser.py -f Amcache.hve --csv output/\n\`\`\``, sortOrder: 0 },
      { heading: "Linux forensic artifacts", content: `\`\`\`bash\n# User activity\ncat /home/user/.bash_history\ncat /home/user/.zsh_history\ncat /home/user/.local/share/recently-used.xbel\n\n# Authentication\n/var/log/auth.log\n/var/log/secure\nlast -f /var/log/wtmp     # login history\nlastb -f /var/log/btmp    # failed logins\n\n# System activity\n/var/log/syslog\njournalctl --since "2024-01-01" --until "2024-01-02"\n\n# Cron execution\ngrep CRON /var/log/syslog\ncrontab -l -u root\nls -la /etc/cron.d/\n\n# Filesystem timestamps\nstat suspicious_file\n# Access, Modify, Change, Birth times\n\n# Find recently modified files\nfind / -mtime -1 -type f 2>/dev/null\nfind / -newer /tmp/reference_file -type f 2>/dev/null\n\`\`\``, sortOrder: 1 },
      { heading: "Malware triage", content: `Initial analysis of a suspicious file:\n\n\`\`\`bash\n# Static analysis\nfile malware.exe\nstrings malware.exe | less\nstrings -e l malware.exe  # Unicode strings\n\n# PE analysis\npython3 -c "import pefile; pe = pefile.PE('malware.exe'); print(pe.dump_info())"\n\n# Check imports for suspicious APIs\n# VirtualAlloc, WriteProcessMemory → injection\n# CreateRemoteThread → thread injection\n# WinExec, ShellExecute → execution\n# InternetOpen, URLDownloadToFile → C2 communication\n\n# Hash lookup\nsha256sum malware.exe\n# Check against VirusTotal, MalwareBazaar\n\n# Sandbox execution\n# Upload to Any.Run, Hybrid Analysis, or Joe Sandbox\n\`\`\``, sortOrder: 2 },
      { heading: "Timeline analysis", content: `Correlate events across multiple artifact sources:\n\n\`\`\`bash\n# Build a super-timeline with Plaso\nlog2timeline.py timeline.plaso disk.raw\npsort.py -o l2tcsv timeline.plaso -w timeline.csv\n\n# Filter the timeline\npsort.py -o l2tcsv timeline.plaso "date > '2024-06-01' AND date < '2024-06-02'" -w filtered.csv\n\n# Key artifacts to correlate:\n# 1. File creation/modification times\n# 2. Registry modification times\n# 3. Event log entries\n# 4. Prefetch execution times\n# 5. Browser history timestamps\n# 6. Network connection logs\n\`\`\`\n\nThe timeline reveals the sequence: initial access → execution → persistence → lateral movement → data exfiltration. Each phase leaves different artifacts.`, sortOrder: 3 },
      { heading: "Sources", content: `- SANS DFIR Poster: digital forensic artifact reference\n- Eric Zimmerman's tools: ericzimmerman.github.io\n- Plaso documentation: plaso.readthedocs.io\n- MITRE ATT&CK mapped to forensic artifacts`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 4, title: "Expert Forensics Techniques", recommendedLevel: 4,
    sections: [
      { heading: "Advanced memory forensics", content: `Beyond basic process listing:\n\n\`\`\`bash\n# Detect process injection\nvol3 -f memory.dmp windows.malfind\n# Finds: executable pages in process memory not backed by files\n# Common indicator: MZ header in non-image memory regions\n\n# SSDT hooks (System Service Descriptor Table)\nvol3 -f memory.dmp windows.ssdt\n# Hooks redirect system calls — rootkit indicator\n\n# Kernel module analysis\nvol3 -f memory.dmp windows.modules\nvol3 -f memory.dmp windows.modscan  # find hidden modules\n\n# Extract process memory for analysis\nvol3 -f memory.dmp windows.memmap --pid 1234 --dump\n\n# Yara scanning in memory\nvol3 -f memory.dmp yarascan.YaraScan --yara-rules malware_rules.yar\n\`\`\``, sortOrder: 0 },
      { heading: "Anti-forensics detection", content: `Attackers try to cover their tracks:\n\n- **Timestomping**: Modify file timestamps with tools like Timestomp. Detection: compare $STANDARD_INFORMATION vs $FILE_NAME timestamps in NTFS (MFT analysis). $FILE_NAME times are harder to modify.\n- **Log clearing**: Detect via Event ID 1102 (audit log cleared), or gaps in sequential event IDs.\n- **Secure deletion**: Tools like sdelete overwrite file data. Detection: look for MFT entries without corresponding data, or SDelete artifacts in prefetch.\n- **Process hollowing**: Legitimate process with injected code. Detection: compare in-memory image to on-disk binary.\n\n\`\`\`bash\n# Detect timestomping with MFT analysis\nanalyzeMFT.py -f $MFT -o mft_output.csv\n# Compare SI_Created vs FN_Created timestamps\n# Large discrepancies indicate timestomping\n\`\`\``, sortOrder: 1 },
      { heading: "Cloud forensics", content: `Cloud environments require different approaches:\n\n\`\`\`bash\n# AWS CloudTrail analysis\naws cloudtrail lookup-events \\\\\n  --lookup-attributes AttributeKey=EventName,AttributeValue=ConsoleLogin\n\n# Key events to investigate:\n# - ConsoleLogin (especially from unusual locations)\n# - CreateUser, AttachUserPolicy (persistence)\n# - GetSecretValue (credential access)\n# - StopLogging, DeleteTrail (anti-forensics)\n# - RunInstances (cryptomining)\n\n# Azure Activity Log\naz monitor activity-log list --start-time 2024-01-01 --end-time 2024-01-02\n\n# GCP Cloud Audit Logs\ngcloud logging read 'resource.type="gce_instance"' --limit 100\n\`\`\`\n\nChallenge: cloud providers control the infrastructure — you can't image a cloud VM's hypervisor layer. Focus on API logs, flow logs, and application-level artifacts.`, sortOrder: 2 },
      { heading: "Sources", content: `- Volatility 3 plugin reference\n- SANS FOR508: Advanced Incident Response\n- AWS CloudTrail documentation\n- Harlan Carvey, "Windows Forensic Analysis Toolkit" (Syngress)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "forensics", depthTier: 5, title: "Forensics Internals", recommendedLevel: 5,
    sections: [
      { heading: "NTFS internals for forensics", content: `NTFS stores metadata in the Master File Table (MFT). Each file has an MFT entry with attributes:\n\n- **$STANDARD_INFORMATION**: Timestamps (created, modified, accessed, MFT modified), permissions\n- **$FILE_NAME**: Alternative timestamps (set by the kernel, harder to forge), short/long filenames\n- **$DATA**: File content (resident if < ~700 bytes, non-resident otherwise)\n- **$ATTRIBUTE_LIST**: Points to additional MFT entries for files with many attributes\n\n\`\`\`\nMFT Entry structure:\n  Header (fixup, sequence number, link count)\n  $STANDARD_INFORMATION\n  $FILE_NAME\n  $DATA (or pointer to clusters)\n  $INDEX_ROOT / $INDEX_ALLOCATION (for directories)\n\`\`\`\n\nDeleted files: the MFT entry is marked as unused but not overwritten. Data clusters are marked as free but remain until overwritten — this is why carving works.`, sortOrder: 0 },
      { heading: "Windows memory structures", content: `Understanding kernel structures for memory forensics:\n\n- **EPROCESS**: Kernel object representing a process. Contains PID, parent PID, image filename, handle table, token, VAD tree.\n- **PEB** (Process Environment Block): Usermode structure with loaded DLLs, command line, environment variables.\n- **VAD** (Virtual Address Descriptor): Tree describing the process's virtual memory layout — what's mapped where.\n- **Pool tags**: Kernel allocations are tagged (e.g., 'Proc' for process objects). Pool scanning finds objects even when unlinked from active lists.\n\n\`\`\`bash\n# Volatility uses these structures:\n# pslist: walks the ActiveProcessLinks doubly-linked list in EPROCESS\n# psscan: scans for EPROCESS pool tags (finds hidden/terminated processes)\n# vadinfo: dumps the VAD tree (shows memory regions and their protections)\n\`\`\`\n\nRootkits hide by unlinking EPROCESS from the ActiveProcessLinks list — psscan bypasses this by scanning raw memory.`, sortOrder: 1 },
      { heading: "Firmware and UEFI forensics", content: `Below the OS, firmware can harbor persistent threats:\n\n- **UEFI implants**: Survive OS reinstallation. Modify the SPI flash chip containing the firmware.\n- **Bootkits**: Compromise the boot process before the OS loads.\n- **Analysis tools**: CHIPSEC (Intel firmware security assessment), UEFITool (firmware image parser)\n\n\`\`\`bash\n# Dump UEFI firmware\nchipsec_util spi dump firmware.bin\n\n# Analyze with UEFITool\n# Look for: unexpected DXE drivers, modified boot manager,\n# unsigned modules in the firmware volume\n\n# Check Secure Boot state\nchipsec_main -m common.secureboot.variables\n\`\`\`\n\nReal-world examples: Hacking Team's UEFI rootkit (2015), LoJax (2018, first UEFI rootkit found in the wild by ESET), CosmicStrand (2022, Kaspersky).`, sortOrder: 2 },
      { heading: "Sources", content: `- Brian Carrier, "File System Forensic Analysis" (Addison-Wesley)\n- NTFS specification: flatcap.github.io/linux-ntfs/ntfs/index.html\n- CHIPSEC: github.com/chipsec/chipsec\n- ESET research: "LoJax: First UEFI rootkit found in the wild"`, sortOrder: 3 },
    ],
  },
];
