import type { SeedArticle } from "./types";

export const RECON_OSINT_ARTICLES: SeedArticle[] = [
  {
    competencyId: "recon-osint", depthTier: 0, title: "Reconnaissance and OSINT Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is reconnaissance", content: `Reconnaissance is the first phase of any security assessment — gathering information about a target before active testing. It divides into passive (no direct contact with target systems) and active (direct interaction, potentially detectable).\n\nOSINT (Open Source Intelligence) refers to information collected from publicly available sources: websites, social media, DNS records, certificate transparency logs, public repositories, and more.`, sortOrder: 0 },
      { heading: "Why reconnaissance matters", content: `- 80% of a successful engagement is reconnaissance\n- Better recon = fewer blind spots = more targeted attacks\n- OSINT findings can reveal credentials, internal infrastructure, employee information, and technology stacks without touching the target\n- Many organizations underestimate how much information they leak publicly`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Passive recon**: No direct interaction with the target (DNS lookups via third parties, Google dorking, social media)\n- **Active recon**: Direct interaction (port scanning, web crawling, sending requests to target)\n- **Footprinting**: Mapping the target's external presence\n- **Google dorking**: Using advanced search operators to find exposed information\n- **Subdomain enumeration**: Discovering all subdomains of a target domain\n- **Certificate Transparency**: Public logs of all issued TLS certificates`, sortOrder: 2 },
      { heading: "Sources", content: `- PTES (Penetration Testing Execution Standard): Intelligence Gathering phase\n- OWASP Testing Guide v4.2, Chapter 4\n- OSINT Framework: osintframework.com`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "recon-osint", depthTier: 1, title: "Reconnaissance Basics", recommendedLevel: 1,
    sections: [
      { heading: "Passive DNS and WHOIS", content: `\`\`\`bash\n# WHOIS lookup\nwhois example.com\n# Reveals: registrar, creation date, nameservers, sometimes contact info\n\n# DNS records\ndig example.com ANY\ndig example.com MX\ndig example.com TXT\n\n# Reverse DNS\ndig -x 93.184.216.34\n\n# DNS history (passive DNS databases)\n# SecurityTrails, ViewDNS.info, DNSdumpster\n\`\`\`\n\nDNS TXT records often contain SPF, DKIM, and DMARC configurations — and sometimes verification tokens that reveal third-party services (Google Workspace, Microsoft 365, Salesforce).`, sortOrder: 0 },
      { heading: "Subdomain enumeration", content: `\`\`\`bash\n# Certificate Transparency logs\ncurl -s "https://crt.sh/?q=%.example.com&output=json" | jq -r '.[].name_value' | sort -u\n\n# Subfinder (passive sources)\nsubfinder -d example.com -o subdomains.txt\n\n# Amass (comprehensive)\namass enum -d example.com -o amass_results.txt\n\n# DNS brute force (actual DNS resolution)\ngobuster dns -d example.com -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt\n\n# Virtual host enumeration (HTTP-based — not DNS)\n# Sends requests with different Host headers to a known IP\nffuf -u http://10.10.10.10 -H \"Host: FUZZ.example.com\" -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -fs 0\n\n# Check which subdomains are alive\ncat subdomains.txt | httpx -silent -status-code\n\`\`\``, sortOrder: 1 },
      { heading: "Google dorking", content: `Advanced Google search operators for finding exposed information:\n\n\`\`\`\nsite:example.com filetype:pdf        # Find PDF documents\nsite:example.com inurl:admin          # Find admin pages\nsite:example.com intitle:"index of"   # Directory listings\nsite:example.com ext:sql | ext:db     # Database files\nsite:example.com intext:password      # Pages mentioning passwords\n"example.com" filetype:env            # .env files (credentials)\nsite:pastebin.com "example.com"       # Pastes mentioning the target\nsite:github.com "example.com" password # GitHub leaks\n\`\`\`\n\nThe Google Hacking Database (GHDB) at exploit-db.com catalogs hundreds of useful dorks.`, sortOrder: 2 },
      { heading: "Technology fingerprinting", content: `\`\`\`bash\n# Wappalyzer / WhatWeb\nwhatweb example.com\n# Detects: CMS, frameworks, server software, analytics\n\n# HTTP headers reveal technology\ncurl -I https://example.com\n# Server: nginx/1.18.0\n# X-Powered-By: PHP/8.1\n\n# Shodan (search engine for internet-connected devices)\nshodan search hostname:example.com\nshodan host 93.184.216.34\n\n# Censys\ncensys search "example.com"\n\`\`\``, sortOrder: 3 },
      { heading: "Sources", content: `- GHDB (Google Hacking Database): exploit-db.com/google-hacking-database\n- Shodan documentation: shodan.io\n- Certificate Transparency: certificate.transparency.dev\n- SecurityTrails: securitytrails.com`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "recon-osint", depthTier: 2, title: "Reconnaissance in Depth", recommendedLevel: 2,
    sections: [
      { heading: "Social media and people OSINT", content: `\`\`\`bash\n# LinkedIn: employee enumeration, org structure, technology mentions\n# Build employee lists for password spraying\n# Common formats: first.last@company.com, flast@company.com\n\n# Username search across platforms\nsherlock username\n# Checks 300+ social media sites\n\n# Email discovery\ntheHarvester -d example.com -b all\n# Sources: Google, Bing, LinkedIn, Hunter.io\n\n# Verify email addresses\n# Tools: hunter.io, emailrep.io\n\`\`\`\n\nEmployee LinkedIn profiles reveal: technologies used, projects, team structure, and sometimes internal hostnames or tool names. Job postings reveal the tech stack.`, sortOrder: 0 },
      { heading: "Code repository mining", content: `\`\`\`bash\n# Search GitHub for leaked credentials\n# github.com search: "example.com" password\n# github.com search: "example.com" api_key\n\n# Automated secret scanning\ngitleaks detect --source /path/to/repo\ntrufflehog git https://github.com/org/repo\n\n# Search commit history (secrets may be in old commits)\ngit log --all --full-history -- "*.env"\ngit log -p --all -S 'password' -- '*.py'\n\n# GitHub dorking\n# org:company-name filename:.env\n# org:company-name extension:pem private\n# org:company-name "BEGIN RSA PRIVATE KEY"\n\`\`\`\n\nDevelopers frequently commit secrets accidentally. Even if removed in a later commit, the secret persists in git history.`, sortOrder: 1 },
      { heading: "Infrastructure mapping", content: `\`\`\`bash\n# ASN lookup\nwhois -h whois.radb.net -- '-i origin AS12345'\n\n# IP range enumeration\namass intel -org "Example Corp"\n\n# Reverse IP (find domains hosted on an IP)\ncurl -s "https://api.hackertarget.com/reverseiplookup/?q=93.184.216.34"\n\n# Cloud infrastructure detection\n# Check if target uses AWS, Azure, GCP\ndig example.com CNAME\n# .cloudfront.net → AWS CloudFront\n# .azurewebsites.net → Azure\n# .googleapis.com → GCP\n\n# S3 bucket enumeration\naws s3 ls s3://example-com-backup --no-sign-request 2>/dev/null\n\`\`\``, sortOrder: 2 },
      { heading: "Breach data and credential leaks", content: `Previously breached credentials are a primary attack vector:\n\n- **Have I Been Pwned** (haveibeenpwned.com): Check if email appeared in known breaches\n- **Dehashed**, **IntelX**: Search breach databases (paid services used in authorized engagements)\n- Credential stuffing: test leaked passwords against target login pages\n\nPassword reuse is extremely common. A password leaked from a gaming site breach in 2018 may still work for corporate email in 2026.\n\nAlways verify scope and authorization before using breach data in an engagement.`, sortOrder: 3 },
      { heading: "Automating reconnaissance", content: `\`\`\`bash\n# Recon-ng framework\nrecon-ng\n[recon-ng] > marketplace install all\n[recon-ng] > workspaces create example\n[recon-ng] > db insert domains example.com\n[recon-ng] > modules load recon/domains-hosts/certificate_transparency\n[recon-ng] > run\n\n# Custom automation with Python\n# Combine: subfinder → httpx → nuclei\nsubfinder -d example.com -silent | httpx -silent | nuclei -t cves/\n\`\`\``, sortOrder: 4 },
      { heading: "Sources", content: `- OSINT Framework: osintframework.com\n- PTES Intelligence Gathering: pentest-standard.readthedocs.io\n- Michael Bazzell, "OSINT Techniques" (IntelTechniques)\n- Recon-ng: github.com/lanmaster53/recon-ng`, sortOrder: 5 },
    ],
  },
  {
    competencyId: "recon-osint", depthTier: 3, title: "Advanced Reconnaissance Techniques", recommendedLevel: 3,
    sections: [
      { heading: "Attack surface management", content: `Map the complete external attack surface:\n\n\`\`\`bash\n# Full pipeline: discover → probe → scan\n# 1. Subdomain enumeration (multiple sources)\nsubfinder -d target.com -all | sort -u > subs.txt\namass enum -passive -d target.com >> subs.txt\nsort -u subs.txt -o subs.txt\n\n# 2. Resolve and probe\ncat subs.txt | dnsx -silent | httpx -silent -title -status-code -tech-detect > alive.txt\n\n# 3. Screenshot for visual review\ncat alive.txt | aquatone\n\n# 4. Vulnerability scanning\ncat alive.txt | nuclei -t cves/ -t exposures/ -t misconfiguration/\n\`\`\`\n\nThis pipeline discovers hundreds of assets and identifies exposed panels, default credentials, known CVEs, and misconfigurations automatically.`, sortOrder: 0 },
      { heading: "Metadata analysis", content: `Documents published online contain metadata:\n\n\`\`\`bash\n# Extract metadata from documents\nexiftool document.pdf\n# Reveals: author, software, creation date, sometimes internal paths\n\n# FOCA (Fingerprinting Organizations with Collected Archives)\n# Automated document metadata extraction\n# Downloads documents from the target, extracts metadata\n\n# Bulk download documents\nwget -r -l 1 -A pdf,doc,docx,xls,xlsx https://example.com/resources/\nexiftool -r -csv downloaded_files/ > metadata.csv\n\`\`\`\n\nMetadata reveals: internal usernames, software versions, internal server names, directory structures, printer names.`, sortOrder: 1 },
      { heading: "Dark web and underground forums", content: `Monitoring dark web sources for threat intelligence (in authorized engagements):\n\n- **Tor hidden services**: Forums, marketplaces, paste sites\n- **Telegram channels**: Breach announcements, initial access brokers\n- **Ransomware leak sites**: Published data from ransomware victims\n\nTools:\n- OnionSearch: search across .onion sites\n- TorBot: crawl and scrape hidden services\n- Commercial platforms: Recorded Future, Flashpoint, DarkOwl\n\nAlways ensure proper authorization and legal compliance when accessing underground sources.`, sortOrder: 2 },
      { heading: "Wireless and physical reconnaissance", content: `Physical-layer recon for authorized red team engagements:\n\n\`\`\`bash\n# Wi-Fi reconnaissance\nairodump-ng wlan0mon\n# Reveals: SSIDs, BSSIDs, channels, encryption types, connected clients\n\n# Identify corporate Wi-Fi networks\n# Look for WPA2-Enterprise (802.1X) vs WPA2-PSK\n# WPA2-Enterprise with EAP-PEAP/MSCHAPv2 is vulnerable to\n# credential capture with hostapd-mana or eaphammer\n\`\`\`\n\nPhysical: badge cloning (Proxmark3), tailgating, dumpster diving, shoulder surfing — all valid red team techniques with proper authorization.`, sortOrder: 3 },
      { heading: "Sources", content: `- Michael Bazzell, "OSINT Techniques" (IntelTechniques)\n- SANS SEC487: Open-Source Intelligence Gathering\n- ProjectDiscovery tools: subfinder, httpx, nuclei, dnsx\n- EXIF Tool documentation: exiftool.org`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "recon-osint", depthTier: 4, title: "Expert Reconnaissance Operations", recommendedLevel: 4,
    sections: [
      { heading: "Custom OSINT tooling", content: `Build automated OSINT pipelines:\n\n\`\`\`python\nimport requests\nimport json\nfrom concurrent.futures import ThreadPoolExecutor\n\ndef check_subdomain(sub, domain):\n    url = f"http://{sub}.{domain}"\n    try:\n        r = requests.get(url, timeout=3)\n        return {"subdomain": f"{sub}.{domain}", "status": r.status_code,\n                "server": r.headers.get("Server", ""),\n                "title": extract_title(r.text)}\n    except:\n        return None\n\ndef extract_title(html):\n    import re\n    m = re.search(r"<title>(.*?)</title>", html, re.I|re.S)\n    return m.group(1).strip() if m else ""\n\nwith open("subdomains.txt") as f:\n    subs = [l.strip() for l in f]\n\nwith ThreadPoolExecutor(max_workers=20) as ex:\n    results = [r for r in ex.map(lambda s: check_subdomain(s, "target.com"), subs) if r]\n\nwith open("results.json", "w") as f:\n    json.dump(results, f, indent=2)\n\`\`\``, sortOrder: 0 },
      { heading: "Cloud infrastructure enumeration", content: `\`\`\`bash\n# AWS\n# S3 bucket permutation\nfor word in backup dev staging prod assets; do\n  aws s3 ls s3://target-$word --no-sign-request 2>/dev/null && echo "OPEN: target-$word"\ndone\n\n# Check for public snapshots\naws ec2 describe-snapshots --owner-ids ACCOUNT_ID --region us-east-1\n\n# Azure\n# Enumerate blobs\nfor container in backup files data; do\n  curl -s "https://targetaccount.blob.core.windows.net/$container?restype=container&comp=list"\ndone\n\n# GCP\n# Check bucket permissions\ngsutil ls gs://target-bucket/\n\n# Enumerate cloud IP ranges to find target assets\n# AWS: ip-ranges.amazonaws.com/ip-ranges.json\n# Azure: download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public.json\n\`\`\``, sortOrder: 1 },
      { heading: "Threat intelligence correlation", content: `Correlate findings across multiple sources:\n\n- Cross-reference subdomains with Shodan/Censys for exposed services\n- Match employee emails against breach databases\n- Track infrastructure changes over time (passive DNS history)\n- Monitor certificate issuance for new services\n- Correlate IP ranges with cloud provider allocations\n\nFrameworks:\n- Diamond Model: adversary, capability, infrastructure, victim\n- Kill Chain: recon findings map to early kill chain phases\n- MITRE ATT&CK: map findings to Initial Access techniques`, sortOrder: 2 },
      { heading: "Sources", content: `- SANS SEC487: Open-Source Intelligence Gathering\n- AWS IP Ranges: ip-ranges.amazonaws.com/ip-ranges.json\n- Shodan API documentation: shodan.io/api\n- MITRE ATT&CK: Reconnaissance (TA0043)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "recon-osint", depthTier: 5, title: "OSINT Expert Reference", recommendedLevel: 5,
    sections: [
      { heading: "Geolocation and imagery intelligence", content: `Advanced OSINT techniques using visual data:\n\n- **Geolocation from photos**: Analyze shadows, vegetation, architecture, signage, and terrain features to determine location\n- **Satellite imagery**: Google Earth, Sentinel Hub, Maxar for temporal analysis\n- **Street-level**: Google Street View historical imagery for change detection\n- **Metadata extraction**: EXIF GPS coordinates, camera model, timestamp\n\nTools: GeoSpy, SunCalc (shadow analysis), Overpass Turbo (OpenStreetMap queries), Google Lens (reverse image search).\n\nVerification workflow: extract metadata → reverse image search → analyze visual clues → cross-reference with maps → confirm with multiple sources.`, sortOrder: 0 },
      { heading: "Sock puppet and operational security", content: `Creating research personas for OSINT investigations:\n\n- **Identity creation**: Consistent backstory, aged social media accounts, realistic profile photos (use generated faces, never real people)\n- **Infrastructure**: Dedicated VPN/proxy, separate browser profile, no cross-contamination with real identity\n- **Communication**: Burner email, VoIP numbers, encrypted channels\n\nOPSEC for the investigator:\n- Never access target resources from attributable infrastructure\n- Use Tor or VPN chains for sensitive lookups\n- Compartmentalize investigations\n- Consider that some OSINT activities may alert the target (e.g., LinkedIn profile views)`, sortOrder: 1 },
      { heading: "Machine learning for OSINT", content: `AI-assisted OSINT techniques:\n\n- **NLP**: Extract entities, relationships, and sentiment from large text corpora (forum posts, leaked documents, news articles)\n- **Image recognition**: Face matching across platforms, logo detection, object identification\n- **Network analysis**: Graph analysis of social connections, communication patterns, infrastructure relationships\n- **Anomaly detection**: Identify unusual patterns in DNS records, certificate issuance, or infrastructure changes\n\nEthical considerations: facial recognition crosses significant privacy boundaries. Always ensure legal authorization and proportionality. Many jurisdictions have specific laws governing biometric data collection.`, sortOrder: 2 },
      { heading: "Sources", content: `- Bellingcat investigation guides: bellingcat.com\n- OSINT Curious: osintcurio.us\n- Trace Labs OSINT Search Party resources\n- European Data Protection Board guidelines on OSINT and privacy`, sortOrder: 3 },
    ],
  },
];
